### ISSUE TITLE
Feature request: Passkeys support on Android 14

### ISSUE THREAD

**Issue by Fei1Yang** [Yubico/yubioath-desktop#1023]
Android 14 added Credential Manager to allow third party apps to manage passkeys, could this be implemented in this app so YubiKeys can be used for passwordless login on Android?

**Comment by dainnilsson** [comment]
Our hope is that this will natively be supported in Android without the need for an additional app. In the meantime we are investigating this API and will evaluate when/if we should add this type of support to the app, and will continue to do so when the new Android version is released.

**Comment by dainnilsson** [comment]
Google actually has implemented this as part of Google Play Services. I just now verified that it works to authenticate with a Passkey on a YubiKey connected over USB in Chrome. It does seem to have some issues as I wasn't able to get it to work over NFC (even though there is an option for that) and another key failed over USB, but it's there which I think shows promise.

We are currently not actively developing this as a feature for Yubico Authenticator, but may do so in the future.

**Comment by dainnilsson** [comment]
No, my test was with discoverable credentials, this did indeed work. I was prompted for PIN, the Passkey was displayed and I selected it, and the authentication was successful. This was with an empty allowList.

**Comment by dainnilsson** [comment]
I can take some screenshots later. Do note that what I tested was USE of a Passkey, not REGISTRATION of one. Also, due to the flakiness of the implementation, I wouldn't really want to rely on this as a full solution at this point. Mainly I'm pointing it out as a sign that they are indeed working on it.

**Comment by AdamVe** [comment]
I would like to add more information. The FIDO2 Pin protocol support was added in September 2023 (see the official [System Release Notes](https://support.google.com/product-documentation/answer/11412553?hl=en#zippy=%2Cseptember)). The document states, that the Pin Protocol is _Available through Google Play services v23.35 updated on 09/6/2023_

**Comment by p1gp1g** [comment]
I have installed yubico authenticator because I expected it to support this exact feature. Do you think it is possible to reopen this issue ? I suppose this is not rare to not have google services when we use this kind of security key.

**Comment by p1gp1g** [comment]
Is it possible to at least add this information to the readme so other people won't install the app for this ?
