### ISSUE TITLE
QR code capture failing on Arch Linux GNOME

### ISSUE THREAD

**Issue by bgh-github** [Yubico/yubioath-desktop#1024]
The Authenticator app 'Add account > Scan QR code' function is failing with
> Failed reading QR code: Invalid parameters: Unable to capture screenshot

### Environment

* Yubico Authenticator 6.1.0
* `gnome-screenshot` installed
* Same behaviour using the official download directly and [AUR pkgbuild](https://aur.archlinux.org/packages/yubico-authenticator)
* Platform: Arch Linux, rolling, currently kernel 6.2.8-arch1-1
* Desktop Environment: GNOME 43.4
* Windowing System: Wayland

### Troubleshooting

Launching `authenticator` via the terminal, the following error is written whenever the 'Scan QR code' option is selected
> [helper] ERROR: gnome-screenshot: /opt/yubico-authenticator/helper/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/lib/libicuuc.so.72)

It seems the problem may be related to the ./helper/libstdc++.so.6 file bundled (statically linked?) with Authenticator. Manually removing this file was found to work around the problem, allowing QR code screenshots to be captured without issue.

Interrogating the file with `strings /opt/yubico-authenticator/helper/libstdc++.so.6 | grep GLIBCXX`, we can see only GLIBCXX versions  up to GLIBCXX_3.4.25 are returned.

I was curious if the older ubuntu:18.04 container image version in the Linux build workflow could be a factor here.

**Comment by dainnilsson** [comment]
I believe this is due to the issue fixed in #942, which will be included in the next release of the app (most likely later this month).
