### ISSUE TITLE
Add option to change items aftewards

### ISSUE THREAD

**Issue by fredericmohr** [Yubico/yubioath-desktop#106]
I'm using Yubikeys extensively (go 2FA!) and I would love to have the option to edit each item after I added them.

For example, it would be nice to be able to rename them, so I can name them after the same schema (e.g. "project 1 - appname - user"). Unfortunately I didn't plan ahead when naming my items so now I have quite a few named differently and it's a) quite a mess and b) hard to find the right code for my login.

Another thing is, to be able to activate (or maybe even deactivate, if possible) the "require tap to generate code" after creation. Having to remove and re-add an item everytime I want to change something is a bit tedious.

**Comment by dagheyman** [comment]
It is currently not possible to edit the name or settings for a credential stored on the YubiKey, the [protocol](https://developers.yubico.com/ykneo-oath/Protocol.html) does not allow it.

**Comment by nathaniel-holder** [comment]
Is it possible to make a request to change the [protocol](https://developers.yubico.com/OATH/YKOATH_Protocol.html) to allow at least just renaming?

**Comment by fdennis** [comment]
@nathaniel-holder Thank you for your feedback, this is something we will consider for the future.
