### ISSUE TITLE
Package for Ubuntu 16.10 on PPA?

### ISSUE THREAD

**Issue by MatzFan** [Yubico/yubioath-desktop#108]
Hi

I'm migrating from my old Mac to Ubuntu (16.10) and need yubioath-desktop. I see you have maintain a PPA, but that so far you do not have a 16.10 (Yakkety) package. Have you plans to add one soon? If not I'll install it by cloning from this repo.

Many thanks

**Comment by dagheyman** [comment]
Yes, will add this on the upcoming release, which will probably be out this or next week.

**Comment by MatzFan** [comment]
Awesome, thanks for instant response @dagheyman

**Comment by MatzFan** [comment]
Just noticed it is there now, many thanks - closing
