### ISSUE TITLE
yubioath-desktop 3.1.0 does not start on OS X 10.10

### ISSUE THREAD

**Issue by callipeo** [Yubico/yubioath-desktop#109]
I just tried to open Yubico Authenticator for Desktop on Mac OS X 10.0.5, but it crashes on startup. I'm attaching the crash report.

Trying to run it via terminal:

```
$ /Applications/Yubico\ Authenticator.app/Contents/MacOS/yubioath

Illegal instruction: 4
```

[yubioath-desktop_3.1.0_crash_osx_10.10.5.txt](https://github.com/Yubico/yubioath-desktop/files/632441/yubioath-desktop_3.1.0_crash_osx_10.10.5.txt)

**Comment by dagheyman** [comment]
Works well on my 10.10.5 Yosemite machine, it might be worth trying this patch though it shouldn't matter: https://github.com/Yubico/ifd-yubico

**Comment by dagheyman** [comment]
Could you try the build below and see if the issue is still there? https://yubico-builds.s3-eu-west-1.amazonaws.com/yubioath-desktop/yubico-authenticator-3.1.1-dev-mac.pkg

**Comment by ejpcmac** [comment]
@dagheyman I had the same problem with 3.1.0 on OS X 10.10.5, your 3.1.1-dev works well.

**Comment by dagheyman** [comment]
There is now a new mac installer for the 3.1.0 release available here: https://developers.yubico.com/yubioath-desktop/Releases/yubioath-desktop-3.1.0b-mac.pkg
It should resolve the issue.
