### ISSUE TITLE
3.1.0 digits=<n> causes qr scan failure

### ISSUE THREAD

**Issue by not1337** [Yubico/yubioath-desktop#112]
I did try to scan a qr code with an url that contains "digits=8". Scanning such an URL fails.
Actually, it seems that qrencode created images cause behaviour as follows:

otpauth://totp/test?secret=7777AAAA                       scan succeeds
otpauth://totp/test?secret=7777AAAA&digits=6       scan fails
otpauth://totp/test?secret=7777AAAA&digits=8       scan fails

The failing function seems to be parse_bits in gui/qrdecode.py at :
raise ValueError('Unsupported encoding: %d' % enc)

**Comment by dagheyman** [comment]
Thanks for the report. Could you provide an example of a actual QR code that fails?

**Comment by not1337** [comment]
Ok, here's a sample URI for which scanning fails:
otpauth://totp/oathfail-test?secret=XHJXJB4AK5D4UFUU4CLNKUWXB2DSBGPR&digits=8

qrencode version 3.4.4 was used to create the png image (beware of the line wrap):

`qrencode -o test.png 'otpauth://totp/oathfail-test?secret=XHJXJB4AK5D4UFUU4CLNKUWXB2DSBGPR&digits=8'`

The resulting image can't be scanned by yubioath-desktop, a qr code scanner on android has no problems reading the qr code.

![test](https://cloud.githubusercontent.com/assets/17812386/21278370/0e1a73c8-c3db-11e6-8b38-bfe67da713ae.png)

**Comment by dagheyman** [comment]
Thanks for the QR code. Just as you said the application failed to decode it. A fix that solves this error is committed and will be included in the next release.
