### ISSUE TITLE
Windows release of Authenticator distributed with broken, outdated DLLs

### ISSUE THREAD

**Issue by rmenessec** [Yubico/yubioath-desktop#115]
Using the last couple of releases of the Windows build from the Yubico site has given me an extensive headache. The first release I tried—supposedly v3.1.0—threw a number of errors (R6034—apparently quite popular with MSVC projects) (also "Windows error 1114"—again popular) and a message about failing to load a plugin. This happened during login. For reasons I still don't understand, closing all the error dialogs (4) and launching Authenticator manually... worked.

I opened a support ticket with Yubico directly, who didn't really have anything for me, except a suggestion to look again for a newer build. There was one, also ostensibly v3.1.0. When I installed it, Authenticator broke hard, and wouldn't do _anything_ except throw errors, no matter whether I was starting it manually or watching it break automatically on login.

I haven't had time to diagnose the problem specifically, but here's what worked for me:

I deleted all the bare MSVC DLLs being distributed with the installer—_in violation of the license terms_, by the way—and created symlinks to the systemwide DLLs and manifests under ${Windows} (9.0.30729.6161).

When I simply deleted the DLLs, the Python runtime snidely informed me that it wouldn't work without the "missing" DLLs, presumably because it was badly linked and wouldn't consult the system library paths.

Please, distribute the MSVC runtime sensibly, and in compliance with the license: include the installer. Don't start the runtime installer by default unless you've detected that there's _no system instance_ already installed. Refuse to run the installer if the system release is more recent—which is going to be almost always. Otherwise, it's one more time I have to go uninstall an ancient, _insecure_ release of the runtime.

If that's too much work, just include a note in the installer with a link to Microsoft's [The latest supported Visual C++ downloads KB article](https://support.microsoft.com/en-us/kb/2977003) and don't package the MSVC runtime DLLs at all.

_Since you're including the Python runtime, you could even modify the default Python compiler error about missing DLLs to link to that article_.

**Comment by dagheyman** [comment]
Do you have any reference to that redistributing the MSVC DLLs would violate the licence? My understanding is that [application local deployment is allowed](https://msdn.microsoft.com/en-us/library/ms235299.aspx), but I may have misunderstood something. 

What version of Windows are you running btw?

**Comment by rmenessec** [comment]
Windows 7SP1 x64 with the latest rollups and Microsoft EMET-latest running mostly defaults.

I have an older copy of the terms consistent with the MSVC 2k8 you're using—you're looking at the MSVC 2k15 license; not the MSVC 2k8 license—that's pretty clear about not redistributing individual files.

However, the license terms you linked to have this to say:

> It's also possible to directly install redistributable Visual C++ DLLs in the application local folder, which is the folder that contains your executable application file. _For servicing reasons, we do not recommend that you use this installation location._

And, for what it's worth, after I rebooted my test system, Authenticator promptly stopped working again, but this time with new errors directly from the Python runtime. So I still don't have a working Authenticator to roll out, although I did at least keep a copy of the older 3.1.0 Authenticator that I confirmed "sort of sometimes" works.

I've got most of the other Yubico tools installed on the test system, and those work without any apparent errors. Those all seem to rely on the same MSVC9-, 10-, or something-and-Python-and-Qt runtime framework as well.

I strongly suggest standardizing on a single MSVC runtime; 2015 Community Edition is free for all uses, including commercial. 2017—near final release—is expected to be licensed much the same way. I don't recall the timeframe, but all public support for MSVC 2k5 and earlier--including security fixes--has ended. 2k8 is probably very close to losing support as well. If you switch to at least 2k15 now / soon, you won't have to worry about support again for quite a while.

Also, now that I've had a chance to assess other dependencies: you're distributing **OpenSSL** several versions old (for the 1.0.2 branch) with known vulnerabilities.

There is no official packaging of OpenSSL for Windows, but one of these solutions should work for keeping both redist and dev sides up to date:

https://wiki.openssl.org/index.php/Binaries

I use the first listed in order to keep a single systemwide set of OpenSSL binaries up to date on each machine.

**Comment by dagheyman** [comment]
We use [PyInstaller](http://www.pyinstaller.org/) to build the Windows version, which I think includes msvcp90.dll because Python 2.7 needs it. I believe OpenSSL comes from from [PySide](https://pypi.python.org/pypi/PySide/1.2.4). This stack probably needs to be updated at some point anyway (no Qt5 support in PySide for example), and what MSVC runtime to use should definitely be a part of that.

The latest Windows build does seem to work well on the Win7 32bit SP 1 machine I'm testing on though. What are the exact error messages you get?

**Comment by rmenessec** [comment]
This may easily be a problem with x64 Windows.

(I have—pretty much everyone has—hundreds or thousands of hours invested in x64 system images, not to mention x64-only or x64-performant software to run. So x86 Windows is not an option. Full stop.)

3x:
![yubio-ath-error-0](https://cloud.githubusercontent.com/assets/425616/21829891/1b0a4730-d767-11e6-817c-2b8dc9d0050e.png)

1x:
![yubio-ath-error-1](https://cloud.githubusercontent.com/assets/425616/21829890/1b025322-d767-11e6-9521-b1833d7be1e7.png)

**Comment by dagheyman** [comment]
![win7](https://cloud.githubusercontent.com/assets/9592259/21849457/250fca44-d806-11e6-9e26-392595dc9eb3.png)
Doesn't seem to be x64 in itself neither, this is from a fresh install. Not sure what conditions that may trigger it.

**Comment by rmenessec** [comment]
All I can offer at the moment is that it appears to be affected in some way by Windows' default DLL caching; it's strongly suggested by the way my "solution" (remove all the DLLs and provide symlinks) failed immediately after a reboot, and the way that the old (Oct/Nov?) build fails on login, then works afterward... until logout.

Can you provide a native x64 build, just to rule out the possibility it has something to do with bitness?

Also, do you have debug builds? I'm happy to provide logs, stack traces, dumps, _etc._ I just need to know what information would give you a better picture of what's happening.

Also—last item—all the system images I've tested have loads of other software, including other MSVC-Python-Qt ports of this and that application, not to mention all the other YubiKey tools (in total: Authenticator, Client API, NEO Manager, Personalization Tool, PIV Manager). The _only_ software failing or even misbehaving slightly is Authenticator. Half or more of the other installed apps use one version or another of the MSVC DLLs.

I haven't tested to be sure that the other YubiKey tools work on a "naked" login (no Authenticator start on login), but they certainly all work fine after a normal login with Authenticator starting and failing. Given that all the other apps have their own local DLLs—I assume they're _all_ linked to ignore systemwide MSVC DLLs?—it makes me inclined to point the finger at Authenticator or its packaging.

I have an array of utilities already available that might help with debugging the issue: all the Microsoft [Sysinternals](https://technet.microsoft.com/en-us/sysinternals/bb842062.aspx) suite, about half the [NirSoft](http://www.nirsoft.net/) tools, [Process Hacker](http://processhacker.sourceforge.net/), _etc._

I also happen to be evaluating the [RC of Visual Studio 2017](https://www.visualstudio.com/vs/visual-studio-2017-rc/). I've got the core MSVC++ suite, IDE, and Windows SDK installed at the moment, and I can add more components.

**Comment by dagheyman** [comment]
Could you try this build?
https://s3-eu-west-1.amazonaws.com/yubico-builds/yubioath-desktop/yubioath-desktop-3.1.0b-dev-win.exe

It's the same source, but it's built on Win 7 (x64) instead of 10 with minimal extra developer tools installed.

**Comment by rmenessec** [comment]
No difference from the older version I was using. (Tested by logging out / in and restarting test systems.)

I should have been more specific: is there an x64 build somewhere? Can you produce one?

Otherwise, is there more information I can provide?

**Comment by rmenessec** [comment]
@dagheyman , can you please provide an update? I'm still waiting to hear if there's some sort of debugging info, logs, or something else I can provide to get this bug fixed and closed.

I'm nearing a go / no go point with my rollout, and I need to know that I can get support from Yubico for this and future issues. If not, I have a hardware order to cancel and alternate 2FA hardware to source.

**Comment by rmenessec** [comment]
One other note: the outdated—insecure—MSVC and OpenSSL DLLs are not going to pass our desktop security validation suite.

**Comment by dagheyman** [comment]
When you tried the 3.1.0b build linked above, did you do a full uninstall or just ran the installer? We have seen similar issues as yours which could be resolved by making sure that the old installation was completely removed (verify that the installation folder is empty/gone). 

You could also try to install this tool, [YubiKey Manager](https://developers.yubico.com/yubikey-manager-qt/Releases/yubikey-manager-qt-0.3.0-win.exe). Does that start without errors? We are working on a new version of Yubico Authenticator that will have an architecture similar to YubiKey Manager and use a more modern stack.

**Comment by rmenessec** [comment]
I tried it both ways. Are there any discarded Registry entries left behind by the installer? Do I need to remove something from the user profile folders? Clean any ash-and-trash folders besides %UserProfile%\Temp ?

Also, the YubiKey Manager is not a lot of help if it's neither production-ready, nor available in a build that includes the Authenticator functions. Beta software is not a solution. You seem to be suggesting that it won't include Authenticator functions, and that the new Authenticator isn't ready.

Separately, I'm very serious that the DLL issue needs to be addressed—for all the extant YubiKey support / admin and end-user apps. If it's not possible to replace the outdated / vulnerable OpenSSL and MSVC DLLs on my own—and I'd rather not do that in any case—then I need a build that has up-to-date DLLs that will pass compliance testing.

Also, I appreciate the effort, but I'm working on a very short timeline. Software that won't be ready for months (years?) does not help me. I have until the end of this month or a little less to decide whether I proceed with YubiKey acquisition and initial roll-out, or just buy another batch of the 2FA tokens I already have to supplement existing stock.

**Comment by dagheyman** [comment]
So, which was the latest working version of Authenticator that you were able to run on your system?
Could you try the installer for YubiKey Manager just so we know if it works or not?

**Comment by rmenessec** [comment]
I repeat: 

> I tried it both ways. Are there any discarded Registry entries left behind by the installer? Do I need to remove something from the user profile folders? Clean any ash-and-trash folders besides %UserProfile%\Temp ?

After—if—we get Authenticator working, I'll consider beta-testing your new product.

**Comment by rmenessec** [comment]
This one question should have been extremely trivial to answer.

I'm out of time now so we're moving forward with our existing vendor instead of purchasing and deploying YubiKeys.

I do have a YubiKey for personal use, though. If you come up with security fixes or functionality fixes for the desktop Authenticator, I'd be interested in hearing about it.

**Comment by dagheyman** [comment]
The new version of Yubico Authenticator (4.0.0) has been released now, with a new stack. Could you try to see if the issues remain? https://developers.yubico.com/yubioath-desktop/Releases/

**Comment by dagheyman** [comment]
Closing this since we're not shipping .dlls from PyInstaller anymore, feel free to open new specific issues if necessary.

**Comment by rmenessec** [comment]
I'm curious to know how you came to this conclusion.

You're still installing outdated DLLs, or at least they're contained in both the installer and the install directory. I'm definitely certain I don't have any software installed that would unpack your installer, insert DLLs in it, and repack it.

This time, it's d3dcompiler_47.dll (Direct3D 10—absolutely unnecessary), mfc100u.dll, mfcm100u.dll, and msvcp140.dll, and vcruntime140.dll.

Again: don't ship Visual Studio DLLs. Either provide a download link for the runtime installers, or include the installers, but _**DON'T**_ install them if a newer version is already present.

**Comment by rmenessec** [comment]
Adding:

sqlite3.dll (not a Microsoft DLL, I know, but you're using 3.8 instead of [3.17](http://sqlite.org/releaselog/3_17_0.html).)
ucrtbase.dll

This is clearly a systemic problem in which no one is paying attention to the build dependencies to see if there's a better version or if you're shipping a dangerously outdated / insecure version. From a quick look through the dependencies, the only thing recent is your Qt build.

I haven't determined what version Scintilla is, so you might want to check and be sure it's 3.7.0.

**Comment by dagheyman** [comment]
So, for the Windows builds we use the [Windows Deployment Tool](http://doc.qt.io/qt-5/windows-deployment.html) from Qt, and then the `msvcp140.dll` and the redistributable dlls from the [Universal CRT](https://blogs.msdn.microsoft.com/vcblog/2015/03/03/introducing-the-universal-crt/) are added on top of that. The whole process can be found in this [appveyor file](https://github.com/Yubico/yubioath-desktop/blob/master/appveyor.yml).

As a first step to improve this I plan to stop adding dlls manually and instead launch the Visual C++ Redistributable Package installer from our installer (our NSIS script can be [found here](https://github.com/Yubico/yubioath-desktop/blob/master/resources/win/win-installer.nsi)), as both you and Qt [recommends](https://bugreports.qt.io/browse/QTBUG-56566?focusedCommentId=334648&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-334648).

I also noted now that there is a `--no-system-d3d-compiler ` flag for windeployqt, so maybe direct3d can be fully excluded, will try that as well.

**Comment by rmenessec** [comment]
> I also noted now that there is a --no-system-d3d-compiler flag for windeployqt, so maybe direct3d can be fully excluded, will try that as well.

I'm deeply confused about why—whomever built windeployqt—thought that they needed to bundle a D3D DLL. D3D 10 is shipped in Windows 7, and it's patched and updated (if at all) via Microsoft hotfixes. D3D 10/11/12 ship as part of later Windows releases.

If I'm mistaken, and this is a mislabeled D3D9 DLL, well, there's a [redist installer](https://www.microsoft.com/en-us/download/details.aspx?id=8109) for D3D9 as well... but no one should be using D3D9 at all by this point. There's a reason the last/latest installer is for the June 2010 release; it's been deprecated for years. Support ended with Windows XP's support, so far as I'm aware.

In short, you may want to report an upstream bug.

**Comment by rmenessec** [comment]
Separate note: I was able to remove every extraneous DLL. Authenticator is loading without any issues, both immediately, and several reboots later. Either it's using the system or redist DLLs, or else it's including DLLs it doesn't use. I don't have time to look through the imports for this big pile of EXEs and DLLs right now.

If it's using the system or redist DLLs correctly, then at least this release is linked correctly.
