### ISSUE TITLE
3.1.0b Can't delete an entry once it has been added

### ISSUE THREAD

**Issue by codfather** [Yubico/yubioath-desktop#119]
OSx Sierra 10.12.3
Used with a Nano 4

Hi,

I have added a site that would not work with the Authenticator - Amazon - so I wanted to remove and re-start the process. But clicking the Delete button has no effect at all.
When I run yubiauth show from the command line I get this error.

> $./yubioath show
github.com      123456 <- this site is working fine btw
Failed to execute script yubioath-script

I have attached a picture of what the screen looks like of the item it will not let me delete.
<img width="447" alt="screen shot 2017-03-02 at 08 07 16" src="https://cloud.githubusercontent.com/assets/688333/23498402/7cd1c1de-ff1f-11e6-8b8b-2cc3815a5595.png">

If you can let me know where the logs are, how to turn on debug mode etc, I can help diagnose the problem.

Cheers

Nick

**Comment by dagheyman** [comment]
The YubiKey can store OATH credentials in two ways, on the CCID (Smart card) side and the "YubiKey Slot" side, where you only have two slots (and slot 1 is preconfigured with a Yubico OTP credential.) It looks like you are trying to delete slot 2, which seems to be empty? If the application is set to read from slots, they will show up even if they are empty or have another kind of credential configured. I recommend turning off reading from slots under "Settings", and only using the CCID part.

**Comment by codfather** [comment]
Thanks for the update I will look into this. The documentation is very far from clear on this info. 

I shall look into turning on CCID - if you have a links on docs to do that , it would be v. useful.

**Comment by dagheyman** [comment]
Your YubiKey 4 probably already have CCID turned on (all new keys are shipped like this), but you can confirm this using the YubiKey Manager [GUI](https://developers.yubico.com/yubikey-manager-qt/) (look under "Connections") or  [Command line version](https://developers.yubico.com/yubikey-manager/) (do `ykman info`).

Yubico Authenticator currently has no setting to turn CCID off, so if CCID is enabled on the key and the OS supports it (Sierra should be no problem) it should find the credentials.

**Comment by codfather** [comment]
FYI - I have installed those two tools , but they need Python3 - which most people won't have as their defaults. You can use virtual env's to get around this for the CLI tool, but not the GUI. 

Having checked with the CLI tool - CCID is indeed enabled, but I have no idea if my oauth creds are being stored there or in the slots as you mentioned. Also this should remain open, as the fact I now have authenticator with a item I can't delete is certainly not a feature , and should be regarded as a bug.

**Comment by codfather** [comment]
Here is the output from the tool
$ykman info
Device name: YubiKey 4
Serial number: 1234567 <changed> 
Firmware version: 4.3.4
Enabled connection(s): OTP+U2F+CCID

Device capabilities:
    OTP:	Enabled
    U2F:	Enabled
    CCID:	Enabled
    OPGP:	Enabled
    PIV:	Enabled
    OATH:	Enabled

**Comment by dagheyman** [comment]
The YubiKey Manager GUI comes with a [.pkg package](https://developers.yubico.com/yubikey-manager-qt/Releases/) for mac, which includes the Python 3 runtime.

The output means CCID is enabled on your key.

Did you disable "Read from slot" under preferences? Because I don't think the credential is still there. You could try `ykman slot info` to see if something is programmed in the slots.

**Comment by codfather** [comment]
Here is the output from that command:
$ykman slot info
YubiKey 4
Slot 1: programmed
Slot 2: empty

FYI - With regards that GUI tool - when run with the default Sierra python two - it errored everywhere, once I had installed all the pip dependencies mention for the CLI tool , it's now running fine.
