### ISSUE TITLE
Feature requests / bug reports.

### ISSUE THREAD

**Issue by brendanhoar** [Yubico/yubioath-desktop#12]
Yubico support suggested that I submit this directly to github.

---

I have some (hopefully minor) requests for and would like to report some possible bugs in the Yubico Authenticator windows client. Most of this is UI stuff.

---

Background:

I am using Yubico Authenticator 0.1.1 WINDOWS version in Windows 7 64-bit.
My Yubikey Neo serial # is 300xxxx and it has been configured as [HID+CCID with touch-eject].
Slot 1: YubiOTP
Slot 2: OATH secret for my Google account (using YubiTOTP)
Other credentials: OATH secret for Google account is also stored in YubiOATH applet.

---

Feature requests to consider:

1. An option or hardcoded setting to limit the time (e.g. 5 minutes) and/or the number of waves of OTPs (e.g. 10 waves) that are generated after entering the pin/password. Then discard the current session with the Yubikey NEO and close the window. Require the user to re-enter the pin/password and then re-authenticate with the Yubikey Neo.

Because there is no physical interaction required to generate these codes from a device that might stay plugged in most of the time, I think this kind of change would be wise to reduce the ability to compromise codes from an unattended session/screen.

2. Also or alternately make the window close [X] discard the current session and require pin/password re-authentication.

3. The warning dialog box (see below) should auto-clear once the yubikey neo is inserted, and the password dialog box should immediately be brought up.
---------------------------
Warning: No Yubikey NEO detected
---------------------------
No Yubikey NEO found. Please plugin your Yubikey NEO in one of your USB port
---------------------------
OK
---------------------------

-------------------------------------------------------------------------------------------------------------------

Possible bugs:

1. Unlike other windows/dialogs, bringing up the password dialog removes the yubikey authenticator from the systray. Especially confusing if the password dialog ends up behind some other window, which happens in windows from time to time. The first few times this happened, I thought that the process exited, when in fact, it was still running behind other apps. Note: exiting the password dialog already restores the icon.

2. A right-click/show-codes action should bring the Yubico Authenticator main/codes window to the front if it is already open. Double-click on the system tray icon already does this correctly, but right-click/show-codes does not.

3. After removing the yubikey neo and double-clicking, the warning dialog box is sometimes generated behind other windows.

4. After removing the yubikey neo and double-clicking, the warning dialog box is sometimes generated in front of other windows, but does not have focus.

5. The above two items sometimes occur with the password dialog box as well.

6. The main window gets renamed from "Yubico Authenticator" to "Authenticator Authenticator" after closing and re-opening it.

7. Sometimes after inserting the yubikey neo after a warning that the yubikey is not inserted, the application will recognize the reinserted yubikey neo enough to ask for the password, but then after entering the password, it again gives the warning instead of opening the Yubico Authenticator dialog. Apparently at this point the only solution is to both quit the program and remove and reinsert the yubikey neo. Looking at the github history, it may be the case this item is being worked on already.

Thanks,
Brendan

PS - I know the window/dialog stack order and window/dialog focus stuff doesn't always work as documented in windows, so I feel your pain on that. :) Also, I'm really looking forward to the new FIDO U2F support on your to be released/new devices soon.

**Comment by dainnilsson** [comment]
Closing this as 2.x.x is a complete rewrite of the software. If anything in here is still applicable to the new version, feel free to open a new issue!
