### ISSUE TITLE
ux improvement - retain window dimensions between launches

### ISSUE THREAD

**Issue by xortim** [Yubico/yubioath-desktop#120]
In many use-cases there will be numerous accounts added to the YubiKey, but will not change too frequently. Sometimes the ordering of these accounts forces the user to scroll and requires extra steps from the user to get to the code they require. If the user resizes the window to show more codes/accounts at the same time, then the new window dimensions should persist between launches of the yubico authenticator application. Another option to "reset" or a file in which the user can customize the window dimensions would also be useful.

**Comment by dagheyman** [comment]
Agreed that we should save the dimensions, we could probably use the [Settings](http://doc.qt.io/qt-5/qml-qt-labs-settings-settings.html#details) for this.

**Comment by ferenczy** [comment]
It used to work in the version 3.0.1 (and most probably in 3.1.0 also), so the fact it's not working anymore is most likely related to the complete UI rewrite in the version 4.

**Comment by dagheyman** [comment]
http://stackoverflow.com/questions/31426528/saving-window-state-with-qml

**Comment by dagheyman** [comment]
This is now implemented. I'm not adding an extra option to reset the window size though, just resize it back the usual way.
