### ISSUE TITLE
ux improvement - default focus to search field

### ISSUE THREAD

**Issue by xortim** [Yubico/yubioath-desktop#121]
When the authenticator GUI is launched, the search field does not have the default focus. By focusing the search field by default, it will allow users with multiple accounts added to the YubiKey rapid access to the code they require without much other interaction (such as scrolling).

**Comment by dagheyman** [comment]
I see what you mean, but right now the arrow keys has focus at startup which means you can select a credential with those. Focus on the search bar is only one press on the tab key away.

**Comment by xortim** [comment]
Good to know. Perhaps an option for the user to decide which should have the default focus?

**Comment by ferenczy** [comment]
It's two key presses away actually. The first <kbd>tab</kbd> press visually does nothing, after the second press, the focus is moved into the search field.

Also, when I write something into the search field, I cannot go into the credential list using the keyboard. When I press the <kbd>tab</kbd> key for the first time, the search field looses focus, the second key press does nothing visually and the third key press moves the focus back into the search field.

**Comment by ferenczy** [comment]
I just found out that the following scenario is working, but it's not very friendly and moreover it works just once:

1. Execute the app
2. Press the <kbd>tab</kbd> key twice to focus the search field
3. Write something to filter the credentials
4. Press the <kbd>tab</kbd> to focus the credential list
5. Press the down arrow to select the first credential
6. Now you can use for example <kbd>Ctrl</kbd> + <kbd>C</kbd> to copy the code

It's not working when anything was already selected previously (so when you'll go to the search field again and filter something else, it won't work anymore).

I wonder what gets the focus after the first <kbd>tab</kbd> press when you're in the credential list. I didn't manage to find out.

**Comment by dagheyman** [comment]
Thanks for the feedback/testing, I'll look into figuring out the focus issues.

**Comment by dagheyman** [comment]
Closing this issue since the "Two presses on tab" bug is fixed, and the search filter now selects the top result. 

The flow should now be:
 1. Execute the app
 2. Press the <kbd>tab</kbd> key or <kbd> Ctrl</kbd> + <kbd>F</kbd> to focus the search field
 3. Write something to filter the credentials
 4. Press <kbd> tab</kbd> to focus on the credential list
 5. Now you can use for example <kbd>Ctrl</kbd> + <kbd>C</kbd> to copy the code

It could maybe be improved even more though (focus search on any letter press?, copy code on enter?).
