### ISSUE TITLE
Application won't launch after upgrade (4.0.0)

### ISSUE THREAD

**Issue by drohm** [Yubico/yubioath-desktop#123]
I just upgraded to the latest version (4.0.0) through  APT and the application will not launch now.  When I click the link in the launcher, nothing happens.

OS: LinuxMint 18.1 Cinnamon (x64)

When I try launching the application from the command line, I get the following message:

```
QQmlApplicationEngine failed to load component
qrc:///qml/main.qml:6 module "Qt.labs.settings" is not installed
```

**Comment by drohm** [comment]
Issued the following cmd and it launches now:

```
sudo apt install qml-module-qt-labs-settings
```

Is this possibly a missing dependency for the installer? Otherwise go ahead and close.

**Comment by dagheyman** [comment]
Yes, `qml-module-qt-labs-settings` should probably be added as a dependency for the debian package. Thanks for the report!
