### ISSUE TITLE
Missing shortcuts for macOS

### ISSUE THREAD

**Issue by xlc** [Yubico/yubioath-desktop#131]
With new v4 release some very useful shortcuts are not working anymore.

- cmd + w should close window
- cmd + f should focus on search and allow me to start typing 

Also now I have to click to select then cmd + c to copy instead of just single click the copy button to copy?
It should allow single or double click to copy

Also cmd + c copy have no feedback at all. Normally if there is Edit menu and cmd + c and other shortcuts will flash the menu indicates there is action been done

**Comment by dagheyman** [comment]
> cmd + w should close window

Could you explain a little why this is needed? `Cmd + Q` currently quits the application and `Cmd + H` hides the window. What would the expected behaviour be for `Cmd + w`?

> cmd + f should focus on search and allow me to start typing

Agreed, this should be added.

> Also now I have to click to select then cmd + c to copy instead of just single click the copy button to copy? It should allow single or double click to copy

I see your point, will experiment a little with copying on double-click probably.

>Also cmd + c copy have no feedback at all. Normally if there is Edit menu and cmd + c and other shortcuts will flash the menu indicates there is action been done

Good point as well, will look into this.

**Comment by xlc** [comment]
> Could you explain a little why this is needed? Cmd + Q currently quits the application and Cmd + H hides the window. What would the expected behaviour be for Cmd + W?
Every apps on my machine that have window can be closed with cmd + w. Some of them quit if last window is closed, which may be the behavior you want. I don't use cmd + q normally because it may close other windows so I use cmd + w to close everything. I don't want this app become an exception.

Also close window without quitting the app will provide faster resume time when I need it. It only need to create the window without starting from beginning. 

For v4 it took me about 2s from click the icon on dock to launch app to 2fa code visible.
For v3, if I only close the window without quit the app, it took < 0.5s to show the window again

**Comment by dagheyman** [comment]
Fixes for closing on Cmd + W, and give focus to the search bar on Cmd + F are pushed to the master branch. I'm closing this issue and creating two new ones for visual feedback on copy and closing window without quitting the application.
