### ISSUE TITLE
macOS: Close window without quitting the application

### ISSUE THREAD

**Issue by dagheyman** [Yubico/yubioath-desktop#132]
On macOS it is common to close the last window without quitting the application.
[setQuitOnLastWindowClosed](http://doc.qt.io/qt-5/qguiapplication.html#quitOnLastWindowClosed-prop) could be set to false, but a way to bring back the main window is needed.

[Thread on Qt forum.](https://forum.qt.io/topic/77462/macos-re-open-applicationwindow-when-setquitonlastwindowclosed-is-false)

From #131 : 
> Every apps on my machine that have window can be closed with cmd + w. Some of them quit if last window is closed, which may be the behavior you want. I don't use cmd + q normally because it may close other windows so I use cmd + w to close everything. I don't want this app become an exception.
>
> Also close window without quitting the app will provide faster resume time when I need it. It only need to create the window without starting from beginning.
>
> For v4 it took me about 2s from click the icon on dock to launch app to 2fa code visible.
For v3, if I only close the window without quit the app, it took < 0.5s to show the window again

**Comment by emlun** [comment]
Version 4.1.0 and later have an option to close to system tray which seems like it should fit the described desired behaviour. With this option enabled, <kbd>Cmd</kbd>+<kbd>W</kbd> will close the window but leave the app running in the system tray; and <kbd>Cmd</kbd>+<kbd>Q</kbd> will always close the app completely.
