### ISSUE TITLE
Visual feedback when copying codes

### ISSUE THREAD

**Issue by dagheyman** [Yubico/yubioath-desktop#133]
Broken out from #131

No visual feedback is given to the user when copying codes with the keyboard shortcuts. On macOS this could possibly be solved by having a Edit menu in the menu bar with the Copy/Generate/Delete options. The Edit menu would then flash when performing those operations. Not sure about Windows and Linux.

**Comment by dagheyman** [comment]
Added the Edit menu, which will give visual feedback on macOS.

**Comment by ilya40umov** [comment]
This would be really nice to have and would allow to immediately spot issues like #144

**Comment by dagheyman** [comment]
Visual feedback is now implemented on all platforms, since version 5.0.0.
