### ISSUE TITLE
Application starts only from cli and with errors after upgrade (4.0.0)

### ISSUE THREAD

**Issue by yubiuser** [Yubico/yubioath-desktop#135]
I just upgraded to the latest version (4.0.0) through PPA and installed qml-module-qt-labs-settings as suggested (https://github.com/Yubico/yubioath-desktop/issues/123) to get yubioath-desktop to start at all.

When I try launching the application from the command line, I get the following message:

> qrc:///qml/main.qml:185:13: QML ColumnLayout: Binding loop detected for property "width"
qrc:///qml/main.qml:185:13: QML ColumnLayout: Binding loop detected for property "width"

When I click the link in the launcher, nothing happens.

OS: LinuxMint 18.1 Cinnamon (x64)

**Comment by dagheyman** [comment]
Not able to reproduce.

Installed yubioath-desktop on a fresh Linux Mint 18.1 Cinnamon (which gave me 2.3.0), then upgraded to 4.0.0 through the ppa. `qml-module-qt-labs-settings` was needed as you said, but the launcher icon kept working as it should.

Maybe you have modified the launcher entry in some way? The binary has been renamed from `yubioath-gui` to `yubioath-desktop` with the latest release, if that helps.

I've noticed the Binding loop errors on Linux as well, but I don't think it is related to the application not launching.

**Comment by yubiuser** [comment]
You're right, my mistake. The launcher didn't update to the new name of the binary.
