### ISSUE TITLE
Add default sorting for entries

### ISSUE THREAD

**Issue by rmenessec** [Yubico/yubioath-desktop#136]
Entries appear to be displayed in random order.

I'm constantly using Authenticator to log into multiple sites, and it's hard to find entries without resorting to the search field. I have 16 credentials on the key I'm using.

I'm a heavy keyboard user, and without a Ctrl+F shortcut (shortcuts would be good, too) it's breaking my workflow every time I have to reach over and grab the mouse.

**Comment by dagheyman** [comment]
Ctrl + F shortcut is added on master and will be in next release. But I agree some sorting of the entries would make sense.

**Comment by rmenessec** [comment]
What's the upper limit on authentication credentials stored on the YubiKey? (If it's dependent on hardware generation: I have a recent-manufacture NEO and an early 4 Nano from before the USB slot keying revision.)

As more sites add 2FA support, I'm adding more and more credentials. At some point—probably soon—it's going to be worthwhile to add some simple features to help navigate the entries; things like (optionally) promoting frequently-used entries to something like a "top three" list, an ability to hide or lower the list priority of infrequently-used credentials (manually, automatically, or both), and possibly adding a simple multi-column view.

Would you consider these items? I'd be happy to break them out into separate issues.

Thanks!

**Comment by dagheyman** [comment]
> What's the upper limit on authentication credentials stored on the YubiKey? (If it's dependent on hardware generation: I have a recent-manufacture NEO and an early 4 Nano from before the USB slot keying revision.)

For the YubiKey 4 it is 32. For the NEO it actually depends on how much space that is allocated by the other parts (such as PIV, OpenPGP), but it should be somewhere around 28 credentials.

> At some point—probably soon—it's going to be worthwhile to add some simple features to help navigate the entries; things like (optionally) promoting frequently-used entries to something like a "top three" list, an ability to hide or lower the list priority of infrequently-used credentials (manually, automatically, or both), and possibly adding a simple multi-column view.

Not bad ideas, thanks for the suggestions. I guess they could be summarised as "ways to make it easier handling 20+ credentials beyond the search bar". Will think about that problem more when the rough edges from the 4.0.0 release has been dealt with.
