### ISSUE TITLE
Add scroll on selection change

### ISSUE THREAD

**Issue by rmenessec** [Yubico/yubioath-desktop#137]
I'm primarily using the keyboard (Up Arrow / Down Arrow) to select credential entries in Authenticator, but the entry list isn't scrolling as the selections change. On a display with a horizontal resolution of 1080px, even applying vertical maximization to Authenticator doesn't make it high enough to display all 16 credential entries. This leaves about 5 (6?) entries offscreen as I'm trying to select them.

Because entries are displayed in random order (see #136 ), I have no idea what selection's highlighted once the highlight drops through the bottom of the window.

Please scroll the credential list on selection change.

Thanks!
![yubioath0](https://cloud.githubusercontent.com/assets/425616/24270312/037a8938-0feb-11e7-8202-e873e7a5342f.png)

**Comment by dagheyman** [comment]
Agreed, probably related to #122 .

**Comment by dagheyman** [comment]
Should be solved by f33b57b866963c67605559db782f04e374c50abd.

**Comment by rmenessec** [comment]
@dagheyman Do you have nightly or other snapshot builds available somewhere? I don't believe that I have a build environment right now that would work with this.

Incidentally—is the project set up to be able to cross-compile? My personal Windows build environment is under repair at the moment.

**Comment by dagheyman** [comment]
> Do you have nightly or other snapshot builds available somewhere? I don't believe that I have a build environment right now that would work with this.

Kind of. [Here](https://yubico-builds.s3-eu-west-1.amazonaws.com/yubioath-desktop/yubioath-desktop-master--HEAD-win.zip) is the url to the latest windows build from the latest commit on the master branch. It's just the installation directory, it is not signed and have no installer etc. So it's not suitable for production use, but for testing features it should be fine.

> Incidentally—is the project set up to be able to cross-compile? My personal Windows build environment is under repair at the moment.

No, not at the moment. Also not sure how well [PyOtherSide](https://pyotherside.readthedocs.io/en/latest/#building-for-windows) would work with cross-compilation.
