### ISSUE TITLE
Yubikey NEO in mode 6 (OTP+CCID+U2F) isn't detected by the authenticator

### ISSUE THREAD

**Issue by spectralblu** [Yubico/yubioath-desktop#14]
After enabling mode 6, the Yubico OATH applet does not detect the Neo. I keep getting this message:
![image](https://cloud.githubusercontent.com/assets/1915242/4726091/28be0a3e-595f-11e4-95b4-dfa76f2ec950.png)

The Neo Manager (gui) does detect the Neo though:
![image](https://cloud.githubusercontent.com/assets/1915242/4726135/784443b6-595f-11e4-8cf0-29192848946c.png)

Swapping the mode back to mode 2 (OTP + CCID) does let the OATH app detect the Neo correctly.

**Comment by agassner** [comment]
I've got the same issue on Mac OS X Yosemite 10.10.2
Authenticator doesn't work but NEO Manager works.
