### ISSUE TITLE
Yubico Authenticator v4.0.1 - Add ability to change font size

### ISSUE THREAD

**Issue by ilya40umov** [Yubico/yubioath-desktop#140]
On my 14' Thinkpad laptop I tend to increase font in most of the applications. After having updated Authenticator to v4.0.1 I find myself wishing I could double the size of the font in the app, which I sadly can not do. Can you guys add this little feature to the next version? (Or simply make the font somewhat bigger to work for everyone).
OS: Linux Mint 18.1 Cinnamon

Update: I was able to temporary workaround the issue by manually updating the yubioath.desktop with the following "Exec=env QT_DEVICE_PIXEL_RATIO=2 yubioath-desktop" but it does not affect the fond size in the menu (only fond size of the oath entries).

**Comment by dagheyman** [comment]
Do you do this individually for each app? I think the best alternative would be if it followed the font sizes configured on the system, which I think it does to some extent (although haven't tested this much). I don't know much about Linux Mint, but isn't there a way to increase the font size for all applications globally?

**Comment by ilya40umov** [comment]
Well. I have a system-wide "Text Scaling Factor" set to 1.4 but it gets completely ignored by the app(I don't want to tweak the individual font sizes because it's super tedious to change back and forth).

**Comment by dagheyman** [comment]
> I have a system-wide "Text Scaling Factor" set to 1.4 but it gets completely ignored by the app

Okay, so that might be a bug. I rather fix that than adding a setting for font size in the app. Will look into this and do some thinking/experimenting around what the best solution is, thanks for the report.

**Comment by dagheyman** [comment]
Is this still an issue in the latest version?

**Comment by ilya40umov** [comment]
> Is this still an issue in the latest version?
I'm on v4.1.3 and Cinnamon's font scaling still does not affect the font size in the application.

**Comment by dagheyman** [comment]
Ok thanks. So for me to be able to try to reproduce the issue, could you specify what scaling settings you have changed and how I can change them in Cinnamon?

**Comment by dagheyman** [comment]
This should be resolved with version 5.0.0, at least `QT_DEVICE_PIXEL_RATIO=2` seems to work. Tested on Ubuntu 19.04.
