### ISSUE TITLE
documentation request - build procedures

### ISSUE THREAD

**Issue by xortim** [Yubico/yubioath-desktop#143]
Can Yubico provide build instructions for the desktop authenticator for various platforms? I would like to start contributed where possible and would like to set up a development environment and local CI tool to potentially maintain my own patches.

Simply opening the project file on macOS w/in QtCreator is not all that is required.

**Comment by thorduri** [comment]
This should help you get started: https://github.com/Yubico/yubioath-desktop/blob/master/.travis.yml

**Comment by dagheyman** [comment]
Yes, some build instructions for contributors probably make sense. In the mean time the [travis file](https://github.com/Yubico/yubioath-desktop/blob/master/.travis.yml), the [Dockerfile](https://github.com/Yubico/yubioath-desktop/blob/master/docker/xenial/Dockerfile) and the [appveyor](appveyor.yml) file should give some clues.

**Comment by dagheyman** [comment]
Added some development docs (for Ubuntu) as well as a vagrant file intended to be used as a development environment. I might add instructions for Windows and macOS eventually, PRs and opinions welcome in the meantime.
