### ISSUE TITLE
Vim-style keyboard shortcuts (navigation with j/k)

### ISSUE THREAD

**Issue by ilya40umov** [Yubico/yubioath-desktop#145]
It would be really nice if you could add navigation with j/k keys as an alternative to Up/Down arrows.
(And maybe "y" as an alternative to Ctrl+C).

**Comment by dagheyman** [comment]
This request feels too niche to implement and maintain to be honest. I guess it could be opt-in, but I want to keep the number of settings to a minimum as well. May be re-considered if the demand is high.
