### ISSUE TITLE
ux improvement - double-click to generate-code, copy, minimise

### ISSUE THREAD

**Issue by bwalding** [Yubico/yubioath-desktop#146]
In the older 3.1.0 the interface was slightly quicker for day to day usage.

1. Double click entry
2. Touch token if required
3. Copies latest code to clipboard
4. Automatically minimise / close the app

The new 4.x workflow is

1. Right click on entry
2. Click "generate token"
3. Right click on entry
4. Click "copy"
5. Click to minimise app

I will have a look at patching if no one else is looking at this.

**Comment by dagheyman** [comment]
I think "double-click to generate/copy" makes sense and we have been discussing it internally as well. Not sure about the auto close/minimise part. It was a bit confusing in the previous version when the application could just disappear by clicking around.

**Comment by billputer** [comment]
I'd like to add that having the "Generate Code" menu item right next to the "Delete" menu item makes it really easy to almost accidentally delete a token. Adding a "double-click to generate/copy" would help avoid this, and I'd also suggest adding a separator between "Generate Code" and "Delete" in both the Edit and Right-Click context menu.
