### ISSUE TITLE
Clear button in search textbox

### ISSUE THREAD

**Issue by drohm** [Yubico/yubioath-desktop#147]
It would be convenient to have a circled 'x' button in the search textbox to instantly clear any text currently in the textbox.  Something like this:

![yubioath-search-clear-button](https://cloud.githubusercontent.com/assets/184959/24573705/de86407a-1654-11e7-8f83-26ae4fe36bbf.png)

**Comment by dagheyman** [comment]
Closing this since the search field can now be cleared using the <kbd>ESC</kbd> key.
