### ISSUE TITLE
Help...About needs close button

### ISSUE THREAD

**Issue by drohm** [Yubico/yubioath-desktop#148]
The Help...About dialog box doesn't have a close button.  I have to right-click on the title bar and select close to close the dialog.  I'm using 4.0.1 on Linux Mint 18.1 Cinnamon.

**Comment by dagheyman** [comment]
Do you have some custom settings on your system maybe? I can't reproduce this on a fresh Mint 18.1 Cinnamon. 

![screen shot 2017-04-07 at 10 52 26](https://cloud.githubusercontent.com/assets/9592259/24793001/8e49be8a-1b80-11e7-864e-c68e9a16c1a3.png)

**Comment by drohm** [comment]
This looks to be a theming issue, not a yubioath-desktop issue.  Thanks for finding that, I didn't think to check the theme.  I'm running the Arc theme.  When I changed the 'Windows borders' to 'Mint-Y', or any other available theme, I could then see 'x'.
