### ISSUE TITLE
suggested ux improvements

### ISSUE THREAD

**Issue by tycho** [Yubico/yubioath-desktop#149]
A few things i noticed playing with the current git version (4.0.1-16-ge0e59dd).

* The File>Exit menu item should either be "E&xit" or "&Quit" (i.e. the keyboard shortcut should be x or q, as with any other app, but not "&Exit" as it currently is).
* The "enter" key does nothing in the passphrase dialog when the checkbox has focus (i.e. enter passphrase, tab to checkbox, space to check it, pressing enter *should* click OK as it does when the text box has focus, but it does not)
* When the search text box has focus, I'd expect the Escape key to clear the current search terms (muscle memory from using search in web browsers like Chrome or Firefox)

**Comment by tycho** [comment]
Another one, a bit more trivial:
* I would suggest that the timer tick rate for updating the progress bar should probably be lower. You'd be surprised how much battery life is impacted in a laptop or tablet when something as simple as a blinking cursor is on screen (it prevents the Intel graphics chip from entering RC6p) -- or in this case, a very rapidly updating progress bar. You could probably update it every second or so and still show just as effectively how much time is remaining.

**Comment by dagheyman** [comment]
Thanks for the feedback, and I agree with all your first three points. 

Regarding the timer, yes it does check every [100 milliseconds](https://github.com/Yubico/yubioath-desktop/blob/master/qml/main.qml#L316) now, maybe it is  possible to check at a lower rate and still have a smooth progress bar (maybe some animations could help?).

**Comment by tycho** [comment]
@dagheyman I'm suggesting that even 100ms is too short a delay if you care about battery life. It keeps the GPU awake to redraw the progress bar. Also, I just noticed the timer doesn't stop ticking when minimized to the system tray, which means it's always consuming CPU even when backgrounded.

**Comment by drohm** [comment]
@dagheyman If you were to implement the change regarding the timer, would that affect desktops?  If so, maybe make it an option that can be enabled in Settings for laptops and such?

**Comment by dagheyman** [comment]
Closing since two of these are fixed and the third one (clear search box) has a separate issue.
