### ISSUE TITLE
Add a notification when OATH storage is full

### ISSUE THREAD

**Issue by thurask** [Yubico/yubioath-desktop#153]
I have a YubiKey NEO (FW 3.4.9) and I'm attempting to add another OTP credential to it with Yubico Authenticator (4.0.1, Windows 10 1703 x64). I scan the QR code with the reader, hit Add Credential and nothing happens; no message and the credential isn't added. Attempting to do the same with the Android app gives me a "YubiKey OATH storage is full!" message. I think the desktop app should have the same warning instead of silently backing out.

**Comment by dagheyman** [comment]
Agreed, should be added.

**Comment by tycho** [comment]
It would also be useful to have some visible metric showing the utilization of the OATH storage (e.g. in bytes perhaps) -- but I see that's not in the existing Yubikey OATH CCID protocol. :disappointed:
