### ISSUE TITLE
Problem with launching on others screen resolutions

### ISSUE THREAD

**Issue by Maksim31** [Yubico/yubioath-desktop#154]
When I close application Yubico Authenticator (version 4.0.1), this program save self coordinate on desktop. And, if I close, for example, on right side on desktop with high display resolution (like external display for notebook), then when I launch Yubico Authenticator on less resolution (on laptop without external display) I don't see application, because it's launched outside desktop. But I see what old version 2.3.0 always start on center of desktop. If it possible, can you change launching of Yubico Authenticator (version 4.0.1) as on old version?

**Comment by dagheyman** [comment]
Right now we are saving the position of the window in settings, to be able to re-launch the app at the same position. At least macOS seems to figure out when the window is trying to position itself outside a visible area. What OS and desktop environment/window manager are you running?

**Comment by Maksim31** [comment]
Dear Dag Heyman,

I use Windows 10.

Best regards,
Maksim Goikalov – Information Security Engineer
Mob. +971 (50) 899 2030 <tel:+971%20(55)%205549%20806>

[cid:image001.png@01D2A93C.7AADD430]

112-113 Building B, Dubai Logistic City
DWC, Dubai - UAE
P.O. Box 712012
Tel. +971 (4) 7017 260<tel:+971%20(4)%207017%20260>/1
Fax +971 (4) 7017 262<tel:+971%20(4)%207017%20262>
www.thekernel.com<http://www.thekernel.com/>
Location on Map<http://goo.gl/Kdsjlc>

**Comment by dagheyman** [comment]
This is now fixed and will be included in the next release. Thanks for the report!
