### ISSUE TITLE
Where to get yubioath-cli for macOS?

### ISSUE THREAD

**Issue by copumpkin** [Yubico/yubioath-desktop#155]
I'm poking around the installer package and can't find it. Is it not bundled with the graphical app? Could it be?

**Comment by dagheyman** [comment]
It is replaced by the CLI tool [YubiKey Manager](https://developers.yubico.com/yubikey-manager/). 
The oath commands can be listed with 
```$ ykman oath -h```

**Comment by copumpkin** [comment]
Oh, thanks!
