### ISSUE TITLE
password not needed when configured a password?

### ISSUE THREAD

**Issue by kun-zhou** [Yubico/yubioath-desktop#156]
I am using Yubikey 4 on my macOS 10.12.4 and on `yubioath-desktop-4.1.0` The issue is that when I set a password in the `File->Set password...`, a prompt shows up saying it is successful. But once I unplug the yubikey and close the application and reopen the app and plug in the key again, it does not prompt for any password but directly shows my OTP. I am not sure what part is wrong.. I have Yubikey configured as a smart card on my Mac, and uses it for U2F .

**Comment by dagheyman** [comment]
Are you sure you didn't check the `remember password` ? This would remember your password on that specific system. You could try setting a new password, it should prompt you for it when you remove and re-insert your YubiKey. There was an issue with the password always being cleared, but it was fixed in version 4.1.0.

You could also try to install [YubiKey Manager](https://developers.yubico.com/yubikey-manager/)  and see if the command `ykman oath code` prompts for a password.

**Comment by kun-zhou** [comment]
I do not see anywhere I can toggle “remember password”, actually, I was never prompted for password, not even once. I did try to reset my passwords at least 10 times, same issue. 

I followed your advice to do it through ykman oath, initially, it did not work. After I typed “ykman oath password” to set a password for my Yubikey, , the CLI does prompt for password and displays the code properly. However, the GUI prompts for password, but is stuck at reading credentials regardless of whether I entered the correct password or not.

**Comment by dagheyman** [comment]
Could you try starting yubioath-desktop from the command line and see if it logs any errors? So we can see if it is the samme issue as #138.

**Comment by kun-zhou** [comment]
Sure:

> qml: Could not read passwords. SyntaxError: JSON.parse: Parse error
> qml: Return value of PyObject call is NULL: Traceback (most recent call last):
> 
>   File "qrc:///py/yubikey.py", line 23, in wrapped
>     return json.dumps(f(*(json.loads(a) for a in args)))
> 
>   File "qrc:///py/yubikey.py", line 141, in derive_key
>     key = derive_key(controller.id, password)
> 
>   File "/Applications/Yubico Authenticator.app/Contents/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ykman/util.py", line 232, in derive_key
>     kdf = PBKDF2HMAC(hashes.SHA1(), 16, salt, 1000, default_backend())
> 
>   File "/Applications/Yubico Authenticator.app/Contents/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/cryptography/hazmat/backends/__init__.py", line 74, in default_backend
>     _default_backend = MultiBackend(_available_backends())
> 
>   File "/Applications/Yubico Authenticator.app/Contents/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/cryptography/hazmat/backends/__init__.py", line 31, in _available_backends
>     "cryptography.backends"
> 
>   File "/Applications/Yubico Authenticator.app/Contents/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/cryptography/hazmat/backends/__init__.py", line 30, in <listcomp>
>     for ep in pkg_resources.iter_entry_points(
> 
>   File "/Applications/Yubico Authenticator.app/Contents/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2235, in resolve
>     module = __import__(self.module_name, fromlist=['__name__'], level=0)
> 
>   File "/Applications/Yubico Authenticator.app/Contents/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/cryptography/hazmat/backends/openssl/__init__.py", line 7, in <module>
>     from cryptography.hazmat.backends.openssl.backend import backend
> 
>   File "/Applications/Yubico Authenticator.app/Contents/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 49, in <module>
>     from cryptography.hazmat.bindings.openssl import binding
> 
>   File "/Applications/Yubico Authenticator.app/Contents/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 141, in <module>
>     Binding.init_static_locks()
> 
>   File "/Applications/Yubico Authenticator.app/Contents/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 125, in init_static_locks
>     __import__("_ssl")
> 
> ImportError: dlopen(/Applications/Yubico Authenticator.app/Contents/Frameworks/Python.framework/Versions/3.5/lib/python3.5/lib-dynload/_ssl.cpython-35m-darwin.so, 2): Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
>   Referenced from: /Applications/Yubico Authenticator.app/Contents/Frameworks/Python.framework/Versions/3.5/lib/python3.5/lib-dynload/_ssl.cpython-35m-darwin.so
>   Reason: no suitable image found.  Did find:
> 	file system sandbox blocked open() of '/usr/local/opt/openssl/lib/libssl.1.0.0.dylib'
> 	file system sandbox blocked open() of '/usr/local/Cellar/openssl/1.0.2k/lib/libssl.1.0.0.dylib'
> 
> qml: Return value of PyObject call is NULL: Traceback (most recent call last):
> 
>   File "qrc:///py/yubikey.py", line 23, in wrapped
>     return json.dumps(f(*(json.loads(a) for a in args)))
> 
>   File "qrc:///py/yubikey.py", line 23, in <genexpr>
>     return json.dumps(f(*(json.loads(a) for a in args)))
> 
>   File "/Applications/Yubico Authenticator.app/Contents/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 312, in loads
>     s.__class__.__name__))
> 
> TypeError: the JSON object must be str, not 'NoneType'
> 
> qml: Return value of PyObject call is NULL: Traceback (most recent call last):
> 
>   File "qrc:///py/yubikey.py", line 23, in wrapped
>     return json.dumps(f(*(json.loads(a) for a in args)))
> 
>   File "qrc:///py/yubikey.py", line 23, in <genexpr>
>     return json.dumps(f(*(json.loads(a) for a in args)))
> 
>   File "/Applications/Yubico Authenticator.app/Contents/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 312, in loads
>     s.__class__.__name__))
> 
> TypeError: the JSON object must be str, not 'NoneType'
> 
> qml: qrc:///qml/YubiKey.qml:168: TypeError: Cannot read property 'length' of undefined
> qml: Return value of PyObject call is NULL: Traceback (most recent call last):
> 
>   File "qrc:///py/yubikey.py", line 23, in wrapped
>     return json.dumps(f(*(json.loads(a) for a in args)))
> 
>   File "qrc:///py/yubikey.py", line 23, in <genexpr>
>     return json.dumps(f(*(json.loads(a) for a in args)))
> 
>   File "/Applications/Yubico Authenticator.app/Contents/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 312, in loads
>     s.__class__.__name__))
> 
> TypeError: the JSON object must be str, not 'NoneType'
> 
> qml: qrc:///qml/YubiKey.qml:168: TypeError: Cannot read property 'length' of undefined
> qml: Return value of PyObject call is NULL: Traceback (most recent call last):
> 
>   File "qrc:///py/yubikey.py", line 23, in wrapped
>     return json.dumps(f(*(json.loads(a) for a in args)))
> 
>   File "qrc:///py/yubikey.py", line 23, in <genexpr>
>     return json.dumps(f(*(json.loads(a) for a in args)))
> 
>   File "/Applications/Yubico Authenticator.app/Contents/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 312, in loads
>     s.__class__.__name__))
> 
> TypeError: the JSON object must be str, not 'NoneType'
> 
> qml: qrc:///qml/YubiKey.qml:168: TypeError: Cannot read property 'length' of undefined
> qml: Return value of PyObject call is NULL: Traceback (most recent call last):
> 
>   File "qrc:///py/yubikey.py", line 23, in wrapped
>     return json.dumps(f(*(json.loads(a) for a in args)))
> 
>   File "qrc:///py/yubikey.py", line 23, in <genexpr>
>     return json.dumps(f(*(json.loads(a) for a in args)))
> 
>   File "/Applications/Yubico Authenticator.app/Contents/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 312, in loads
>     s.__class__.__name__))
> 
> TypeError: the JSON object must be str, not 'NoneType'
> 
> qml: qrc:///qml/YubiKey.qml:168: TypeError: Cannot read property 'length' of undefined
> qml: Return value of PyObject call is NULL: Traceback (most recent call last):
> 
>   File "qrc:///py/yubikey.py", line 23, in wrapped
>     return json.dumps(f(*(json.loads(a) for a in args)))
> 
>   File "qrc:///py/yubikey.py", line 23, in <genexpr>
>     return json.dumps(f(*(json.loads(a) for a in args)))
> 
>   File "/Applications/Yubico Authenticator.app/Contents/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 312, in loads
>     s.__class__.__name__))
> 
> TypeError: the JSON object must be str, not 'NoneType'
> 
> qml: qrc:///qml/YubiKey.qml:168: TypeError: Cannot read property 'length' of undefined
> qml: Return value of PyObject call is NULL: Traceback (most recent call last):
> 
>   File "qrc:///py/yubikey.py", line 23, in wrapped
>     return json.dumps(f(*(json.loads(a) for a in args)))
> 
>   File "qrc:///py/yubikey.py", line 23, in <genexpr>
>     return json.dumps(f(*(json.loads(a) for a in args)))
> 
>   File "/Applications/Yubico Authenticator.app/Contents/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 312, in loads
>     s.__class__.__name__))
> 
> TypeError: the JSON object must be str, not 'NoneType'
> 
> qml: qrc:///qml/YubiKey.qml:168: TypeError: Cannot read property 'length' of undefined
> qml: Return value of PyObject call is NULL: Traceback (most recent call last):
> 
>   File "qrc:///py/yubikey.py", line 23, in wrapped
>     return json.dumps(f(*(json.loads(a) for a in args)))
> 
>   File "qrc:///py/yubikey.py", line 23, in <genexpr>
>     return json.dumps(f(*(json.loads(a) for a in args)))
> 
>   File "/Applications/Yubico Authenticator.app/Contents/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 312, in loads
>     s.__class__.__name__))
> 
> TypeError: the JSON object must be str, not 'NoneType'
> 
> qml: qrc:///qml/YubiKey.qml:168: TypeError: Cannot read property 'length' of undefined
> qml: Return value of PyObject call is NULL: Traceback (most recent call last):
> 
>   File "qrc:///py/yubikey.py", line 23, in wrapped
>     return json.dumps(f(*(json.loads(a) for a in args)))
> 
>   File "qrc:///py/yubikey.py", line 23, in <genexpr>
>     return json.dumps(f(*(json.loads(a) for a in args)))
> 
>   File "/Applications/Yubico Authenticator.app/Contents/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 312, in loads
>     s.__class__.__name__))
> 
> TypeError: the JSON object must be str, not 'NoneType'
> 
> qml: qrc:///qml/YubiKey.qml:168: TypeError: Cannot read property 'length' of undefined
> qml: Return value of PyObject call is NULL: Traceback (most recent call last):
> 
>   File "qrc:///py/yubikey.py", line 23, in wrapped
>     return json.dumps(f(*(json.loads(a) for a in args)))
> 
>   File "qrc:///py/yubikey.py", line 23, in <genexpr>
>     return json.dumps(f(*(json.loads(a) for a in args)))
> 
>   File "/Applications/Yubico Authenticator.app/Contents/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 312, in loads
>     s.__class__.__name__))
> 
> TypeError: the JSON object must be str, not 'NoneType'
> 
> qml: qrc:///qml/YubiKey.qml:168: TypeError: Cannot read property 'length' of undefined
> qml: Return value of PyObject call is NULL: Traceback (most recent call last):
> 
>   File "qrc:///py/yubikey.py", line 23, in wrapped
>     return json.dumps(f(*(json.loads(a) for a in args)))
> 
>   File "qrc:///py/yubikey.py", line 23, in <genexpr>
>     return json.dumps(f(*(json.loads(a) for a in args)))
> 
>   File "/Applications/Yubico Authenticator.app/Contents/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 312, in loads
>     s.__class__.__name__))
> 
> TypeError: the JSON object must be str, not 'NoneType'
> 
> qml: qrc:///qml/YubiKey.qml:168: TypeError: Cannot read property 'length' of undefined
> qml: Return value of PyObject call is NULL: Traceback (most recent call last):
> 
>   File "qrc:///py/yubikey.py", line 23, in wrapped
>     return json.dumps(f(*(json.loads(a) for a in args)))
> 
>   File "qrc:///py/yubikey.py", line 23, in <genexpr>
>     return json.dumps(f(*(json.loads(a) for a in args)))
> 
>   File "/Applications/Yubico Authenticator.app/Contents/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 312, in loads
>     s.__class__.__name__))
> 
> TypeError: the JSON object must be str, not 'NoneType'
> 
> qml: qrc:///qml/YubiKey.qml:168: TypeError: Cannot read property 'length' of undefined
> qml: Return value of PyObject call is NULL: Traceback (most recent call last):
> 
>   File "qrc:///py/yubikey.py", line 23, in wrapped
>     return json.dumps(f(*(json.loads(a) for a in args)))
> 
>   File "qrc:///py/yubikey.py", line 23, in <genexpr>
>     return json.dumps(f(*(json.loads(a) for a in args)))
> 
>   File "/Applications/Yubico Authenticator.app/Contents/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 312, in loads
>     s.__class__.__name__))
> 
> TypeError: the JSON object must be str, not 'NoneType'
> 
> qml: qrc:///qml/YubiKey.qml:168: TypeError: Cannot read property 'length' of undefined
> qml: Return value of PyObject call is NULL: Traceback (most recent call last):
> 
>   File "qrc:///py/yubikey.py", line 23, in wrapped
>     return json.dumps(f(*(json.loads(a) for a in args)))
> 
>   File "qrc:///py/yubikey.py", line 23, in <genexpr>
>     return json.dumps(f(*(json.loads(a) for a in args)))
> 
>   File "/Applications/Yubico Authenticator.app/Contents/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 312, in loads
>     s.__class__.__name__))
> 
> TypeError: the JSON object must be str, not 'NoneType'
> 
> qml: qrc:///qml/YubiKey.qml:168: TypeError: Cannot read property 'length' of undefined
> qml: Return value of PyObject call is NULL: Traceback (most recent call last):
> 
>   File "qrc:///py/yubikey.py", line 23, in wrapped
>     return json.dumps(f(*(json.loads(a) for a in args)))
> 
>   File "qrc:///py/yubikey.py", line 23, in <genexpr>
>     return json.dumps(f(*(json.loads(a) for a in args)))
> 
>   File "/Applications/Yubico Authenticator.app/Contents/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 312, in loads
>     s.__class__.__name__))
> 
> TypeError: the JSON object must be str, not 'NoneType'
> 
> qml: qrc:///qml/YubiKey.qml:168: TypeError: Cannot read property 'length' of undefined
> qml: Return value of PyObject call is NULL: Traceback (most recent call last):
> 
>   File "qrc:///py/yubikey.py", line 23, in wrapped
>     return json.dumps(f(*(json.loads(a) for a in args)))
> 
>   File "qrc:///py/yubikey.py", line 23, in <genexpr>
>     return json.dumps(f(*(json.loads(a) for a in args)))
> 
>   File "/Applications/Yubico Authenticator.app/Contents/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 312, in loads
>     s.__class__.__name__))
> 
> TypeError: the JSON object must be str, not 'NoneType'
> 
> qml: qrc:///qml/YubiKey.qml:168: TypeError: Cannot read property 'length' of undefined
>

**Comment by dagheyman** [comment]
Thank you, it looks related indeed. Will look into it.

**Comment by kun-zhou** [comment]
Great, thanks!

**Comment by dagheyman** [comment]
Still investigating this, but could you try if doing `brew install openssl` makes any difference?

**Comment by kun-zhou** [comment]
Nope. Still stuck at the same place.

**Comment by dagheyman** [comment]
Thanks, is the error from console still the same?
Could you try this [development build](https://s3-eu-west-1.amazonaws.com/yubico-builds/yubioath-desktop/yubioath-desktop-4.1.1-dev.app.zip) and see if it behaves differently?

**Comment by kun-zhou** [comment]
Sorry for the delay. I just tested the dev build and it is working now! It now prompts for a password and no longer stuck at the reading credentials step. It is also able to set password without a problem now. Thanks!

**Comment by dagheyman** [comment]
@kun-zhou Thank you for all your testing! The issue was related to how the bundled Python run time was linked to OpenSSL, will be fixed in the next release.
