### ISSUE TITLE
broken 4.1.0 release

### ISSUE THREAD

**Issue by blshkv** [Yubico/yubioath-desktop#157]
There is a massive quality downgrade in the latest release.

The internal directory is named 'yubioath-desktop-yubioath-desktop-4.1.0' and there is no more standard setup.py file.

Please revert these back.

**Comment by dagheyman** [comment]
It's not a python package in itself anymore, that is why there is no `setup.py`. If you are looking for build instructions, see #143.

**Comment by blshkv** [comment]
I have started to convert to qt and cmake and still look messy.
I'll file a separate issue
