### ISSUE TITLE
Copy shortcut does not work when generate new code with required touch.

### ISSUE THREAD

**Issue by sleski** [Yubico/yubioath-desktop#158]
Yubico Authenticator v. 4.1.0 on Ubuntu 16.

How to reproduce:
-click on credential with required touch
-space -> touch your YubiKey
-ctrl-c -does not work, but right click works correct.

**Comment by dagheyman** [comment]
Thanks for the report, will look into it.

**Comment by sleski** [comment]
Btw, where can I find some information how build app from source, so maybe can try to fix it.

**Comment by dagheyman** [comment]
This is what's available right now: #143 
Will try to improve these docs in the future.

**Comment by bendem** [comment]
it seems like the item isn't actually selected (even though it visually is) after generating the code. <kbd>up</kbd>+<kbd>down</kbd> and you can copy again (easier than having to reach for your mouse in the meantime).
