### ISSUE TITLE
OpenGL Error

### ISSUE THREAD

**Issue by nabber00** [Yubico/yubioath-desktop#159]
Version 4.1.0 on Windows 10 in a Virtualbox guest VM.  This error occurs immediately upon application startup, then the application closes.  See included screenshot of error.

![image](https://cloud.githubusercontent.com/assets/13157950/25444496/5be5902e-2a79-11e7-9f9f-0d6c116ac633.png)

**Comment by dagheyman** [comment]
Thanks for the report. This seems to be solved by deploying [ANGLE](https://wiki.qt.io/Qt_5_on_Windows_ANGLE_and_OpenGL) with the windpeployqt tool. Will be fixed in the next release.
