### ISSUE TITLE
Hotkey support

### ISSUE THREAD

**Issue by tarcieri** [Yubico/yubioath-desktop#162]
I previously did Yubikey+OTP using this (now abandoned) tool:

https://github.com/zeteticllc/onetime

It supported hitting a hotkey sequence (I believe it used cmd-shift-Y on Mac), after which you could push the button on a Yubikey. It would then input the OTP code into wherever your cursor was focused.

I would really love it if Yubico Authenticator supported this as well, as the present workflow seems to be:

1. Right click Yubico Authenticator icon in menu bar to get context menu
2. "Show credentials"
3. Right click on credential window to get context menu
4. Click "Generate Code"
5. Push button on Yubikey
6. Receive code
7. Copy
8. Go back to where I actually wanted to enter the TOTP
9. Paste and hit enter

**Comment by dagheyman** [comment]
Thanks for the suggestion. I can see this being useful, but it also feels a bit niche to maintain (kind of like [Vim-style keyboard shortcuts](https://github.com/Yubico/yubioath-desktop/issues/145)).

Just some comments on the workflow (you might already know about them):
> 1. Right click Yubico Authenticator icon in menu bar to get context menu
> 2. "Show credentials"

Double-click or single click on the tray icon should probably be added as well, see #150

> 3. "Right click on credential window to get context menu
> 4. Click "Generate Code"

Selecting the credential with mouse or arrow keys are supported as well, and triggering the touch dialog with space.

> 5. Push button on Yubikey
> 6. Receive code
> 7. Copy

Cmd + C is supported for Copy when the credential is selected.

> 8. Go back to where I actually wanted to enter the TOTP
> 9. Paste and hit enter

**Comment by dagheyman** [comment]
Closing this. Workflow is improved a bit by with double-click and Enter having the ability to copy a credential to the clipboard. Double click on tray icon still to be addressed.
