### ISSUE TITLE
browser extension to auto fill based on hostname?

### ISSUE THREAD

**Issue by zypA13510** [Yubico/yubioath-desktop#164]
I think it should be possible (technically), to auto-fill authenticator digits into the browser, based on the hostname. We just need a Chrome/Firefox extension to do this. This should give users a similar experience to Yubikey mode (just insert the key, press the button, and success). Would you please consider adding this function in the future?

**Comment by dagheyman** [comment]
It's an idea that might be worth exploring (nothing planned right now though), but I'm closing this issue since it's not an issue with the current project.
