### ISSUE TITLE
feature request: autohide/autoshow when key removed/inserted

### ISSUE THREAD

**Issue by dagheyman** [Yubico/yubioath-desktop#165]
@zypA13510 in #150 :

> Hi, I have a suggestion here. Now that we can minimize to tray and keep running in the background, why don't we make it auto-hide when the key is unplugged, and auto pop out when the key is plugged in? For me, I think this will be very useful.

**Comment by alagopus** [comment]
Not quite the same but coming close:

#### `~/.config/systemd/user/yubikey.service`
```ini
[Unit]
Description=Start Yubikey OATH Tool
IgnoreOnIsolate=true

[Service]
Type=simple
Environment="DISPLAY=:0"
Environment="XAUTHORITY=/home/REPLACEME/.Xauthority"
ExecStart=/usr/bin/yubioath-desktop
```

#### `/etc/udev/rules.d/yubikey-systemd.rules`
```
ACTION=="add", SUBSYSTEM=="usb", ENV{ID_SECURITY_TOKEN}=="1", ENV{ID_VENDOR}=="Yubico", TAG+="systemd", ENV{SYSTEMD_USER_WANTS}+="yubikey.service"
```

**Replace `REPLACEME` with your username, above.**

This will open yubioath-desktop upon key insertion, even if it is not yet running. Minimize to tray is no longer needed.

**Comment by emlun** [comment]
We [recently][iss] disabled polling for the key while the app window is closed, which is incompatible with this request, so we won't do autoshow when inserted. Without that, autohide when unplugged probably isn't of much value. Sorry, we won't add this feature, but you can of course still do it through OS event hooks like the udev rule above. Thanks @alagopus for contributing!

[iss]: https://github.com/Yubico/yubioath-desktop/issues/189
