### ISSUE TITLE
value of selected credential not updated by timer, needs re-selection

### ISSUE THREAD

**Issue by dagheyman** [Yubico/yubioath-desktop#167]
from #144 :

> Issue: After selecting an OTP entry and copying to clipboard, Authenticator works as expected. However, if copying a second time—at least with Ctrl+C—the first OTP code is merely copied to clipboard again, instead of whatever new code has been generated since the first.

The timer or the copy event should update the value of the selected credential, so that a fresh OTP is copied.

**Comment by rmenessec** [comment]
Thanks! By the way, what's the best way to keep up to date on releases for this or the other Yubico support tools / packages?

**Comment by dagheyman** [comment]
> Thanks! By the way, what's the best way to keep up to date on releases for this or the other Yubico support tools / packages?

We do have some RSS feeds on developers.yubico.com.

This project
https://developers.yubico.com/yubioath-desktop/Releases/atom.xml

All projects
https://developers.yubico.com/Software_Projects/atom.xml

**Comment by rmenessec** [comment]
@dagheyman I think that second one is exactly what I was looking for, assuming it'll include any new tools / projects added. Thanks!

**Comment by rmenessec** [comment]
@dagheyman Can we expect to see a release with this fix soon?

Thanks!

**Comment by dagheyman** [comment]
@rmenessec Yes, will probably do a new release in August.
