### ISSUE TITLE
make uninstall tries to remove /usr/bin

### ISSUE THREAD

**Issue by phipolis** [Yubico/yubioath-desktop#168]
When using the build scripts, running `make uninstall` tries, and fails to remove /usr/bin--
```
$ sudo make uninstall
rm -f /usr/bin/yubioath-desktop
rmdir /usr/bin/ 
rmdir: failed to remove '/usr/bin/': Directory not empty
Makefile:639: recipe for target 'uninstall_target' failed
```

**Comment by dagheyman** [comment]
Thanks for the report, was able to reproduce it. Will look into why this is happening.

**Comment by dagheyman** [comment]
Ah, never mind, expected behaviour to get rid of empty folders.
