### ISSUE TITLE
Nothing happens when I add credentials (Mac OS X)

### ISSUE THREAD

**Issue by tomelkin** [Yubico/yubioath-desktop#171]
I'm trying to use my Yubikey Nano for my AWS MFA using Yubikey Authenticator. But when I scan the QR code (or paste in the secret manually) and click Add, the dialog closes but the window still says 'No credentials found'.

I'm trying to use Slot 2, as Slot 1 says it is in use.

I am running Mac OS X 10.12.5.

Thanks.

**Comment by dagheyman** [comment]
Does it help to remove and re-insert the key?
Also, could you check what version of the firmware you have?
You can do that with the [YubiKey Manager](https://developers.yubico.com/yubikey-manager/) tool (both CLI and GUI).

**Comment by tomelkin** [comment]
Hi,

Removing and re-inserting the key did not help.

Just install ykman.  Here are the details-

$  ykman info
Device name: YubiKey Standard
Serial number: 2806032
Firmware version: 2.4.3
Enabled connection(s): OTP

Device capabilities:
    OTP:	Enabled
    U2F:	Not available
    CCID:	Not available
    OPGP:	Not available
    PIV:	Not available
    OATH:	Not available

**Comment by dagheyman** [comment]
I just tested with a standard with 2.4.3, seemed to work on my side.

This is how my settings look:
![screen shot 2017-08-02 at 10 27 37](https://user-images.githubusercontent.com/9592259/28864581-4a72a700-776d-11e7-951f-f4668c77d07f.png)

Could you try starting Yubico Authenticator from the terminal and see if it outputs any errors?

**Comment by tomelkin** [comment]
Great call-
```
$  ./yubioath-desktop
qml: Return value of PyObject call is NULL: Traceback (most recent call last):

  File "qrc:///py/yubikey.py", line 23, in wrapped
    return json.dumps(f(*(json.loads(a) for a in args)))

  File "qrc:///py/yubikey.py", line 185, in add_slot_credential
    'YubiKey Slots cannot handle TOTP keys over 20 bytes.')
```

I was trying to register the QR code for my Amazon Web Services MFA.  Would you have expected this to work?

**Comment by dagheyman** [comment]
Unfortunately the slots can't store keys over 20 bytes. A newer model of the YubiKey (YubiKey 4 or NEO) can handle larger keys in the OATH functionality available over CCID. I'm leaving this issue open because that error should be presented in the GUI when trying to add a too large key.
