### ISSUE TITLE
Connecting to YubiKey...

### ISSUE THREAD

**Issue by credmp** [Yubico/yubioath-desktop#172]
I have a YubiKey 4 that I use for GnuPG and which has OATH tokens through my phone. I am, obviously, trying to use the desktop app as well, but it never goes past "Connecting to YubiKey...". Any ideas? I tried the stable version and t he git build (I am on Arch Linux)

Also, ykman fails to connect to the device. I suspect the issue is related. The personalize app is working nicely from what I see.

Environment:

Linux archman 4.12.3-1-macbook #1 SMP PREEMPT Fri Aug 4 15:39:53 CEST 2017 x86_64 GNU/Linux

YubiKey firmware 3.4.9 with slot 1 configured.

Installed yubikey packages:

community/yubico-c 1.13-3
community/yubico-c-client 2.15-2
local/yubico-yubioath-desktop-git 708-1
community/yubikey-manager 0.4.0-2
community/yubikey-personalization 1.18.0-1
community/yubikey-personalization-gui 3.1.24-3

**Comment by dagheyman** [comment]
I don't have an Arch Linux environment to test on right now, but could it be something related to the CCID drivers? There was a user on gentoo recently that had a similar problem because the pcsc daemon wasn't running.

**Comment by credmp** [comment]
Well that was exactly the problem. For future reference:

```
$ yaourt -S pcsclite pcsc-tools
$ sudo systemctl enable pcscd
$ sudo systemctl start pcscd
```

The yubioath-desktop app will now connect to the card. I had to make sure that CCID is set in the settings and you see all your credentials.

Thanks for the help @dagheyman !
