### ISSUE TITLE
windows 10 display rendering wrong

### ISSUE THREAD

**Issue by jeffkshaw** [Yubico/yubioath-desktop#173]
Windows 10 does not render the file menu properly, and the add credential window is shifted up by 20 pixels or so.
![alt and down arrow](https://user-images.githubusercontent.com/5245361/29383452-6be2a412-829e-11e7-937d-faea1df3cc86.png)
![regular](https://user-images.githubusercontent.com/5245361/29383453-6be4ee20-829e-11e7-9947-898797c2a693.PNG)
![add credential](https://user-images.githubusercontent.com/5245361/29383454-6be5d68c-829e-11e7-9be9-f88e3022fc23.PNG)

The behavior is the same with Windows 10 in dark or light mode.

![image](https://user-images.githubusercontent.com/5245361/29383513-aef38f78-829e-11e7-86fd-3a1bed01be07.png)

**Comment by dagheyman** [comment]
Thanks for the report, this do sound similar to this issue: https://github.com/Yubico/yubioath-desktop/issues/161 A fix for it will be included in the next release. To verify that it is the same, could you try this development build? 

https://yubico-builds.s3-eu-west-1.amazonaws.com/yubioath-desktop/yubioath-desktop-master--HEAD-win.zip 

Just unzip the archive and run the app from the folder, no installer needed.

**Comment by jeffkshaw** [comment]
works for the file menu.  my yubikey doesn't recognize over remote desktop
so can't see if it fixes the screen being shifted, but will report back
asap when i install the dev build on another machine.

**Comment by dagheyman** [comment]
Closing this, feel free to request it to be reopened if issue is still there.
