### ISSUE TITLE
Application icon not themeable in Linux

### ISSUE THREAD

**Issue by tomasz-oponowicz** [Yubico/yubioath-desktop#174]
Hi,

Is there any chance of not setting the window icon in Linux?

https://github.com/Yubico/yubioath-desktop/blob/f2d652ff9529df55fdbb922358483d55a5bad084/main.cpp#L64

...when the window icon is set, the icon comes from the executable file not the default icon theme. The net effect is:

![screenshot from 2017-08-21 18-07-09](https://user-images.githubusercontent.com/615940/29528378-28ddd5a4-869c-11e7-850c-98c7ebd9b8d0.png)

**Comment by dagheyman** [comment]
> Is there any chance of not setting the window icon in Linux?

I'm definitely open for it but I'm not sure what the consequences would be. Would it allow setting a custom icon, but using the provided one as a default? According to [this document](http://doc.qt.io/qt-5/appicon.html) the call to setWindowIcon only seems necessary for macOS.

**Comment by tomasz-oponowicz** [comment]
@dagheyman 

> Would it allow setting a custom icon, but using the provided one as a default?

Please take a look at _Icon Theme Specification_:
https://standards.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html#directory_layout

...if an icon isn't specified in the current icon theme, the `/usr/share/pixmaps` directory is checked. A window "inherits" a desktop icon in run time. 

You already have an appropriate icon in `/usr/share/pixmaps` directory:

https://github.com/Yubico/yubioath-desktop/blob/master/debian/yubioath-desktop.install#L2

I'm not sure about other platforms. 

I'm willing to test if needed.

**Comment by dagheyman** [comment]
I've changed (c2325d9) so that we only set the icon on the actual window and not on the app itself. I think this should resolve the issue, no? Testing appreciated, se https://github.com/Yubico/yubioath-desktop/blob/master/doc/development.adoc for building instructions.

**Comment by dagheyman** [comment]
Does this work for you in the latest version?

**Comment by tomasz-oponowicz** [comment]
Works. Tested against 4.2.0. Thx!
