### ISSUE TITLE
Application stops generating new codes

### ISSUE THREAD

**Issue by ferenczy** [Yubico/yubioath-desktop#176]
I used to use Authenticator that it's constantly running, minimized in the system tray. I have a problem that after some time it just stops generating new codes. The progress bar is just gray and it's not moving. Also, the displayed codes are grayed. Sometimes new codes are generated but it takes longer than 30 seconds and they're not valid (most likely wrong timing). The command line application (`ykman oath code`) generates completely different codes. It was happening also with previous versions. Current version is 4.1.4.

I have to restart the application. Last time I had to forcefully terminate it, because _Quit_ didn't do anything.

**Comment by dagheyman** [comment]
Thanks for the report. Do you know if this happens after machine has been set to sleep or hibernate mode? Or just after some time? This is on Windows 7, correct?

**Comment by ferenczy** [comment]
Yep, it's Windows 7 64-bit.

I'm not sure if it's happening also without sleep or hibernate. I'll try to keep an eye on it and let you know.

**Comment by emlun** [comment]
Do you have any estimate of how long it usually takes for this to happen?

**Comment by ferenczy** [comment]
So it's happening even without the sleep or hibernate. I just left my machine locked (with sleep disabled) in the evening and in the morning I found out that codes in Authenticator are grayed out, progress bar is also gray and Yubikey blinks frequently but irregularly (looks like a HDD LED).

I would say it takes a couple of hours to get into such state.

**Comment by dagheyman** [comment]
Do you still see this with version 4.3.3 ?

**Comment by dagheyman** [comment]
Closing because lack of info for now.
