### ISSUE TITLE
[windows] System tray icon is not removed when application exits

### ISSUE THREAD

**Issue by ferenczy** [Yubico/yubioath-desktop#177]
When I exit Authenticator (and process is really terminated), it doesn't remove the system tray icon and it doesn't disappear until I hover the cursor over it.

Version: 4.1.4

**Comment by dagheyman** [comment]
Does this happen every time? Is it on Windows 7?

**Comment by Nesos-ita** [comment]
yes, every time, on windows 7 (here)

**Comment by dagheyman** [comment]
Reproduced on Windows 10 as well.

**Comment by emlun** [comment]
Reproduced again in Win10, but this doesn't look to me like a bug in the yubioath-desktop app. Since the process exits immediately when you click Quit, and the icon then disappears as soon as you point at it again, I'm more inclined to call this a bug in Windows.

**Comment by ferenczy** [comment]
@emlun I really don't know how it's supposed to work in Windows but I can imagine that this behavior is happening when you don't explicitly remove the icon before exiting the app.

**Comment by emlun** [comment]
Ah yes, you are right. My thanks and apologies, this will be fixed in the next release.

**Comment by emlun** [comment]
Fixed in 77fbaab
