### ISSUE TITLE
No credentials found

### ISSUE THREAD

**Issue by ntrepid8** [Yubico/yubioath-desktop#178]
This morning my yubioath-desktop app stopped showing the 6 digit codes. I use it every day and this is the first time I've seen it do this.

![yubico authenticator_309](https://user-images.githubusercontent.com/482948/30074961-64049180-9241-11e7-8b4c-c9fa4d4bee56.png)

I've tried using different USB ports, but nothing seems to make a difference.  The command line tool `ykman oath code` still works and shows all the codes just fine.

Any ideas?

**Comment by dagheyman** [comment]
I think this is related to an issue with the update of the library `yubikey-manager`, that was released yesterday. Yubico Authenticator uses this library to communicate with the YubiKey. I've published a fixed version in the ppa. Could you try `$ sudo apt upgrade` ?

**Comment by ntrepid8** [comment]
That fixed it for me :)
