### ISSUE TITLE
GUI doesn't show full credential name

### ISSUE THREAD

**Issue by jsha** [Yubico/yubioath-desktop#180]
I have a number of credentials with similar names, prefixed by a distingusher and a colon. For instance, `DigitalOcean:jsha` and `GitLab:jsha`. I was using the `yubioath` v2.3.0 GUI until recently, and it displayed these credential names correctly. However, since upgrading to v4.1.4, the distinguishing text before the column is not displayed, so I have different credentials that display the same name (just `jsha`). This makes it hard to select the correct credential.

Expected behavior: Display the full credential name, including the text before the colon.

Thanks!

**Comment by YourLocalCultLeader** [comment]
I'm having the same problem with yubioath-desktop 4.1.4 on Ubuntu 16.04. Earlier versions from a couple of weeks ago worked fine. Command line tool ("ykman oath list") shows everything correctly. The Windows version of yubioath-desktop works fine aswell.

**Comment by YourLocalCultLeader** [comment]
**UPDATE:** I got it to work properly by compiling the sources from github, using the commands from _yubioath-desktop/docker/xenial/Dockerfile_ (changed the version in _yubioath-desktop/debian/changelog_ to _4.1.4~ppa1~xenial1_ first).

**Comment by dagheyman** [comment]
Thanks for the report, this is a known issue on Ubuntu for 4.1.4, will be addressed in the next version.

**Comment by obenn** [comment]
Hello, just chiming in to report the same issue. From yubio/stable, Ubuntu 16.04.

**Comment by dagheyman** [comment]
Should be fixed in version 4.2.0.
