### ISSUE TITLE
App forces discrete GPU on Mac OS

### ISSUE THREAD

**Issue by kimmoahokas** [Yubico/yubioath-desktop#183]
When opening Yubico authenticator my machine instantly changes to discrete GPU, which increases battery consumption. Tested with following configuration:
- MacBook Pro (15-inch, 2017)
    - has both Intel HD graphics and Radeon Pro 555
- Mac OS Sierra 10.12.6
- Yubico authenticator 4.1.4

Obviously this should not happen, as the application is not GPU-intensive in any way.

Thanks for taking a look at this :)

**Comment by dagheyman** [comment]
Thanks for the report. That's interesting, I didn't know about this issue. The fix [seems to be](https://developer.apple.com/library/content/qa/qa1734/_index.html) a simple flag in the Info.plist file. Will link a development build soon for you to verify.

**Comment by kimmoahokas** [comment]
Wow, you guys are incredibly fast to fix these. I built it myself and can verify that the flag works, it just took me more time to get the dependencies installed :D

Thanks a lot!

**Comment by dagheyman** [comment]
Perfect, thanks!
