### ISSUE TITLE
Windows version stuck at "Connecting to YubiKey..." (Yubikey NEO)

### ISSUE THREAD

**Issue by cdokolas** [Yubico/yubioath-desktop#184]
I installed the Windows version of the Authenticator (v4.1.4) and when I plug in my YubiKey NEO, it doesn't get past the "Connecting to YubiKey..." message.

Do I need to change something on the YubiKey NEO? CCID was enabled by default (fresh purchase).

I have Windows 10 64-bit.

**Comment by dagheyman** [comment]
Thanks for the report. No changes should be needed to a fresh NEO. Could you try starting the application from a command line and see if it outputs any errors ? Also note that there is a 4.2.0 version out, but it shouldn't affect the connectivity to the device.

**Comment by cdokolas** [comment]
I just tested the same version at my work PC and it worked fine (hurray!). I'm going to do what you asked on my personal computer ASAP. Thanks

**Comment by cdokolas** [comment]
Authenticator v4.2.0 works fine as well (and I noticed the fix on the timer bar; nice fix).

**Comment by cdokolas** [comment]
This is definitely related to a driver problem I'm having with my laptop. The smartcard device does not initialize properly in most cases.

If the smartcard device appears in the `Bluetooth & other devices`list, the authenticator works (although it shows a "No credentials found" message for a couple of seconds) . Otherwise it gets stuck.

**Comment by dagheyman** [comment]
Closing this issue since it doesn't seem related to the software. If you figure out what the problem was, feel free to post here as it might help others.
