### ISSUE TITLE
There's a difference between the windows and linux build which causes a linux bug/wrong behavior

### ISSUE THREAD

**Issue by elboletaire** [Yubico/yubioath-desktop#186]
I started using my Yubico Authenticator on windows, where I configured every key at the beginning. It was working very good, until I required to add more accounts of the same host.

Here's the issue: the windows version has a `domain` (or `host`) field which is not present in the linux version:

![imatge](https://user-images.githubusercontent.com/153305/30699696-b54be830-9ee5-11e7-81c8-fc0b7935ed8c.png)
> sorry, I cannot get the windows screenshot right now.. if you really need it I'll be able this afternoon. Basically in the windows version there's a third input named `host` or `domain`.

In my case I've multipple accounts for the same site, using different e-mails, and using the `host` field on windows caused all these credentials to be mixed on linux:

![imatge](https://user-images.githubusercontent.com/153305/30699595-6e01b7b6-9ee5-11e7-89a3-e574ca9d1197.png)

These two codes belong to two diferent sites, but the linux version recognises only the `name` field, and combines both, only giving me one of the two codes (I don't know which one):

![imatge](https://user-images.githubusercontent.com/153305/30699538-4dae4cfe-9ee5-11e7-8d4a-2b6ea31a7879.png)

The workaround in my case is to reopen the app from windows, remove all the credentials where I have the same name and different host, and recreate them again ignoring the `host` field. This could be an option, if only had two or three repeated accounts... but I've more than five 😖 

Obviously I'm using the exact same versions for both linux and windows (4.1.4).

**Comment by dagheyman** [comment]
Thanks for the report. This looks like a duplicate of #180 which only affects 4.1.4 on Ubuntu. Could you try with version 4.2.0 ? `$ sudo apt upgrade` should do it if you are on Ubuntu.

**Comment by elboletaire** [comment]
Oops, yes, apparently is the same issue.

And yes, I've checked the new version and it's fixed now! Thanks and sorry for the duplication 😅
