### ISSUE TITLE
Simplify keyboard usage

### ISSUE THREAD

**Issue by minisu** [Yubico/yubioath-desktop#187]
I love Yubico Authenticator and use it every day. Here's a suggestion for how I think it could be even better:

---

My list of credentials includes the following two:

- Google: my.name@mycompany.com
- my.name@mycompany.com

Currently, in order to paste the value of the second credential I have to:

1. Open/maximize Yubico Authenticator.
1. Press _Tab_ to put focus on the _Search_ text field.
1. Type something, e.g. `mycom`. This filters the list to only the above mentioned credentials.
1. Press _Tab_ to put focus on the list of credentials.
1. Press _Down Arrow_ to select the second credential.
1. Press _Enter_.
1. Minimize Yubico Authenticator.

I propose a few small changes in Yubico Authenticator behavior:

- Search field being focused by default.
- Up/down arrows changing list entries even when the search field is focused.
- Enter key not only copying the OTP to the clipboard, but also minimizing Yubico Authenticator. Ideally combined with a message _"OTP copied to clipboard"_ (I'm thinking something like [Toasts](https://developer.android.com/guide/topics/ui/notifiers/toasts.html) in Android).

With these changes, the above flow would be reduced to:

1. Open/maximize Yubico Authenticator.
1. Type something, e.g. `mycom`. This filters the list to only the above mentioned credentials.
1. Press _Down Arrow_ to select the second credential.
1. Press _Enter_.

This would also harmonize the behavior of Yubico Authenticator with most filterable lists, e.g. the address field in web browsers, search engine suggestions and the start menu in operating systems.

**Comment by emlun** [comment]
Suggestions 1 and 2 are now implemented in master. I'm not sure 3 (minimize on Enter) is something we want to do, I'll need to confer with @dagheyman when he returns from his vacation. Moving that suggestion to #214.

**Comment by emlun** [comment]
By the way: If you want to squeeze keystrokes down to the absolute minimum, and you're on Linux/Unix, you could also try [yubikey-oath-dmenu][yod]. Note however that this is not officially supported by Yubico.

[yod]: https://github.com/emlun/yubikey-oath-dmenu

**Comment by minisu** [comment]
Cool @emlun :ice_cream:
