### ISSUE TITLE
HIgh idle CPU usage

### ISSUE THREAD

**Issue by MarkRose** [Yubico/yubioath-desktop#189]
Even when I don't have a Yubikey inserted, the yubioath python script consumes a lot of CPU (>1%). This is especially concerning on laptops.

**Comment by dagheyman** [comment]
Thanks for the report. What OS and version of Authenticator are you doing measurements with?

**Comment by MarkRose** [comment]
My apologies for the lack of details; I should know better than that.

I'm running Ubuntu 16.04.3 LTS, with yubioath-desktop 4.2.0 installed from the PPA. `top` shows CPU usage hovering around 1%. I would expect it to use much less than that when a Yubikey is not inserted.

**Comment by artburkart** [comment]
I'm seeing the same with the same env and version of yubioath-desktop. It's hovering between 0.7 and 1.3%.

**Comment by emlun** [comment]
Seems to be caused by the GUI refresh timers, looks easy enough to pause those while the window is closed or no device is plugged in. With that, CPU usage drops to zero while closed and hovers around 0.7-1.3% while open with no device plugged in (because of the device polling timer). :)

**Comment by MarkRose** [comment]
Tack så mycket!

**Comment by MBerantzino** [comment]
Not sure if the cause is the same, but I see CPU usage between 1 and 2% when minimized to system tray on Windows 10, 1909 with Yubico Authenticator 5.0.4.
