### ISSUE TITLE
yubioath-desktop fails to detect Yubikey NEO

### ISSUE THREAD

**Issue by jamesfi** [Yubico/yubioath-desktop#19]
I'm having a consistent problem that appears to be a bug in yubioath-desktop-0.1.1.exe on Windows 8.1 x64.

If the exe is launched before the NEO is inserted then everything works perfectly.  If the exe is already running when the NEO is inserted it fails to detect the NEO (even if it was previously launched whilst the NEO was connected).  Reproducible every time in my environment.

**Comment by minisu** [comment]
Same for me.

**Comment by raabf** [comment]
:+1:

**Comment by arcaartem** [comment]
+1

**Comment by XxaxGist** [comment]
+1

**Comment by smiddy** [comment]
Same for me on a ubuntu 14.04 64 bit.

**Comment by dainnilsson** [comment]
Please try the new version (2.0.1) and re-open if you're still having issues with that. Linux and OS X users should first read this before opening a new issue: https://github.com/Yubico/yubioath-desktop#detecting-the-device
