### ISSUE TITLE
Version 4.2.0: TypeError: Cannot call method 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by joebonrichie** [Yubico/yubioath-desktop#190]
Since upgrading to v4.2.0 I am getting the following error when I run yubioath, as a result I am unable to see any of my saved credentials. Downgrading to v4.1.4 fixes the issue. I am running Solus Linux

`qrc:///qml/main.qml:520: TypeError: Cannot call method 'toLowerCase' of undefined`

I believe the regression was introduced via commit [67f9211](https://github.com/Yubico/yubioath-desktop/commit/67f9211c776115a23c4cef8f9ae5e3a45f2d5624#diff-89054baf516aa304c8546c9194eaa4f2)

This seems to be an easy fix, but ofc willing to help in any way, cheers.

**Comment by emlun** [comment]
Thank you for the report! Indeed it looks like it should be an easy fix. Do you know off the top of your head a way to reliably reproduce the error?

**Comment by joebonrichie** [comment]
Upgrading to yubikey-manager v0.4.5 fixed this for me. Sorry, that really should have been the first thing I did!

Anyway, this can be reliably produced when running yubikey-manager <0.4.5, the error occurs in console everytime the oath codes are regenerated. I suppose in the future you could enforce a minimum version of yubikey-manager, which should help with errors like these.

**Comment by emlun** [comment]
Thanks again! Yeah, a versioned dependency might be good. I've opened #191 to track that.
