### ISSUE TITLE
Upgrade PyPI Version Request

### ISSUE THREAD

**Issue by jyundt** [Yubico/yubioath-desktop#193]
Would it be possible to bump the [pypi yubioath-desktop package](https://pypi.python.org/pypi/yubioath-desktop) to 4.2.0? The current version on pypi is 3.1.0.

**Comment by dainnilsson** [comment]
Unfortunately not. The 4.x version is no longer a python package. Instead it's a compiled Qt application which calls Python code, using QML for the UI rather than the Qt-bindings for Python.
