### ISSUE TITLE
Stopped working on macOS Sierra

### ISSUE THREAD

**Issue by Strayer** [Yubico/yubioath-desktop#198]
I have very weird issues on macOS Sierra 10.12.6…

After starting the application I first see "No YubiKey detected.", after a few seconds this changes to "Connecting to YubiKey...", which will take several (20+) seconds until it changes to "No credentials found."
When I quit the application the window turns white for a second, disappears but the application keeps running in a zombie state.

<img width="209" alt="grafik" src="https://user-images.githubusercontent.com/310624/31946295-c332d26e-b8d1-11e7-8696-c31707b17859.png">

It was working before I rebootet the Mac, not sure what the heck is going on. I initially installed the application via homebrew cask, but the same happens when using the installer from the releases tab (may actually be the same, didn't check).

I can generate codes fine with ykman and the Android app, so this doesn't seem to be an issue with the YubiKey itself.

Its a brand new YubiKey 4C – `ykman info` reports:

```
Device name: YubiKey 4
Serial number: <redacted>
Firmware version: 4.3.5
Enabled connection(s): OTP+U2F+CCID

Device capabilities:
    OTP:        Enabled
    U2F:        Enabled
    CCID:       Enabled
    OPGP:       Enabled
    PIV:        Enabled
    OATH:       Enabled
```

**Comment by emlun** [comment]
Thank you for the report. What version of Yubico Authenticator is this?

**Comment by Strayer** [comment]
Whoops, sorry, forgot that. It is Yubico Authenticator 4.2.0.

**Comment by emlun** [comment]
Ok. Just to get some basics out of the way first: You say it used to work and doesn't anymore - have you tried reinstalling it? Did you upgrade Mac OS or something since last time it worked?

**Comment by Strayer** [comment]
Yes, as stated in the issue I first installed via Homebrew that installs from this URL:
https://developers.yubico.com/yubioath-desktop/Releases/yubioath-desktop-4.2.0-mac.pkg

This first worked fine, then I had to reboot for unrelated reasons. After the reboot, I faced the issues mentioned above. I then removed the application with AppCleaner to hopefully clean out all locations and reinstalled via the GitHub release, but still had the same issues. No OS upgrades in-between.

I'm not entirely sure if there isn't actually an issue with the YubiKey itself… running `ykman oath list` takes about 5 to 7 seconds with two entries, running `ykman oath code …` takes about 6 seconds. Since this is the first "full" YubiKey I own I don't know if these times are normal.

**Comment by emlun** [comment]
It doesn't sound right that those ykman commands take that long to run. Have you tried the YubiKey on another computer?

**Comment by Strayer** [comment]
Okay, so… apparently another reboot has fixed the issue. Both ykman and the desktop application are fast now. I'll reopen the issue if I encounter this again.

Very strange! Sorry for the confusion :(

**Comment by emlun** [comment]
That's very strange indeed, but I'm glad you got it to work in the end!
