### ISSUE TITLE
Only can add 7 credentials

### ISSUE THREAD

**Issue by interbiznw** [Yubico/yubioath-desktop#200]
Anyone know why it wont let me add more than 7 credentials? Having issue on windows app and android, it says added but does not show anymore than 7

**Comment by emlun** [comment]
I'm not able to reproduce this problem in either of the apps. Which versions of the apps and what YubiKey model are you using?

**Comment by emlun** [comment]
Closing this for now, you're welcome to reopen it if you have any more information to add.
