### ISSUE TITLE
Program hang if i don't touch the yubikey button in about 20 seconds after the request

### ISSUE THREAD

**Issue by Nesos-ita** [Yubico/yubioath-desktop#202]
**expected behaviour**
After double-clicking on a crredential the program should wait for a yubikey tap until you actually tap or inform you that you haven't touched the button in time.

**actual behaviour**
If you double click on a credential, yubico authenticator asks "touch your yubikey to generate the code".
yubikey start flashing, but if you don't tap the button in about 20 seconds the yubikey stop blinking and start its normal behaviour (yubico otp slot 1)
the problem is that i can't close the "now tap" window (since X is grayed out) nor i can't close the main app and i must terminate the process.

I was explaining dad how to use the yubikey, but he is not very fast.
is the second time that my dad use it and is the second time that he managed to hang the app.

possible solutions:
- set the yubikey to wait indefinitely for a button press (i think is better to avoid this).
- close the "now tap" window after 20 seconds (and maybe inform the user that he didn't tap in time)

not possible solutions:
- disable the "tap required" as it is a major security feature (allows me to prevent virus from requesting codes)
- fix my dad :) i'll try harder but fixing the user is not going to work.

OS: Windows 7 / 8.1 64 bit
yubico authenticator version: 4.2.0

**Comment by emlun** [comment]
Confirmed, thanks for reporting! This is fixed but not yet released, it will be included in the next release.
