### ISSUE TITLE
Multiple yubikey support

### ISSUE THREAD

**Issue by jonasfj** [Yubico/yubioath-desktop#204]
I have multiple yubikeys because I have different security levels.
I have a nano that is always in my laptop, and some tokens are exclusively on my keyring.

Why not have proper support for multiple keys. I played with the python API in a previous version... it's certainly possible to list the keys and display them all..

**Comment by emlun** [comment]
As said in the [YubiKey Manager issue][ykman], this is unfortunately more complicated than it may seem. That said, this application is not as complex as YubiKey Manager, and we could probably get it to work in this specific context. We'll look into it.

[ykman]: https://github.com/Yubico/yubikey-manager/issues/32

**Comment by ntrepid8** [comment]
I'd like to be able to use more than one key at the same time also. It would be especially handy for cases where one of the keys is a nano and a bit hard to remove. I've got at least 3 keys I use on a regular basis :)

**Comment by emlun** [comment]
I agree this is something we would like to do, and it now looks like we probably can. There are some higher priority things we need to get out of the way first, though.

**Comment by aureq** [comment]
Just bumping this issue up. My employer (AWS) have their employees use Yubikeys. Many security conscious people also have their own Yubikeys. It would be great to see such feature implemented. Even something as simple as a drop down selector.

Thank you

**Comment by dagheyman** [comment]
This is implemented in version 5.0.0. You may select what key to use under "Settings".
