### ISSUE TITLE
[regression] provide a CLI interface

### ISSUE THREAD

**Issue by jonasfj** [Yubico/yubioath-desktop#205]
I obviously want to integrate the TOPT tokens with my scripts, example:
https://gist.github.com/jonasfj/8b4848574f70474b941e0428087ac97b
I type `signin-aws` in my shell, touch my yubikey and then I have temporary env vars with EC2 privileges in my shell.

This also mitigates the cases where the buggy UI and I have to write my own, which would be fairly simple to do using dmenu.

Just make a simple cli tool that support dumping the output as json... given an optional parameter `--json`.
That way it would be easy to write scripts on top of it. The old `yubioath-cli` tool didn't support JSON output, and it was extremely hard to reliably parse the names out... It also doesn't support listing multiple keys which should be trivial to add.

**Comment by jonasfj** [comment]
A stable high-level python API would also work. But please enable us to script TOTP retrieval.

**Comment by dainnilsson** [comment]
The yubioath-cli tool has been deprecated in favor of the ykman CLI in https://github.com/Yubico/yubikey-manager, which also aims to provide a stable Python API. There are some backwards-breaking changes in the current master which haven't yet been released, but once they are the API for OATH should be fairly stable. The ykman CLI is intended to support scripting, so if you run into issues there please open an issue for that project.

**Comment by jonasfj** [comment]
Awesome, thanks...
