### ISSUE TITLE
4.2.0 unbundle packages in "vendor" directory or make an option to use system

### ISSUE THREAD

**Issue by blshkv** [Yubico/yubioath-desktop#206]
```
bash$ make
x86_64-pc-linux-gnu-g++ -c -march=native -O2 -pipe -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DAPP_VERSION=\"4.2.0\" -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtQuick -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtQml -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtCore -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o main.o main.cpp
main.cpp:9:31: fatal error: QtSingleApplication: No such file or directory
compilation terminated.
make: *** [Makefile:713: main.o] Error 1
```
But I do have it installed:
```
equery f qtsingleapplication | grep .h
/usr/include/qt4/QtSolutions/qtsingleapplication.h
/usr/include/qt4/QtSolutions/qtsinglecoreapplication.h
/usr/include/qt5/QtSolutions/qtsingleapplication.h
/usr/include/qt5/QtSolutions/qtsinglecoreapplication.h
```

any ideas?

**Comment by blshkv** [comment]
ok, so the entire "vendor" folder is empty in the release tar ball. 

Can I specify a system location instead?

**Comment by emlun** [comment]
Have you tried cloning the repository instead of using the release tarball? That would give you the `vendor/*` subdirectories as Git submodules which you can fetch with either `git submodule update --init --recursive` or `git clone git@github.com:Yubico/yubioath-desktop.git --recurse-submodules`.

**Comment by blshkv** [comment]
I'm sure it will work. But I'm porting it to Gentoo Linux and it has the release tarball with external libraries.

**Comment by emlun** [comment]
That sounds like Gentoo may have repackaged it to also contain the external libraries, as our releases currently don't. We probably want to get that fixed, though, thanks for raising the issue!

**Comment by blshkv** [comment]
Found a similar request here:
https://github.com/QupZilla/qupzilla/issues/1503

**Comment by emlun** [comment]
Source release [4.2.0b][rel] is now up, which includes the contents of the submodules bundled in the archive. Thank you for reporting!

[rel]: https://github.com/Yubico/yubioath-desktop/releases/tag/yubioath-desktop-4.2.0

**Comment by blshkv** [comment]
You made it worse. Software should not come with bundled dependency. Oh well, I'll have unbundle each release now..

**Comment by blshkv** [comment]
So it looks like you removed it eventually. v 4.3.4 does not include the vendor directory at all.
It didn't take long to understand the issue, just 9 month.
