### ISSUE TITLE
On macOS cmd-c does not copy

### ISSUE THREAD

**Issue by chmac** [Yubico/yubioath-desktop#209]
Steps to reproduce
* Open yubico authenticator
* <kbd>cmd</kbd>+<kbd>f</kbd>
* type something to filter your list
* <kbd>cmd</kbd>+<kbd>c</kbd>

Expected result, the credential should be copied to the system clipboard.

Actual result, no change to the clipboard contents.

Pressing the <kbd>enter</kbd> key does copy the credential. But the menu item in macOS is called "Copy to clipboard" and labeled with the shortcut <kbd>cmd</kbd>+<kbd>C</kbd>. Pressing the keyboard shortcut also flashes the menu confirming that the action was taken, but in fact nothing happened.

**Comment by emlun** [comment]
This is because the search text box has focus, not the credential list. The flashing menu confirms copying the (probably empty) selection in the search field.

If you press <kbd>Tab</kbd> between searching and copying you get the desired behaviour.

**Comment by chmac** [comment]
@emlun Fair enough. It's definitely not what I would "expect". My experience with password managers for example (LastPass desktop & KeepassX) is that <kbd>cmd</kbd>+<kbd>c</kbd> will copy the target value. It's probably unlikely that I want to copy out of the search input field...

**Comment by emlun** [comment]
Sorry, I understand it can be confusing. We'll look into adding some kind of confirmation that the code has been copied (see #133), hopefully that will help.
