### ISSUE TITLE
Request: build documentation

### ISSUE THREAD

**Issue by divoxx** [Yubico/yubioath-desktop#211]
It would be great to be able to easily build/compile the app since you only provide packages for ubuntu and there are many of us non-ubuntu users out there.

**Comment by emlun** [comment]
Good point, thanks. There are some instructions in [doc/development.adoc][doc], but it could indeed be made more accessible and less targeted toward development.

In the meantime: As far as building goes, you should only need to install the dependencies and then run `qmake && make` in the project root. You can refer to the Vagrant [provisioning script][prov] to get an idea of what you need installed to build it. For packaging it's not quite as clear, but these are the files included in the Arch Linux AUR package:

```
usr/
usr/bin/
usr/share/
usr/share/applications/
usr/share/pixmaps/
usr/share/pixmaps/yubioath.png
usr/share/applications/yubioath-desktop.desktop
usr/bin/yubioath-desktop
```

and the Arch package dependencies are `pcsclite`, `ccid`, `python-pyotherside`, `yubikey-manager`, `qt5-quickcontrols`. Compare with the Debian package dependencies listed in [debian/control][deb].

Hope that helps while we sort this out!

[deb]: https://github.com/Yubico/yubioath-desktop/blob/master/debian/control
[doc]: https://github.com/Yubico/yubioath-desktop/blob/master/doc/development.adoc
[prov]: https://github.com/Yubico/yubioath-desktop/blob/master/vagrant/development/provision.sh

**Comment by emlun** [comment]
Build instructions are now available at [doc/Building_from_Source](https://github.com/Yubico/yubioath-desktop/blob/master/doc/Building_from_Source.adoc), and also linked from the root README. Please let us know if anything is missing or unclear. I'll close this issue for now, but please reopen it if you have any more questions or suggestions.
