### ISSUE TITLE
Yubico on MacOS errors when adding credentials

### ISSUE THREAD

**Issue by joshma** [Yubico/yubioath-desktop#212]
I'm trying to use Yubico Authenticator with a Yubikey 4 with AWS. Started from CLI to show errors:

```
qml: Return value of PyObject call is NULL: Traceback (most recent call last):

  File "qrc:///py/yubikey.py", line 24, in wrapped
    return json.dumps(f(*(json.loads(a) for a in args)))

  File "qrc:///py/yubikey.py", line 73, in refresh_credentials
    c.to_dict() for c in self._calculate_all(timestamp, password_key)]

  File "qrc:///py/yubikey.py", line 222, in _calculate_all
    controller = OathController(dev.driver)

AttributeError: 'NoneType' object has no attribute 'driver'

qml: qrc:///qml/YubiKey.qml:168: TypeError: Cannot read property 'length' of undefined
```

I just downloaded the application today, so I don't think it's a version problem. Any chance there's a regression here?

**Comment by emlun** [comment]
Indeed looks a lot like a bug. We'll take a look at it. What exactly did you do to trigger this?

**Comment by joshma** [comment]
Thanks! I didn't do much:
- Install Yubico Authenticator
- Launch the app (No YubiKey detected)
- Plug in Yubikey (No credentials)
- Scan QR Code - save without modifications
- Nothing shows up :(

**Comment by emlun** [comment]
Which versions of Mac OS and Yubico Authenticator are you using?

**Comment by joshma** [comment]
Was on Sierra, now High Sierra: 10.13.1. Yubico Authenticator 4.2.0.

**Comment by emlun** [comment]
Ok. I managed to reproduce the issue with 4.2.0 but not with the development build for 4.3.0, so I'll close this for now. Please reopen it if you still have this problem with 4.3.0, which we plan to release tomorrow.

**Comment by emlun** [comment]
My bad, we're not actually releasing today. Hopefully the release will happen on Friday or so.

**Comment by joshma** [comment]
Thanks! Will try again next week.
