### ISSUE TITLE
yubioath-desktop does not show codes after update

### ISSUE THREAD

**Issue by ntrepid8** [Yubico/yubioath-desktop#217]
- Yubico Authenticator version:  4.2.0
- Operating system and version: Ubuntu 16.04
- YubiKey model and version: YubiKey NEO [OTP+U2F+CCID]
- Bug description summary: after updating today, the desktop app no longer shows any codes, but the command line application `ykman oath code` still works fine.

Steps to reproduce
---

Update to version 4.2.0 on Ubuntu 16.04

Expected result
---

Expected it to still generate codes.

Actual results
---

Got a blank grey box with the message "No YubiKey detected" instead of a list of codes. Menus still worked.

Other info
---

This has happened once before after an update, and it seems like it was a relatively easy fix: #178

**Comment by emlun** [comment]
Thanks for the report! Just to double check, do you actually mean 4.2.0 and not 4.3.0? I'm asking because we released 4.3.0 just a few hours before you opened this issue.

I think this might again be an issue with the `yubikey-manager` dependency. Which version of `yubikey-manager` do you have installed (package version or `ykman --version` output)?

**Comment by dainnilsson** [comment]
Weird, I just tried to add the PPA and see what the current version is, and it's showing `4.2.0~ppa1~artful1`, even though the latest one listed is 4.3.0 here: (https://launchpad.net/~yubico/+archive/ubuntu/stable/+index?batch=75&direction=backwards&start=150). Not sure why the later version isn't showing up...

**Comment by dainnilsson** [comment]
@emlun It looks like the problem is the dependency version here: https://github.com/Yubico/yubioath-desktop/blob/master/debian/control#L22. yubikey-manager-qt likely has the same issue.

Unfortunately I'm not in a position to fix this myself right now.

**Comment by emlun** [comment]
Yeah, it's probably caused by 4.2.0 not specifying a maximum yubikey-manager version.

**Comment by emlun** [comment]
@dainnilsson Ah, thanks for pointing out the build failure. I fixed the issue and got 4.3.0 published, only to discover a fatal bug in it which is now also fixed and published as 4.3.1.

@ntrepid8 Thanks again for reporting! Please try upgrading to 4.3.1 and let us know if you have any further problems.

**Comment by ntrepid8** [comment]
Yup, the update to version `4.3.1` fixed the issue for me. Thanks for the quick fix!
