### ISSUE TITLE
Yubikey 4 is not detected on Linux Mint 18.2 Sonya

### ISSUE THREAD

**Issue by rettlsteiner** [Yubico/yubioath-desktop#218]
Yubikey Authenticator (v4.2.0) is not detecting my Yubikey 4. I'm using Linux Mint 18.2 Sonya.

This is my console output:
NameError: name 'yubikey' is not defined
)
qml: qrc:///qml/YubiKey.qml:70: Error: Cannot assign [undefined] to int
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"<string>\", line 1, in <module>\n\nNameError: name 'yubikey' is not defined\n"
qml: Function not found: 'yubikey.controller.count_devices' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: qrc:///qml/YubiKey.qml:70: Error: Cannot assign [undefined] to int

**Comment by emlun** [comment]
Thank you for reporting! This looks like an issue with the version of the `yubikey-manager` dependency (namely that we hadn't specified a maximum dependency version in 4.2.0). This should be fixed in 4.3.1, please try upgrading to that and let us know if you have any further problems.
