### ISSUE TITLE
Help...About not showing correct version

### ISSUE THREAD

**Issue by drohm** [Yubico/yubioath-desktop#219]
Thank you for opening an issue! If this is a bug report, please include the
following information:

- Yubico Authenticator version: 4.3.1-1
- Operating system and version: Ubuntu Budgie 17.10
- YubiKey model and version: YubiKey NEO (firmware 3.4.9)
- Bug description summary: yubioath-desktop in Help...About shows version 1.0.0 when it should be 4.3.1?  The 4.3.0 version correctly showed 4.3.0, but this new version shows 1.0.0.

apt output when upgrading:
```
The following packages will be upgraded:
  yubioath-desktop
1 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
Need to get 53.8 kB of archives.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://ppa.launchpad.net/yubico/stable/ubuntu artful/main amd64 yubioath-desktop amd64 4.3.1-1~ppa1~artful1 [53.8 kB]
Fetched 53.8 kB in 0s (164 kB/s)          
(Reading database ... 482592 files and directories currently installed.)
Preparing to unpack .../yubioath-desktop_4.3.1-1~ppa1~artful1_amd64.deb ...
Unpacking yubioath-desktop (4.3.1-1~ppa1~artful1) over (4.3.0-3~ppa1~artful1) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Processing triggers for desktop-file-utils (0.23-1ubuntu3) ...
Processing triggers for bamfdaemon (0.5.3+17.10.20170810-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Setting up yubioath-desktop (4.3.1-1~ppa1~artful1) ...
Processing triggers for gnome-menus (3.13.3-6ubuntu5) ...
```

Obviously not a showstopper, just wanted to relay the information.

**Comment by drohm** [comment]
Looks like you fixed this in the latest version.

![yubioath-desktop-version](https://user-images.githubusercontent.com/184959/34081853-381820c8-e322-11e7-97cb-8c49a0cab876.png)

**Comment by emlun** [comment]
Yeah, it was a simple mistake in the Ubuntu publishing procedure. Thanks for reporting!
