### ISSUE TITLE
Yubico Autheticator stops to Scan QR codes

### ISSUE THREAD

**Issue by rafaelvannucci** [Yubico/yubioath-desktop#220]
- Yubico Authenticator version: 4.3.0 and 4.3.1
- Operating system and version: MacOS 10.13.2 and Linux Arch
- YubiKey model and version: Yubikey 4 Firmware version: 4.3.5
- Bug description summary: After 4.3.0/4.3.1 update, the Yubico Authenticator did not recognize new credentials on screen.

Steps to reproduce
---

Try to add new credentials by tap on Scan QR code

Expected result
---

Could not find QR code.

Actual results
---

Im adding mannualy.

Thank you all!

**Comment by emlun** [comment]
Confirmed and fixed in c066183. Thanks for reporting!
