### ISSUE TITLE
Require Touch with Slots mode doesn't generate OTP

### ISSUE THREAD

**Issue by nicsyubi** [Yubico/yubioath-desktop#221]
Yubikey 4, firmware 4.3.7
Authenticator 4.3.0 on Mac and Windows 10

Change preferences to Slot mode
Add a new credential requiring Touch
Credential will be seen in the Authenticator but double clicking or right-click Generate Code has no effect

Downgrade to Authenticator 4.2.0 and you can generate the OTP without having to regenerate the credential on the key

**Comment by emlun** [comment]
Thanks for reporting! This is fixed in 99a6226f which will be included in 4.3.2.
