### ISSUE TITLE
MacOS loses credentials after time in Slot Mode

### ISSUE THREAD

**Issue by nicsyubi** [Yubico/yubioath-desktop#225]
Authenticator 4.3.2
MacOS High Sierra 10.13.2
Slot mode operation
Credential requires touch

Insert key, touch to generate OTP then leave
After approx 4 mins the Authenticator says "No credentials found"
After a further minute it will generally find the credential again
Cycle then repeats

Only happens in Slot mode + Touch required
Does not seem to happen on Windows

**Comment by dagheyman** [comment]
Closing, not able to reproduce this anymore.
