### ISSUE TITLE
"Generate code" shortcut doesn't work

### ISSUE THREAD

**Issue by rettlsteiner** [Yubico/yubioath-desktop#226]
The "Generate code" shortcut doesn't work, the Authenticator will search for " " (space).

Versions:
Yubico Authenticator v4.3.2
YubiKey OATH v4.3.7

**Comment by dagheyman** [comment]
Thanks for the report! It's related to #222 , and will be addressed in the next version.

**Comment by dagheyman** [comment]
Fixed on master, will be in next release. The search field will continue to have the default focus, but the space shortcut will work when if the credential-list has focus. Pressing Enter (generate and copy) will work from "within" the search.
