### ISSUE TITLE
[question] How should I supposed to move secret tokens from a yubikey to another

### ISSUE THREAD

**Issue by Rictusempra** [Yubico/yubioath-desktop#231]
Thank you for opening an issue! If this is a bug report, please include the
following information:

- Yubico Authenticator version: 4.3.2
- Operating system and version: Windows 10.16299.192 Pro
- YubiKey model and version: 4

**Comment by emlun** [comment]
Hi, thank you for asking. In the future, please direct this kind of questions (that are not bug reports) to [Yubico Support][support]. 

It's not possible to read the secret out of the YubiKey once it's been written (this is one of the security features of the YubiKey), so it's not possible to copy it to another YubiKey.

What you need to do instead is re-register each credential you want to copy, and when prompted to input the secret into your authenticator app you add it to both YubiKeys.

If you have further questions about this, please contact Yubico Support.

[support]: https://www.yubico.com/support/get-support/
