### ISSUE TITLE
TOTP Secret length limitation

### ISSUE THREAD

**Issue by raabf** [Yubico/yubioath-desktop#24]
There seems to be an length limitation of the secret the app can handle.

Description
========= 

GitLab.com generates a secret with 80 characters.
If I try to add an account with this secret the *add new account* dialog and the main window simply closes and do nothing.
So is there any length limitation? 80 characters is much more then normal length, but I don't know if this breaks any standard. Well *Google Authentificator* and *FreeOTP* have no problems. So is this a memory problem of yubikey or does *yubioath-desktop* simply assumes a false, maximum length of the secret?

Reproduce
========

 1. Click on *Add Account*
 2. Enter any name
 3. Enter a long valid secret (for example 80 characters. I haven't tried out where is the border)
 4. Click on *OK*

Observed Behaviour
-------------------------

The *Add New Account* dialog and the main window closes. The tray icon will not exit and is still working. The Account is not added to the list.

Expected Behaviour
-------------------------

Only the *Add New Account* dialog closes and the item appears in the list.

Environment
-----------------

 + Windows 8.1
 + yubioath-desktop 0.1.1
 + Yubico NEO (all three modes enabled, already eight other accounts added)
 + Linux is not tested because #15 still persists

**Comment by TomAtYubico** [comment]
Hello,

that does not add any security, it actually may reduce it. SHA1 HMAC hash is always 160 bits or 20 bytes.
A block is 64 bytes [check: private static final byte hmac_buf_size = 64; https://github.com/Yubico/ykneo-oath/blob/master/applet/src/pkgYkneoOath/OathObj.java ]

So the key which is in base64 will be decoded and then truncated to fit a block.

**Comment by dainnilsson** [comment]
This is fixed in 2.x.x

**Comment by raabf** [comment]
Works well, great! :-)
