### ISSUE TITLE
Don't bother compiling qt4 on a Mac and compiling this repo, just install the pkg from yubico.

### ISSUE THREAD

**Issue by nottinhill** [Yubico/yubioath-desktop#25]
Could have been mentioned in the docs or on this repo, would have saved me 2 hours of my life.

https://developers.yubico.com/yubioath-desktop/Releases/yubioath-desktop-0.1.1.pkg

**Comment by dainnilsson** [comment]
The README now makes it clear that the preferred way of installing is by using a pre-built binary.
