### ISSUE TITLE
4.3.2 release is NOT gz archive

### ISSUE THREAD

**Issue by blshkv** [Yubico/yubioath-desktop#254]
it is just a tar file:

```
bash$ wget https://github.com/Yubico/yubioath-desktop/releases/download/yubioath-desktop-4.3.2/yubioath-desktop-4.3.2.tar.gz
bash$ file yubioath-desktop-4.3.2.tar.gz 
yubioath-desktop-4.3.2.tar.gz: POSIX tar archive (GNU)
```

**Comment by blshkv** [comment]
btw, the internal structure is not correct either, see https://github.com/Yubico/yubioath-desktop/issues/208.

"the tarball should unpack into a subdirectory with the same name as the release"
ie. it should be called ```yubioath-desktop-4.3.2```

**Comment by dagheyman** [comment]
Thanks for the report, this will be fixed in the next release.

**Comment by blshkv** [comment]
thanks!
