### ISSUE TITLE
pkg_resources.DistributionNotFound: PySide

### ISSUE THREAD

**Issue by raabf** [Yubico/yubioath-desktop#26]
An `pkg_resources.DistributionNotFound: PySide` occur if you try to lunch `yubioath`

**Full Error:**
```
Traceback (most recent call last):
  File "/usr/local/bin/yubioath", line 4, in <module>
    import pkg_resources
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 446, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 459, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 628, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: PySide
```

Don't really know where the fault is now, but maybe others have the same problem and are interested in the workaround.

Reproduce
---------------

1. Install yubioath-desktop deb from the ppa
2. This should install the dependencies `python-pyside.qtgui` and `python-pyside.qtnetwork`
3. pyside must not installed through pip
4. run cmd `yubioath`
5. The Error above is printed and the app exit.

Workaround
-----------------

Determine your pyside version. For example with `/usr/lib/python2.7/dist-packages/PySide/__init__.py`.
create a text file `/usr/lib/python2.7/dist-packages/PySide-1.2.1-py2.7.egg-info` with:

```
Metadata-Version: 1.0
Name: PySide
Version: 1.2.1
Summary: UNKNOWN
Home-page: UNKNOWN
Author: UNKNOWN
Author-email: UNKNOWN
License: UNKNOWN
Description: UNKNOWN
Platform: UNKNOWN
```

after that the yubioath starts normal. Of course you can also install pyside with pip. [Source](https://github.com/nvbn/everpad/issues/401#issuecomment-35834335)

Environment
-----------------

+ yubioath-desktop ~~2.0.1~~ EDIT 2.0.2 (It was always 2.0.2 sry I did not look correctly)
+ Ubuntu 14.04
+ pyside 1.2.1 from standard ubuntu repos
+ python 2.7

**Comment by dainnilsson** [comment]
I haven't been able to reproduce this. What's strange is that your error log shows the executable as "/usr/local/bin/yubioath". Installing from the PPA should place the executable in /usr/bin/. Also, the version of the package in the PPA is 2.0.2, not 2.0.1. I'm guessing you've got some manually installed version that is conflicting with the one from the PPA, could that be the case?

**Comment by raabf** [comment]
Yes you're right! :blush: 
I have tried to install it from the [Releases Page](https://developers.yubico.com/yubioath-desktop/Releases/) before. The install script failed at some point, but copying partly the files to `/usr/local/lib/python2.7/dist-packages/` and `/usr/local/bin`. After deleting them it works without the `/usr/lib/python2.7/dist-packages/PySide-1.2.1-py2.7.egg-info` file. Strange that the above workaround had fix that issue.
Sadly :disappointed:  #15 was not fixed with deleting the files.
