### ISSUE TITLE
Stuck on "Connecting to YubiKey"

### ISSUE THREAD

**Issue by SamSaffron** [Yubico/yubioath-desktop#262]
I am using Yubico Authenticator 4.3.2 on Windows 10 1709:16299.192 with a Yubikey Fido U2F I recently bought. 

When I launch the authenticator app all I see is: "Connecting to YubiKey..." and it never progresses. 

Any ideas how I should debug this?

**Comment by emlun** [comment]
It sounds like your key is a [FIDO U2F Security Key by Yubico][u2f-key], recognisable by its blue color. This device isn't a full YubiKey, and doesn't have the features required for using it with Yubico Authenticator. For that you'll need a YubiKey 4 series or YubiKey NEO device.

We'll take a look at detecting and indicating this in the Yubico Authenticator UI: #264.

If you have more questions about this, please direct them to [Yubico Support][support].

[support]: https://www.yubico.com/support/get-support/
[u2f-key]: https://www.yubico.com/products/yubikey-hardware/fido-u2f-security-key/
