### ISSUE TITLE
Hide/minimize doesn't trigger password dialog to re-enter password

### ISSUE THREAD

**Issue by seh-len** [Yubico/yubioath-desktop#273]
Yubico Authenticator version: 4.3.3
Operating system and version: Windows 10 
YubiKey model and version: Yubikey NEO
Bug description summary: 

As written in comment https://github.com/Yubico/yubioath-desktop/issues/62#issuecomment-168668372 the app should forget the password required to generate new codes once the app is minimized. 
At the moment this doesn't work, even removing/reinserting the stick doesn't force me to enter the password again. I need to exit the application to make it forget the password.

**Comment by dagheyman** [comment]
Thanks for the report, we'll look into if we want to change the current behaviour for the next version.

**Comment by dagheyman** [comment]
Removing the device should now forget the password properly (in 4.3.4). After some thought, I don't think forgetting the password (essentially "logging out") when minimising the window is a good user experience. When needed, I would instead suggest closing the app or removing the device.
