### ISSUE TITLE
Portable Version of Authenticator?

### ISSUE THREAD

**Issue by borque** [Yubico/yubioath-desktop#274]
Hello!
Is it possible to create a portable version of the authenticator?
My apologies for posting this question on this issue-tracker, but I asked Yubicos support and as their forum is closed they redirected me here with my question.
Thanks for opinions and a reply!

**Comment by emlun** [comment]
Hi, thanks for your interest! What do you mean by "portable"?

**Comment by borque** [comment]
Hello!
Wow, that's a quick reply, thanks!
I mean a version that can simply be started ("out of the box") without a need for further installation.
Yubioath 4.0.3 is only delivered as a complete installer (at least on windows).
Background: I need to use 2FA on a machine which I own and control, but for license and warranty reasons of another software I can not install new software on it. On the other hand I am allowed to execute programmes that do not need an installation. Don't ask... I do not understand the reason for these strange conditions myself.

**Comment by emlun** [comment]
That sounds like... a pretty useless policy indeed. :)

On both Windows and Mac, the installed app directory (usually `C:\Program Files (x86)\Yubico\Yubico Authenticator`) can actually be copied and run anywhere, so you should be able to run that from My Documents or off a USB drive or the like. I suppose we _could_ provide a plain zip file as an official distribution, but I'm not sure we'd want to. @dagheyman thoughts?

Alternatively, if you have an Android phone with NFC or USB-C and a YubiKey NEO or 4C, you can use the [Yubico Authenticator Android app][android] when you don't have access to the desktop version.

[android]: https://play.google.com/store/apps/details?id=com.yubico.yubioath&hl=en

**Comment by borque** [comment]
Hello!
I am glad that I am not the only one who thinks of that policy that way! ;)
Simply copying the directory and trying to run it from another location is exactly what I tried before posting here: 
It resulted in lots of error messages because of missing DLLs or other missing components. To make sure it was not because of missing system components installed alongside with Yubiauth (i.e. DotNet or VB or something like that, which is often bundled with installers) I tried it from different directories on two different machines: the one I initially had installed it on (my thought was there should be nothing missing after the successful installation) and on one where I never installed Yubiauth before. Same results?!
Regarding the use of Android: I am currently on iOS...

**Comment by nomade1999** [comment]
Any versions for iOS in the roadmap?

**Comment by Michael-Sabatini** [comment]
About a year later but stumbled across this for pretty much the exact same reason. 
On the off chance someone else is looking for a quick solution here is what I ended up doing.

Quick work around is to download the Yubikey Authenticator .exe file and I just used 7ZIP to extract the .exe into a folder instead of actually installing it.

Dropped that folder into a USB stick and it's working like a charm 👍 


P.S Yubico if you see this just take the easy solution like Microsoft did with visual studio code and just allow people to download the ZIP of the application then its pretty much portable already :)

**Comment by dagheyman** [comment]
Closing this since an official supported portable version of the app is unlikely to happen. I'm glad the workaround mentioned above works though.

**Comment by nomade1999** [comment]
Thanks 

I keep restarting the process regularly to free up resources 

/André

**Comment by schlagi123** [comment]
I think a portable version is very useful. Currently I have the case, that I must work on a computer without having root privileges. In this case a portable version is great

**Comment by Tim-K-DFW** [comment]
Hi guys, can you reconsider this and put an "official" portable version? I just tried the ZIP workaround, it failed with 64-bit version (on Win10, error message was about missing some DLL) and did work on the 32-bit version... but there's no guarantee it will keep working.
"Portable" means no installation needed: you download an EXE file and run it.
Use case is, as OP suggested, for a machine where I don't have admin access to install stuff. This will make the Yubico Authenticator a complete solution without any dependencies, and I'm sure many other users will appreciate that. Hope this would not be too difficult or time-consuming. Thank you in advance.

**Comment by fdennis** [comment]
Hey,
We hear you and will have a discussion about this.
In the meantime, have you tried what @emlun suggested above - installing Yubico Authenticator and copying it over?

**Comment by Tim-K-DFW** [comment]
Hi, appreciate the quick response! Yes, just tried that, same thing - `VCRUNTIME140_1.dll` is missing.

**Comment by fdennis** [comment]
I see. Just to make sure I understand: Did you install it on one computer and then copy the files over to another?

**Comment by Tim-K-DFW** [comment]
Yes, that is correct. Fully installed on _A_ (and it works), copied entire installation folder (in `Program Files/...`) to _B_, now trying to execute `yubioath-desktop.exe` on _B_, getting the above-mentioned DLL error.

**Comment by fdennis** [comment]
Yeah, that makes sense now that I think about it. The installer runs an executable called vcredist_x64.exe which is a Visual C++ Redistributable Package. When you copy over the installation folder, the files that vcredist_x64.exe installed do not get copied over. To run this executable you need admin permissions, which you do not have if you want a portable version. Basically, this means that copying from one computer to another will not work.

We will have to discuss this internally, but thank you all for letting us know about this.

**Comment by emlun** [comment]
Yeah, I think I only tried it by copying from the install folder to a different folder on the same machine. My mistake, sorry.

**Comment by MPatzek** [comment]
Yes, please a portable version, that can be access without administrator rights.

**Comment by Goldich** [comment]
Hi,
I have the same problem, that I can not install any application on my laptop. I found a solution with the MSI Packages:

- download the latest MSI package from https://developers.yubico.com/yubioath-desktop/Releases/
- open the windows command line
- type `msiexec /a C:\yubioath-desktop-5.1.0b-win64.msi /qb TARGETDIR=C:\yubi` 

> Please change the path of the MSI file to your file location and choose as target dir a folder where you have write access (e.g. your desktop)

**Comment by dainnilsson** [comment]
In which way is the workaround not working for you? Both extracting the MSI via the command above, as well as manually copying the contents of the installation directory should work as far as I know.

**Comment by dainnilsson** [comment]
If you have access to another Windows machine, I believe you should be able to extract the MSI there and then copy the files to the machine without command line access.
