### ISSUE TITLE
Update Checking

### ISSUE THREAD

**Issue by Riajyuu** [Yubico/yubioath-desktop#275]
- Yubico Authenticator version: 4.3.3
- Operating system and version: Windows 10 Pro latest release
- YubiKey model and version: 4

Please add facility for the program to check any update.
Another approach is Microsoft Windows Store where you can wrap any current Win32 program

**Comment by dagheyman** [comment]
Thanks for the suggestion. This is no is currently planned, but I'll leave the issue here as an enhancement suggestion.

**Comment by edelstone** [comment]
+1 to check for updates within the application. I'm fairly certain this is the only app I use regularly that doesn't have even a manual way to do this within the app. (Mac user btw)

**Comment by dagheyman** [comment]
This is still not planned as a in-app feature, but the app is now available in the [macOS App Store](https://apps.apple.com/us/app/yubico-authenticator/id1497506650?ls=1), and will be in the Microsoft Store in the next version of Windows 10.

**Comment by edelstone** [comment]
Interesting. i was unaware of that; pretty much solves my problem.

**Comment by braathen** [comment]
just to elaborate a bit more to what Dag is saying, we have deliberately chosen to be quite conservative and strict about any kind of network or 'calling home' activity from inside the app. while this is also a feature that I personally have missed, our solution is now to allow the app stores to handle the version checking and updating. I hope you find it to be a good enough work around.

**Comment by edelstone** [comment]
Perfectly fine by me; I'll be switching over.

**Comment by dagheyman** [comment]
Closing this, since no in-app automatic updates beyond what the different app stores provide is likely to happen.
