### ISSUE TITLE
New token is regenereted infinitely without user's intention

### ISSUE THREAD

**Issue by punksta** [Yubico/yubioath-desktop#279]
- Yubico Authenticator version: 4.3.2
- Operating system and version: `Debian 9.4(stretch) x64`
- YubiKey model and version:  `yubikey 4`
- Bug description summary: 

The app is generating new token just after last token expired without any input. 
Bug exists only for `https://www.yourserver.se` site, others work without problem

Steps to reproduce
---
1) complete two factor auth set up on https://www.yourserver.se with requiring touching.
2) observe

Expected result
---
Token is generated only when I click `generate token`

Actual results
---

token is regenerated infinitely without any input.

Other info
---
Maybe it's problem of yourserver.se two factor setup, anyway I believe it should not work this way.

thanks

**Comment by emlun** [comment]
Thanks for the report. Could you please try generating codes using the [YubiKey Manager][ykman] CLI as well? Does `ykman oath code` also generate a code without needing touch?

[ykman]: https://github.com/Yubico/yubikey-manager

**Comment by dagheyman** [comment]
I just tried registering an account on yourserver.se, and adding the TOTP credential to Yubico Authenticator with require touch. It seemed to work well. Are you sure you didn't just forget to check the require touch checkbox?

**Comment by punksta** [comment]
Issue disappeared after resetting of two-factor authentication and activation again. Not sure how I got it first time.

**Comment by punksta** [comment]
I am getting this again!
![image](https://user-images.githubusercontent.com/13404754/54984287-96459080-4fbf-11e9-8d1e-1e1701415b88.png)
```
uname --all 
Linux stanislav-ThinkPad-X230 4.18.0-16-generic #17-Ubuntu SMP Fri Feb 8 00:06:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by emlun** [comment]
Yes, this is an intended feature for touchless credentials.

**Comment by punksta** [comment]
@emlun touchless code is being generated in loop without clicking "new code"

**Comment by punksta** [comment]
is that really expected feature ? :)

**Comment by emlun** [comment]
Yes, user interaction is only needed to generate codes for HOTP credentials or credentials that require touch.
