### ISSUE TITLE
NFC Support

### ISSUE THREAD

**Issue by audunmg** [Yubico/yubioath-desktop#288]
I just discovered I can use PIV and openPGP on the built-in nfc reader on my laptop in CCID mode.

The only thing I miss is using the yubioath-desktop on the nfc reader as well.

It would be so cool if it would work :)

**Comment by dagheyman** [comment]
Fully agreed that we want to support this, it's on the roadmap. No ETA yet though.

**Comment by rmenessec** [comment]
Would love to see this as well!

**Comment by dagheyman** [comment]
While this is still on the roadmap for the GUI (next major version probably), the latest release of the command line tool [ykman](https://developers.yubico.com/yubikey-manager/) includes a flag to specify the smart card reader. To try it out with an external NFC reader:

`$ ykman --reader [READERNAME] oath code`

**Comment by matthewmb** [comment]
+1, my laptop can read the yubikey with NFC, and it would be awesome if authenticator recognised it

**Comment by dagheyman** [comment]
Experimental support for this is available in version 5.0.0, by specifying an external smart card reader under settings.

**Comment by matthewmb** [comment]
Version 5.0.0 is working for me, using the custom CCID settings. However, I had to disable NFC OTP interface on the yubikey to get it to work (using the yubikey manager).

With NFC OTP enabled, windows 10 jumps in with a 'tap to receive content from another device', which then opens up a browser to https://demo.yubico.com/yk/ and the OTP.

I use NFC OTP with Lastpass on mobile, so I can't disable this. Any ideas?

**Comment by dagheyman** [comment]
@matthewmb Interesting, will have to investigate this scenario a bit. What reader/laptop are you using?

**Comment by graealex** [comment]
That's really clumsy. The authenticator should be able to find a OATH-TOTP app on any qualifying smart card on any connected reader, including the builtin virtual USB card reader when plugging the key directly into the computer. It should also not immediately remove the still-valid codes after removal of the device from the NFC reader. 

Besides, why has the 5.0 release become unintelligible bloatware? The text is barely readable. These are still desktop apps, no need to get too fancy.

**Comment by matthewmb** [comment]
@dagheyman my laptop is a Dell Latitude 7490, the built in NFC reader is Broadcom. The most detailed information I could find is [here.](https://www.dell.com/support/manuals/au/en/audhs1/latitude-13-7390-laptop/latitude_7290_7390_7490_tgb/security-option-contactless-smartcard-reader?guid=guid-1e4362a5-06ff-440b-ae10-23f1da6af8af&lang=en-us).

Other relevant info: Yubikey 5 NFC, default configuration. Windows 10 Pro, 1803.
