### ISSUE TITLE
TOTP not generating correct codes on macOS

### ISSUE THREAD

**Issue by legsak1mbo** [Yubico/yubioath-desktop#290]
- Yubico Authenticator version: 4.3.4
- Operating system and version: 10.12.6
- YubiKey model and version: YubiKey Neo
- Bug description summary: TOTP codes are not accepted by apps. The codes are different from those generated by other apps such as Authy and Google Authenticator when using the same secret.

Steps to reproduce
---
Add a "New credential" to Yubico Authenticator and save.

Expected result
---
Codes generated should be accepted by applications.

Actual results
---
The codes are not accepted. Codes generated by other authenticator apps using the same secret are fine.

Other info
---
I've tried changing the algorithm to no avail.

**Comment by dagheyman** [comment]
Thanks for the report! For what services are you seeing this?

**Comment by legsak1mbo** [comment]
No problem. Any services I try including Dropbox and some apps at work.

I've also knocked up a quick test app in PHP and the results are the same.

**Comment by dagheyman** [comment]
Wierd. So I tried adding this credential,
<img width="789" alt="screen shot 2018-05-21 at 15 28 36" src="https://user-images.githubusercontent.com/9592259/40310039-d59759a0-5d0b-11e8-8adc-cce9dd86d955.png">
 from http://security-totp.appspot.com/ on a NEO 3.5.0, using Yubico Authenticator 4.3.4 on macOS 10.13.4. I then added the same credential to Google Authenticator on iOS, and I get the same TOTP codes. Do you get different codes if you do the same?

**Comment by legsak1mbo** [comment]
Unfortunately I've left the office for the day.

I've just tried it on my laptop running 10.13 and things work as expected. So it appears that it may be an issue with 10.12.

Note that the issue that I reported at https://github.com/Yubico/yubioath-desktop/issues/289 isn't happening on this laptop either.

**Comment by dagheyman** [comment]
Closing this one since it works well on 10.13.
