### ISSUE TITLE
Scaling issue in Windows 10 

### ISSUE THREAD

**Issue by pauby** [Yubico/yubioath-desktop#291]
- Yubico Authenticator version: **4.3.4**
- Operating system and version: **Windows 10 Pro 1803 (Build 17134.48)**
- YubiKey model and version: **Yubikey NEO**
- Bug description summary: 

Yubico Authenticator looks to have scaling issues using Windows 10 in 1920 x 1280 resolution. Menus are not shown, scroll bar and search status line are cropped and the blue bar that moves up before changing the keys is missing. PIN box is also cropped.

I tend to use 150% font size however I have tried this with 100% and it's the same issue.

Screenshots attached (obviously I've obscured some of the entries).

![yubioath-desktop_2018-05-23_10-40-12](https://user-images.githubusercontent.com/12760779/40416898-666e9e28-5e76-11e8-8e52-68e79b02d377.png)
<img width="129" alt="yubioath-desktop_2018-05-23_10-38-07" src="https://user-images.githubusercontent.com/12760779/40416903-69cfeffe-5e76-11e8-9f8d-e0ba582a2113.png">

Steps to reproduce
---

For me it's simply a matter of running the app  day to day.

**Comment by dagheyman** [comment]
Thanks for the report. I think this looks more like OpenGL driver issues than scaling issues actually.
Could you try running the app with the environment variable `QT_OPENGL` set to `software` or `angle` and see if it makes a difference?

**Comment by pauby** [comment]
Thanks for the quick response. Both of those options seem to work fine. I'm assuming the angle one would be better (that seems to convert OpenGL to DirectX calls)?

**Comment by dagheyman** [comment]
Yes, I also think `angle` is preferred, but in some environments I've seen it can cause flickering when resizing the application window. You can also try to update your graphics card drivers and see if that helps.
