### ISSUE TITLE
Authenticator only generates codes once, then stops

### ISSUE THREAD

**Issue by rmenessec** [Yubico/yubioath-desktop#292]
- Yubico Authenticator version: 4.3.4
- Operating system and version: Windows 10 Enterprise 1803 x64
- YubiKey model and version: NEO 3.4.9
- Bug description summary: After connecting to the key, reading the secrets, and generating a set of TOTP codes for each entry, Authenticator just... stops. No new TOTP codes are generated. The progress bar remains empty and does not appear to redraw. Exiting causes Authenticator to free for about 30 seconds, during which time the window is gone, but the process still exists, and trying to launch Authenticator causes an error saying that Authenticator is still running.

Steps to reproduce
---
I think the only step was upgrading from 10 1709 to 1803. Authenticator was working as expected after a clean install of 1709 on bare metal. Since the upgrade, Authenticator started displaying this bizarre behavior. No third-party driver changes were made; unknown whether 1803 contained new in-box drivers with the new build that were related to the USB stack or the CCID or other drivers used by YubiKey. Driver dates are still "2006-06-21".

Expected result
---
Authenticator should have continued regenerating TOTP codes on each time roll-over.

Actual results
---
Authenticator stopped generating new codes on roll-over.

Other info
---
This YubiKey and other YubiKeys (other NEOs, 4 Nano, _etc._) work normally on other platforms (10 Enterprise 1709, various Linux desktops, _etc._).

**Comment by anderscode** [comment]
I have the same issue.
Same version of Authenticator,Windows and NEO Key. The key works ok on my other pc with Windows 1709. Mode is set to CCID on both computers.

Logs from the following command included.
yubioath-desktop.exe --log-level DEBUG --log-file c:\temp\auth.txt
[auth.zip](https://github.com/Yubico/yubioath-desktop/files/2116384/auth.zip)

**Comment by dagheyman** [comment]
Is this reproducible with version 5.0.0 ?

**Comment by anderscode** [comment]
Tested 64Bit version 5.0.0 now and it works ok no issues anymore.
