### ISSUE TITLE
[Windows Installer] Failure to update from 4.3.2 -> 4.3.4

### ISSUE THREAD

**Issue by zypA13510** [Yubico/yubioath-desktop#298]
- Yubico Authenticator version: 4.3.2
- Operating system and version: 64-bit Windows 10 Enterprise 1709 Build 16299.431
- YubiKey model and version: Yubikey NEO
- Bug description summary:

Upon yubioath-desktop 4.3.4 installation (update from 4.3.2), the installer will actually delete the old installation folder, causing the new version fails to install. Manually creating the installation path and then click _Retry_ resolves this issue (just clicking _Retry_ does not work). Screenshot:

![image](https://user-images.githubusercontent.com/8077540/40920855-62beef48-6840-11e8-973c-49782fdae2a2.png)

Steps to reproduce
---
1. Install yubioath-desktop 4.3.2 on Windows
2. Download yubioath-desktop 4.3.4 x64 installer, and run it

Expected result
---
Everything go smoothly and yubioath-desktop is updated from 4.3.2->4.3.4

Actual results
---
See the screenshot above.

**Comment by dagheyman** [comment]
Was never able to reproduce this, can reopen issue if it's reproducible with version 5.0.0.
