### ISSUE TITLE
Support QR code scanning somehow?

### ISSUE THREAD

**Issue by jas4711** [Yubico/yubioath-desktop#3]
I don't know how this would work, so this is more a placeholder for future thinking.  For example, how to get the QR code into the application?  Drag'n'drop an image?  Take a screenshot of the system and scan for QR code?  A browser plugin to do it automatically on OATH-signup pages?

**Comment by bakketun** [comment]
Taking a screenshot and reading QR codes is easy: https://gist.github.com/bakketun/1f8db75a783d16e3c638

**Comment by dainnilsson** [comment]
zbar seems like a good alternative for doing this, but unfortunately it looks like it's quite difficult to get working on a Mac (at least for me, as I'm not very familiar with the OS). Even so, it's the best candidate I've been able to find with any cross platform support for parsing QR codes.

**Comment by dainnilsson** [comment]
I ended up implementing this from scratch in pure Python instead. It seems to work quite well. It will be in the next release.
