### ISSUE TITLE
[Suggestion] Optional Alternating Rows

### ISSUE THREAD

**Issue by VGrol** [Yubico/yubioath-desktop#302]
By default the GUI displays alternating rows between each key entry.
Ideally, there'd be a setting that allows for switching off the alternating row colours, leaving the background in an uninterrupted even colour.

This is mostly a vanity thing, but I feel like it'd be a nice QoL setting.

**Comment by dagheyman** [comment]
Thanks for your suggestion, I'll think about it. Just out of curiosity, what OS are you using?

**Comment by VGrol** [comment]
That'd be the Arch-Linux distribution.
Alternating rows always make the content a little bit busier and thus harder to read for me.

**Comment by dagheyman** [comment]
Closing as not relevant anymore, since the UI is re-designed for version 5.0.0.
