### ISSUE TITLE
build issue on mac

### ISSUE THREAD

**Issue by apps4u** [Yubico/yubioath-desktop#303]
- Yubico Authenticator version: 4.3.4
- Operating system and version: mac 10.13.5
- YubiKey model and version:  4
- Bug description summary:  can not build, Ive installed QT Creator and I can load project but not build.
So I went to the command line and tried to run the setup_mac script but I get this error

'dev-util/setup-mac.sh: line 9: vendor/pyotherside/src/src.pro: No such file or directory"

Steps to reproduce
---
run above command.

I wanted to add a new feature for mac os,  So I could keep the app in the menu bar, I was going to use for myself and issue a PR if other would like the feature. 

Anyway not sure what I'm doing wrong but I do not have the vendor folder. not sure how to create it. I did not see and build tool configs for any tool that creates a vendor folder. .

**Comment by dagheyman** [comment]
Thanks for the report. Did you see the development docs? https://github.com/Yubico/yubioath-desktop/blob/master/doc/development.adoc Pyotherside needs to be installed on your system to run the app when building from source.
