### ISSUE TITLE
yubioath-desktop was not working

### ISSUE THREAD

**Issue by thomase1993** [Yubico/yubioath-desktop#304]
After I had started the service pcscd.socket as suggested in Ticket 192, it worked under fedora. 
Here the link to the ticket: https://github.com/Yubico/yubioath-desktop/issues/192
Is it an installation step i missed to follow? I didn't really find some installation instructions for fedora on your website.

Can I safely enable this pcscd.socket?

Thank you for this great piece of software and hardware. :smiley:

**Comment by dagheyman** [comment]
Thanks for the report! We're not maintaining the Fedora package, but enabling the pcscd.socket is fine. Closing.
