### ISSUE TITLE
Codes get cropped on Windows 10 Pro

### ISSUE THREAD

**Issue by adamchainz** [Yubico/yubioath-desktop#310]
- Yubico Authenticator version: 4.3.4
- Operating system and version: Windows 10 Pro
- YubiKey model and version: N/A
- Bug description summary: 

Rendering on Windows 10 ends up with the codes cropped, but usable:

![unnamed](https://user-images.githubusercontent.com/857609/46094438-e333e000-c1b1-11e8-8004-775eb05a1fa1.png)

Steps to reproduce
---

Open the app with yubikey in

Expected result
---

Codes render without cropping

Actual results
---

Codes cropped, despite resizing window

**Comment by dagheyman** [comment]
Hi, thanks for the report!

This looks like an issue related to your graphics driver. See #291 and #293.
Try updating your drivers. If that doesn't help, you could try the workaround setting the environment variable `QT_OPENGL` to `angle` or `software`.
