### ISSUE TITLE
Impossible to use two-factor authentication

### ISSUE THREAD

**Issue by shenron** [Yubico/yubioath-desktop#312]
- Yubico Authenticator version: 4.3.4 (from https://aur.archlinux.org/packages/yubico-yubioath-desktop/)
- Operating system and version: archlinux
- YubiKey model and version: Yubikey 4 (2.1)
- Yubikey OATH Version: 4.3.7
- Bug description summary: 
Impossible to enable two-factor authentication on github, npm or what ever. When they ask the 6 digits, they are always wrong.

Steps to reproduce
---
Insert the key, scan the QRcode, double click on the new entry, press the button.

I have no error message with `ykman oath code Github`, everything seems to works. But digits are wrong.

I don't know if it's linked or not, but I added gpg certs inside the key to sign commit, use ssh etc ...

Other thing very strange, the same key works on my mac ... 
The version of Yubico Authenticator is the same but I don't have the version of OATH used.

Thank you very much for help.

**Comment by emlun** [comment]
My first guess on this is that your system clock might be off by a few seconds too many. Does the credentials on the same YubiKey work when using YubiKey Authenticator or `ykman` on a different computer, or on Android?

**Comment by emlun** [comment]
Ah, right:

>Other thing very strange, the same key works on my mac ...

In that case I would definitely suspect the system clock.

**Comment by shenron** [comment]
Thank you for your answer.

I tried to add the entry with type: `Counter base`. And I have the same problem.

**Comment by emlun** [comment]
A counter based credential won't work with a server expecting time based credentials.

Probably the easiest way to synchronize your system clock is using `ntpdate`, from the [ntp][package] package:

```
$ sudo ntpdate pool.ntp.org
```

This will synchronize the clock and report back how offset the system clock was from the network time. My hypothesis is that this will probably be more than 30 seconds off.

I would also recommend configuring and enabling the NTP daemon if you haven't done that already. See the [Arch Wiki article][wiki] for instructions on that.

[package]: https://www.archlinux.org/packages/extra/x86_64/ntp/
[wiki]: https://wiki.archlinux.org/index.php/Network_Time_Protocol_daemon

**Comment by shenron** [comment]
Thank you so much for your help !
It works.
