### ISSUE TITLE
Cannot Run on Linux

### ISSUE THREAD

**Issue by nekromantik** [Yubico/yubioath-desktop#313]
- Yubico Authenticator version: 4.3.4
- Operating system and version: Kali Linux 2018
- YubiKey model and version: 4 Nano
- Bug description summary: Desktop App errors after compile

Steps to reproduce
---
I downloaded source and compiled the app on my machine and when launching the app I get 

> ./yubioath-desktop: symbol lookup error: /usr/lib/x86_64-linux-gnu/qt5/qml/io/thp/pyotherside/libpyothersideplugin.so: undefined symbol: PyUnicodeUCS4_AsUTF8String

Expected result
---
App launches

**Comment by dagheyman** [comment]
Hi, thanks for the report. Did you see the development docs? Did you compile and install pyotherside?
https://github.com/Yubico/yubioath-desktop/blob/master/doc/development.adoc
