### ISSUE TITLE
yubioath-desktop 4.3.3 and 4.3.4 crash on open

### ISSUE THREAD

**Issue by Nesos-ita** [Yubico/yubioath-desktop#319]
- Yubico Authenticator version:   
4.3.3 and 4.3.4, both crash on open
- Operating system and version:   
Windows 7 32bit  (Acer aspire one)  
Here you can find more complete pc specs:
https://github.com/Yubico/yubioath-desktop/issues/179
- Bug description summary:   
I have a pc that i don't use often, i have decided to update the authenticator but:
4.3.2 works (i'm using this version as workaround)  
4.3.3 crash as soon as i open the program  
4.3.3 crash as soon as i open the program (latest available version)  

Notes:  
If it can be useful, as soon as i open the program it crash but i can see the border of the window while the inside is transparent (i can see my desktop icons inside the program) everything is "greyed" like when a windows program is freezed

**Comment by dagheyman** [comment]
There is a new version out (4.3.5) that you may try, not much have changed but it is built with a newer Qt version that might affect this. Other things to try: Update graphic drivers. Testing with the QT_OPENGL env variable set to either "software" or "angle" as mentioned in the old issues.

**Comment by Nesos-ita** [comment]
sorry for the delay in my answer, setting env var to `software` works, angle doesn't.  
It's a very old pc (still windows 7 32 bit), i can keep the env var or use an older version but if you fix this it would be nice.

**Comment by 234845** [comment]
Hello,

Windows 10 (1809) using YA version 4.3.6

Not as bad as 4.3.5 but often takes 2 or 3 attempts to get the application to stay open.

Right click on entries to copy crashes the app.

Do you need anything more - Files/Logs etc.?

**Comment by Nesos-ita** [comment]
updating to the latest version (4.3.6) solved the problem

**Comment by 234845** [comment]
Confirmed, 4.3.6 is nice and stable - thank you very much!
