### ISSUE TITLE
YubiKey Edge fails to be recognized

### ISSUE THREAD

**Issue by SueHeim** [Yubico/yubioath-desktop#32]
Steps to recreate:
1. Insert a YubiKey Edge into USB port (firmware version is 4.1.6).
2. 2. Use Yubico Authenticator to program slot 2 for 6 digit TOTP, manually entering secret key. 
3. Click OK. 
4. When prompted to overwrite the credential stored in slot 2, click OK. (I had already deleted the configuration in slot 2, why am I being prompted for this? Is this just precautionary?)
5. When returned to the main Authenticator window, I'm prompted to Insert a YubiKey.

Pulling out the key and reinserting it does nothing. It appears the configuration of the Edge isn't saved.

On a different note, it would be nice to be able to copy the secret key into the field in the application. Do you want me to create a new issue as an Enhancement request?

**Comment by dainnilsson** [comment]
Reproduced and confirmed. It will be fixed in the next release. This affects all non-CCID devices when using slot-based credentials.

Regarding the feature, you mean like adding a "Paste from clipboard" button next to the field or something? Yes, please open a new Enhancement issue for that!
