### ISSUE TITLE
Folders to organise tokens - Enhancement Request

### ISSUE THREAD

**Issue by Barltarman** [Yubico/yubioath-desktop#326]
- Yubico Authenticator version: 4.3.5
- Operating system and version: Ubuntu 18.04.1
- YubiKey model and version: YubiKey 4

I'm now starting to get quite a few tokens in my Authenticator and they are not organised in any particular way. Ideally I'd love to be able to put them in folders like "Social Media", "Email", "Banking" etc to make it easier to find them.

**Comment by emlun** [comment]
Thanks for the suggestion, but it's unlikely that we'll do this. There's no way to store that additional metadata on the YubiKey, so it would have to be stored on the client machine which means it wouldn't follow the YubiKey between machines. We do have the filter feature which fills much the same role.

**Comment by dagheyman** [comment]
Closing this. Since the max amount of credentials is 32, and we have Quick Find and Favorite Credentials (since version 5.0.0), this will not be implemented.
