### ISSUE TITLE
Upload new package for Debian

### ISSUE THREAD

**Issue by mhoran** [Yubico/yubioath-desktop#328]
The upcoming release of Debian buster will drop yubioath-desktop due to incompatible dependencies [1]. However, the latest version of yubioath-desktop looks to be compatible with buster [2].

Most of the package uploaders [3] look to be Yubico employees. The Debian package scripts are pointing to an archived repository [4]. I'm not sure who can fix this, but it'd be great to get yubioath-desktop updated and re-imported to testing so that it's not dropped from the upcoming release of buster.

[1] https://tracker.debian.org/news/863112/yubioath-desktop-removed-from-testing/
[2] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=886810#15
[3] https://tracker.debian.org/pkg/yubioath-desktop
[4] https://github.com/Yubico/yubioath-desktop-dpkg

**Comment by Tyler-2** [comment]
+1

**Comment by dagheyman** [comment]
Hi, thanks for the report.

However Yubico is no longer directly uploading packages to Debian, the linux packages we currently support is the Ubuntu PPA package and the .AppImage bundle. The official repo for the Debian package for yubioath-desktop can be found here https://salsa.debian.org/auth-team/yubioath-desktop, I'd suggest trying to get the people maintaining that to upload a new version.

**Comment by mhoran** [comment]
Thanks for the quick reply, @dagheyman. Do you have any idea who to contact about this? All of the uploaders appear to be Yubico employees. The maintainer is listed as Debian Authentication Maintainers, but attempting to email the alias results in a rejection as I'm not on the list.

**Comment by dagheyman** [comment]
I'm not sure, but I know that @nbraud have packaged some of our software for Debian recently. Do you have any input here?

**Comment by 0xaf1f** [comment]
> The maintainer is listed as Debian Authentication Maintainers, but attempting to email the alias results in a rejection as I'm not on the list.

@mhoran, emails to the bug-tracking system go the package maintainer, so your posting to the ticket made it to the auth team's mailing list: https://alioth-lists.debian.net/pipermail/pkg-auth-maintainers/Week-of-Mon-20190121/001257.html
...then it's just a matter of getting them to answer

**Comment by linuxluser** [comment]
For others who land here, you can download and run the current AppImage on a Debian system by getting it here: https://developers.yubico.com/yubioath-desktop/Releases/. Additionally, add a `.desktop` file in your ` ~/.config/autostart` folder for it to launch automatically.

I will say, though, that it still would really be nice to have an up-to-date package for this from the official Debian repos, especially as Buster is released (might be too late for Buster, though). Even if the package is just the AppImage with supporting scripts and configs for the system.

**Comment by JacobBrownAustin** [comment]
I recently upgraded to Buster since it was just released recently.  I had trouble with the `yubioath-gui` application that I had been using just fine in Stretch.  After upgrading,  it no longer showed my yubikey as being connected anymore (even though the yubioath command line application did show it). 

So I just tried the AppImage that @linuxluser suggested in the previous comment,  and it works just fine.  In fact,  it works even better than the previous application I was using because I can have it running at the same time as I'm using gpg-agent (for ssh) and have both of the access my yubikey without having to close one or the other first.

I do wish that someone would add this to buster,  because yubikey is super useful to me.  I'm sure more Debian users would find yubikeys useful if it was added to buster,  so it seems like an easy sell to the sales/marketting teams at Yubico to get this done.

**Comment by dagheyman** [comment]
@JacobBrownAustin 
We do like to see our software in the official repositories for various Linux distributions, but we don't currently have the bandwidth to maintain that on our side. We're happy to work with uploaders/package maintainers though, and assist in any way possible.

Related issue for yubikey-manager-qt: https://github.com/Yubico/yubikey-manager-qt/issues/189

**Comment by taowa** [comment]
Hi there!

I've filed an intent to salvage [(bug #947154)](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=947154), and have a working package on [mentors.](https://mentors.debian.net/), with the packaging work on [salsa](https://salsa.debian.org/taowa/yubioath-desktop).

The salvage procedure wants me to wait 27 days before going ahead with an upload, but a (preferably signed) statement from someone here would allow me to get around to it faster :).

Thanks,
Taowa

**Comment by taowa** [comment]
(@dagheyman )

**Comment by dagheyman** [comment]
@taowa Packaging looks great! Is there an easy way for me to test out the package?

**Comment by taowa** [comment]
Hey there @dagheyman, here it is: https://people.debian.org/~taowa/yubioath-desktop_5.0.1-3_amd64.deb

**Comment by dagheyman** [comment]
Thanks! 

Tested on a clean `debian/testing` install.

The build seems to be missing the dependency `qml-module-qtquick-controls2`. After installing that manually it worked well.

**Comment by taowa** [comment]
Hmm, I added qml-module-qtquick-controls2 as a build dependency a couple weeks ago [on Salsa](https://salsa.debian.org/taowa/yubioath-desktop/blob/master/debian/control). Is it a dependency to run it as well? I can add it if so.

**Comment by taowa** [comment]
Ah, sorry, didn't read the edit. I'll add it as a dependency.

**Comment by taowa** [comment]
Quick update: it's currently in the NEW queue. If it's accepted it will make its way into sid and then into the next stable release.

**Comment by taowa** [comment]
As per [0], the package has been accepted into unstable and will be available in the archive within the next couple of hours. Thanks for your help @dagheyman, I think this issue can now be closed :).

[0] https://alioth-lists.debian.net/pipermail/pkg-auth-maintainers/Week-of-Mon-20200330/001543.html

**Comment by dagheyman** [comment]
Awesome, thanks again for your work on this.
