### ISSUE TITLE
When adding secret key for a YubiKey Edge, add capability to copy the key text

### ISSUE THREAD

**Issue by SueHeim** [Yubico/yubioath-desktop#33]
Enhancement request, usability improvement.

Right now, in order to add the secret key for a YubiKey Edge (or other key), you have to manually enter the key text. In order to improve the user's experience, please add the capability to copy the key into the "Secret key" field. The easiest way would be to recognize the Ctrl+V key press (or Apple+V on a Mac system). Not necessary but "nice to have" would be a "Paste from Clipboard" button, or something similar.

**Comment by dainnilsson** [comment]
Can't you already paste into the field?

I agree that having a button to paste further simplifies this process.

**Comment by SueHeim** [comment]
Unless there is something that I'm not doing, neither DavidM or I could get it to paste yesterday. And I tried again today working on the Edge issue (that's been fixed), and it still didn't work. (My secret key has spaces in it, but I'd think it would at least paste as many chars as it could, since it's a limited field, yes?)

**Comment by dainnilsson** [comment]
Ah! It's the spaces then! Good, that should definitely be fixed!

**Comment by SueHeim** [comment]
Ah! Yes, it *is* the spaces! I had copied the secret key directly from Dropbox, and was trying to configure both my NEO and Edge. I didn't think to remove the spaces when I configure the YubiKey. It works fine when I removed the spaces. 

Can you modify this so that spaces are stripped out of key text when pasted in? 

Or do you want to close this out, and I'll just document to ensure that no spaces are included in the key text when it's being pasted in?

(And this IS a low priority!)

**Comment by dainnilsson** [comment]
I've fixed the issue in the source code, but I'm not likely to make a new release until there are more improvements/fixes.

**Comment by SueHeim** [comment]
Thanks Dain. That's good enough for me.
