### ISSUE TITLE
Stuck on reading credentials

### ISSUE THREAD

**Issue by StrangerTwenty** [Yubico/yubioath-desktop#335]
- Yubico Authenticator version: 4.3.5
- Operating system and version: Windows 10 Pro build 17763
- YubiKey model and version: Yubikey 5 NFC
- Bug description summary: 

Stuck on "reading credentials...", sometimes I may get it to display codes if a wait about 60-90 seconds, but once it does load, it'll gives me expired codes and doesn't refresh. Usually it will work only once after first boot, but recently stopped doing that. 

side note: When It does load, I'm unable to add new credentials with the QR code, just sits and loads indefinitely. 

Steps to reproduce
Launch the software

Note that I can perfectly retrieve the codes using the phone app which has yet to fail me, not even once (the desktop app fails me about 80% of the time).  I'm also able to retrieve codes just fine with the "ykman oath code" console command.

**Comment by dagheyman** [comment]
Thanks for the report.

It's a bit hard to tell what is going here, but it might be related to the graphics drivers.
Could you try to see if there are any updates available to your graphics card?
Also, could you try running the app with the environment variable `QT_OPENGL` set to `software` or `desktop` ?
