### ISSUE TITLE
Software u2f support in yubioath desktop roadmap ? 

### ISSUE THREAD

**Issue by mcarbonneaux** [Yubico/yubioath-desktop#347]
there a Software u2f support in yubioath desktop roadmap ?

**Comment by dagheyman** [comment]
No. Note that there is no FIDO functionality at all in this application, the protocols supported is TOTP and HOTP.

**Comment by mcarbonneaux** [comment]
Why not expose hotp/totp with fido?

**Comment by emlun** [comment]
FIDO is a set of completely different technologies which don't include any OTP functionality at all.

**Comment by mcarbonneaux** [comment]
They use ocra from oath!
