### ISSUE TITLE
fails to read in CCID mode (linux)

### ISSUE THREAD

**Issue by modgethanc** [Yubico/yubioath-desktop#348]
- Yubico Authenticator version: 4.3.5 (from AppImage)
- Operating system and version: Debian Stretch
- YubiKey model and version: Yubikey NEO
- Bug description summary: In CCID mode, it says:

> Authenticator mode is set to CCID, but the CCID connection mode is not enabled.

I've enabled CCID on the Yubikey NEO, and if I insert the exact same key into a Mac running Yubico Authenticator, it correctly displays my expected OATH pairs. I've found no problems reading from the Yubikey slots on Linux.

**Comment by emlun** [comment]
Thanks for the report. Is `pcscd` installed and running? If it is, could you please run the app with `--log-level DEBUG` and post the output here?

**Comment by modgethanc** [comment]
Installing `pcscd` did the trick! I didn't realize that was a dependency; did I miss that in the documentation somewhere?

Thanks for the help!

**Comment by dagheyman** [comment]
Good that you got it to work. Yes, the dependency on pcscd needs to be better documented for the AppImage.

**Comment by dagheyman** [comment]
This is documented in the README since a while back.
