### ISSUE TITLE
Have to run linux-patch-ccid in ubuntu

### ISSUE THREAD

**Issue by smiddy** [Yubico/yubioath-desktop#35]
It is great to have a ppa for ubuntu now! Thanks heaps!

Is it possible to change the packaging that the linux-patch-ccid is launched automatically? After this, the installation works.

**Comment by dainnilsson** [comment]
I'm not sure we want to do this. It seems a bit intrusive to me that the package itself would alter the configuration files of other software automatically.

**Comment by smiddy** [comment]
Hm, I see your point. Perhaps some kind of dialogue? I am thinking of my parents trying to install the package and I do not think they will get it...

**Comment by dagheyman** [comment]
Yubikeys are supported by libccid by default in Ubuntu since the 15.10 release (wiley).
Closing.
