### ISSUE TITLE
Binary Releases On Github Lag Behind Website

### ISSUE THREAD

**Issue by pauby** [Yubico/yubioath-desktop#361]
The Yubico Website at https://www.yubico.com/products/services-software/download/yubico-authenticator/ is showing 4.3.5 as available (I'm interested in Windows so that's what I'm looking at). However the Releases on GitHub only show source code release for 4.3.5.

This is causing issues trying to find the latest release for the Chocolatey package at https://chocolatey.org/packages/yubico-authenticator

Could you clarify where releases are published now and where they will in the future so I can adjust the automatic package updating?

Thanks.

**Comment by emlun** [comment]
Sorry for the confusion, the primary releases page is here: https://developers.yubico.com/yubioath-desktop/Releases/
