### ISSUE TITLE
option to hide dock icon

### ISSUE THREAD

**Issue by xortim** [Yubico/yubioath-desktop#37]
Adding an option to hide the dock icon in the various OS's would be ideal. This would allow it to work better with various workflows and needs. For example, I would like to have the app running on startup, but not have the window displayed immediately nor the dock icon shown unless the credentials windows is available; thereby keeping my dock and app switcher free of clutter.

**Comment by dainnilsson** [comment]
The dock icon is already only shown while the window is shown, is it not? Having the ability to not show the window on startup (#36) seems like it should satisfy your needs. Am I missing something?

**Comment by xortim** [comment]
Sorry for the confusion. I'm referencing the appearance of it in the dock itself. This would be in addition to #34. The icon in the dock is shown even when the application window is not shown. I would like the dock icon to only be shown when the credential window is displayed. When the window is closed the dock icon should be destroyed and accessing the application should be done through the system tray icon.

**Comment by dainnilsson** [comment]
So, what I think you're saying (please correct me if I'm wrong) is that on
OS X (?) the main windows icon is shown even when the window is closed to
the tray. This is not the behavior in Windows, nor in XUbuntu, which are
the OSes I currently have access to test this out on. The intended behavior
is that the icon is shown only when the window is shown. If I understood
you correctly, then that indicates a bug that affects the OS X version only
(?).

Sorry for the confusion. I'm referencing the appearance of it in the dock
itself. This would be in addition to #34
<https://github.com/Yubico/yubioath-desktop/issues/34>. The icon in the
dock is shown even when the application window is not shown. I would like
the dock icon to only be shown when the credential window is displayed.
When the window is closed the dock icon should be destroyed and accessing
the application should be done through the system tray icon.

—
Reply to this email directly or view it on GitHub
<https://github.com/Yubico/yubioath-desktop/issues/37#issuecomment-120459405>
.

**Comment by xortim** [comment]
You are correct in the summary of the issue, however it is affecting not just OS X. I can confirm that 
the dock icon is shown in the latest Ubuntu (with Unity) and OS X Yosemite

**Comment by dainnilsson** [comment]
Thanks. I'm replacing this issue with one that has a clearer subject: #38.
