### ISSUE TITLE
Adding new credential on MacOS Desktop and nothing happens

### ISSUE THREAD

**Issue by 3eph1r0th** [Yubico/yubioath-desktop#379]
- Yubico Authenticator version: 4.1.2
- Operating system and version: MacOS High Sierra 10.13.6
- YubiKey model and version: YubiKey 5C Nano
- Bug description summary: 

I bought YubiKey, installed Yubico authenticator and tried to add 2FA for one of the websites into Yubico authenticator. Each time i press "Add credential" button after choosing name and entering secret key, it closes window and shows again "No credentials found".

Authenticator mode is CCID (Smart Card). If I choose YubiKey Slots it works fine but only for 1 credential per slot.

**Comment by dagheyman** [comment]
Thanks for the repost. Could you try updating to version 4.3.5 and see if it helps?
