### ISSUE TITLE
Add controls to set "require touch" on entries

### ISSUE THREAD

**Issue by tamasd** [Yubico/yubioath-desktop#384]
I moved over all my entries from FreeOTP to Yubico Authenticator when I got my Yubikey 5. Recenly, I discovered that I can set "require touch" on entries when I add them, but I can't add them afterwards. I don't want to reimport everything, it would take a lot of time, but it would be nice if I could set just the "require touch" property on all entries.

**Comment by dagheyman** [comment]
Thanks for the report. There is no support in the firmware to in any way modify the credential after it have been written to the device, so the only way would be to re-import it.
