### ISSUE TITLE
Timeline not working on Fedora 30

### ISSUE THREAD

**Issue by xoxys** [Yubico/yubioath-desktop#396]
- Yubico Authenticator version: 4.3.5
- Operating system and version: Fedora 30
- YubiKey model and version: YubiKey 5C

The timeline which indicates remaining time before generation new TOTPs is also not working on Fedora 30 (does not decrease). Maybe this is also a wayland issue, I've opened this issue just for the record :)

**Comment by dagheyman** [comment]
Thanks for the report. Does version 5.0.0 (currently available as .AppImage here https://developers.yubico.com/yubioath-desktop/Releases/) work correctly?

**Comment by xoxys** [comment]
Awesome! Really nice job :) works like a charm and, by the way, the new design looks really nice :+1:

**Comment by dagheyman** [comment]
Great, closing.
