### ISSUE TITLE
Yubikey Neo-n it not detected on both my mac's

### ISSUE THREAD

**Issue by glnds** [Yubico/yubioath-desktop#40]
The application just says Insert a Yubikey...
The personalization tool correctly reports that my key is present.
FYI slot 2 of the key is not configured

I tried to run the  osx-patch-ccid script to solve the issues but the output tells me that everything was already setup correctly... (i've reboot the system as suggested in the documentation)
 
Secondly i ran:
brew install python
brew install pyside
pip install PyInstaller
pip install pycrypto
pip install pyscard
But since i installed the packaged version i assume this was not a necessity...

Could i enable any logging to find out more about the issue or do you have any clue how to solve this?

Thx!

**Comment by glnds** [comment]
I found the above issue, I had to install the Yubikey Neo Manager to enable CCID communication.
Since then the Yubikey is recoginized by the desktop authenticator.
But again i'm stuck.
The OSX interface looks a bit different from the one in the Documentation (window)
Currently i'm unable to add multiple keys, i have a File menu option but that doesn't provide me the expected functionallity....

**Comment by dainnilsson** [comment]
The application has two different "Add credential" dialogs: one for CCID based credentials, and one for slot-based ones. As the application is displaying the dialog for slot-based credentials it seems that it is not able to detect the OATH applet in your device. So the question becomes, why isn't it detecting it? And unfortunately I'm not sure as to what the answer to that one is. Does the YubiKey NEO Manager show "YubiOATH" as an available app for your NEO? Have you been able to use this functionality with the Android version of Yubico Authenticator over NFC?

**Comment by glnds** [comment]
I solved the issue, You only get the dialog for the CCID based credentials if you uncheck both Yubikey standard slot checkboxes.
Although most of the time I skip reading the manual i think it needs an update :)
