### ISSUE TITLE
Oath installation for windows in CMD

### ISSUE THREAD

**Issue by karthick-mani** [Yubico/yubioath-desktop#400]
I am trying to install Yubico Authenticator for Desktop in my organisation computers. 
Since the number of users targeted are more than 100, I am looking ahead for installation switches for executable to be installed through SCCM.
Target workstations are Windows 7 and Windows 10. Any suggestion or guidance are much appreciated.

- Operating system and version: Windows

**Comment by dagheyman** [comment]
I don't know much about SCCM, but you should be able to run the installer with the `/S` flag for silent install and optionally the `/D` flag for a custom directory.
```
$ yubioath-desktop-4.3.6-win64.exe /S /D=C:\Program Files\CustomFolder
```
