### ISSUE TITLE
Yubico Authenticator is stuck on "No YubiKey Detected" screen upon launch.

### ISSUE THREAD

**Issue by cwiemann** [Yubico/yubioath-desktop#419]
- Yubico Authenticator version: 4.3
- Operating system and version: Mac OS 10.12.6
- YubiKey model and version: Yubikey 4
- Bug description summary: Yubico Authenticator is stuck on "No YubiKey Detected" screen upon launch.

Steps to reproduce
---

Opened YubiKey Authenticator.

Expected result
---

I expected the app to function normally.

Actual results
---

Yubico Authenticator is stuck on "No YubiKey Detected" screen upon launch.

Other info
---

YubiKey Manager is al stuck on the "Insert your YubiKey" screen upon launch. Smart Card functionality is OK.

**Comment by itsaphel** [comment]
Same issue. After a while if you stay on that screen I see "Authenticator mode is set to CCID, but the CCID connection mode is not enabled."

Using 4.3.6b (upgraded from v4.3.5 to see if it'd help, it didn't). Yubikey was working fine a few days ago. It still works fine on my Windows PC with the same app for Windows (v4.3.5), just not on macOS.

**Comment by dagheyman** [comment]
Closing, macOS 10.12 is no longer supported for this app. Feel free to open new issues if problem persists on other macOS versions.
