### ISSUE TITLE
No installation on Kubuntu 18.10

### ISSUE THREAD

**Issue by RolandSM** [Yubico/yubioath-desktop#425]
Today my YubiKey5 arrived and i tried to install like described. But i only get:

`yubioath-desktop : Hängt ab von: python3-yubikey-manager (<= 3) aber 3.0.0~ppa1~cosmic1 soll installiert werden`

I installed pyton3-yubikey-manager and this works, version is 1.1.2 but when I try to install the Yubioath-Desktop this dependency is hera again...

**Comment by dagheyman** [comment]
Thanks for the report. I think the problem might be that we only release PPA packages for supported Ubuntu versions, and 18.10 is [end of life](https://wiki.ubuntu.com/Releases). Anything stopping you from upgrading to 19.04 ?

Alternatively you could also try the `.AppImage` found here: https://developers.yubico.com/yubioath-desktop/Releases/
