### ISSUE TITLE
Cannot clear cached password on PC authenticator (can on android's)

### ISSUE THREAD

**Issue by Morthawt** [Yubico/yubioath-desktop#438]
- Yubico Authenticator version: all
- Operating system and version: Windows 10
- YubiKey model and version: na
- Bug description summary: 
Save the TOTP password for your YubiKey and later decide to not have it remember it any more because you want to type it each time...
---
Expected result is on the menu it should say something like "Clear cached password"
---

**Comment by dagheyman** [comment]
This is now added on master, will be included in the next release.
