### ISSUE TITLE
Authenticator require root priviledge

### ISSUE THREAD

**Issue by JGoutin** [Yubico/yubioath-desktop#439]
- Yubico Authenticator version: 1.3.5 (Version from OS packages)
- Operating system and version: Fedora 30
- YubiKey model and version: Yubikey nano 5
- Bug description summary: 

The authenticator requires to be run as root to work properly.

Steps to reproduce
---

* Run `yubioath-desktop`, Authenticator show "No YubiKey Detected".
* Run  `sudo yubioath-desktop`, Authenticator work properly.

**Comment by dagheyman** [comment]
Thanks for the report! The app shouldn't require root permissions, but a udev rule is typically needed to be able to see the device. Since the fedora package is not maintained by us I would report it to fedora.

**Comment by tebruno99** [comment]
Having the same issue on Manjaro. I copied the 70-uf2.conf rule from Yubico's instructions and having this issue now.  All other apps work fine as normal user except yubioath-desktop

**Comment by tebruno99** [comment]
I have built from source and experiencing the same issue.  ykman oath code works fine but launching yubioath-desktop must be done with sudo to have the yubikey detected.

I have install the 70-u2f.conf in udev as the documentation states.
Yubico Authenticator Version:  Master branch 12/16/2019
Manjaro Linux KDE
Yubikey NFS 5

**Comment by tebruno99** [comment]
The logs appear pretty similar, both showing success for opening Yubikey 4 (Same for my Yubikey 5 NFC)
[user-log.txt](https://github.com/Yubico/yubioath-desktop/files/3969323/user-log.txt)
[sudo-log.txt](https://github.com/Yubico/yubioath-desktop/files/3969326/sudo-log.txt)

If the Yubikey is not in the USB port --log-level "DEBUG" only outputs:
`
2019-12-16T11:21:40-0600 INFO [ykman.logging_setup.setup:58] Initialized logging for ykman version: 3.1.0
`

**Comment by tebruno99** [comment]
I went all the way back to yubioath-desktop 4.3.5 and the issue does not occur.

**Comment by tebruno99** [comment]
Something is pretty weird. I went commit by commit until I found where it started requiring root.

Signal handling change at [pyotherside: fix for handling signals correct](https://github.com/Yubico/yubioath-desktop/commit/2dd9e0186e81e59351761260982f8da4c0a28b15) is where it started.

Master branch seems to have fixed it at #493 however now it is intermittent. It usually works but sometimes doesn't.

**Comment by gbcox** [comment]
I haven't noticed this issue on Fedora.  The current version on Fedora is:
yubioath-desktop-5.0.1-2.gitc58db92 since October 16, 2019.

**Comment by tebruno99** [comment]
This is actually fixed upstream Arch Linux in v 5.0.1-2.  This just hasn't made it down to Manjaro yet.

**Comment by emlun** [comment]
Thanks @tebruno99 for investigating!

@JGoutin could you post your `--log-level DEBUG` output, with and without root privileges, so we can confirm if your issue is a duplicate of the signal handling issue? On my Arch machine, the UI on commit 2dd9e0186e81e59351761260982f8da4c0a28b15 remains at "Insert your YubiKey" both with and without sudo.

**Comment by JGoutin** [comment]
With packages:
yubikey-manager.noarch  3.0.0-7.git1f22620.fc31                                                             
yubioath-desktop.x86_64 5.0.1-2.gitc58db92.fc31       

The issue is still existing. 

Output when running: `yubioath-desktop --log-level DEBUG`
```
Unhandled PyOtherSide error: Cannot import module: yubikey (Traceback (most recent call last):

  File "qrc:///py/yubikey.py", line 8, in <module>
    import ykman.logging_setup

ModuleNotFoundError: No module named 'ykman'
)
Unhandled PyOtherSide error: Function not found: 'yubikey.init_with_logging' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
Unhandled PyOtherSide error: Function not found: 'yubikey.controller.check_descriptors' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
Unhandled PyOtherSide error: Function not found: 'yubikey.controller.get_connected_readers' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)

....
```

I does not have this issue when using the AppImage  version.

**Comment by emlun** [comment]
Thanks!

`ModuleNotFoundError: No module named 'ykman'` suggests this might be an issue with the PYTHONPATH. Does the following code run successfully in a Python shell?

```
import ykman
print(ykman.__version__)
```

**Comment by JGoutin** [comment]
Ok, I found what was wrong. There was a residual virtualenv that blocked system packages loading.
