### ISSUE TITLE
gpg sig doesn't match

### ISSUE THREAD

**Issue by jmichel359** [Yubico/yubioath-desktop#440]
Hi

I've just downloaded yubioath-desktop-5.0.0-linux.AppImage from https://developers.yubico.com/yubioath-desktop/Releases/ page and when I `gpg2 --verify yubioath-desktop-5.0.0-linux.AppImage.sig`, I get an error saying there's no public key for 59944611C823D88CEB7245B906FC004369E7D338.

So I search for it with `gpg2 --no-default-keyring --keyring vendors.gpg --keyserver pgp.mit.edu --recv-key 69E7D338` and I get no data for it.

I've seach too on the https://developers.yubico.com/Software_Projects/Software_Signing.html page, but this key isn't there.

**Comment by dagheyman** [comment]
Hi, thanks for the report.

The key listed is correct, but it is the master key and the signature is done with the subkey.

Could you try this:

```
gpg --recv-keys F4AB24C3
gpg --verify yubioath-desktop-5.0.0-linux.AppImage.sig
```

**Comment by dagheyman** [comment]
Great. Yes, I'll look into that (you are not the first person asking about this).

**Comment by sunknudsen** [comment]
Hi @dagheyman, relieved to have found this thread.

I tried searching for Yubico’s signing keys on DuckDuckGo but failed.

Tails, for example, publishes their signing key at https://tails.boum.org/tails-signing.key which is convenient.

Where can I find yours? In my past experiences, it’s pretty standard for organizations to publish their signing key on their official website. We can them use a web of trust model to mitigate man-in-the-middle attacks.

Thanks!
