### ISSUE TITLE
Github appears to be missing releases

### ISSUE THREAD

**Issue by aureq** [Yubico/yubioath-desktop#447]
- Yubico Authenticator version: n/a
- Operating system and version: n/a
- YubiKey model and version: n/a
- Bug description summary: 

I saw #361 and it's ok if binaries aren't published on Github, but people like me use Github as a way to be notified of new releases. I actually watch this repository to know when a new release is available so I can update the app in a timely manner.

Could Yubico and the dev team consider publishing new releases on Github as described [here](https://help.github.com/en/articles/creating-releases) please? This way repo subscribers will be aware of new versions.

Thank you.

**Comment by dagheyman** [comment]
Thanks for the report, we'll consider it, (even though I was quite happy with not putting the release notes in two places). Would the RSS feed work as an alternative? https://developers.yubico.com/yubioath-desktop/Releases/atom.xml

**Comment by aureq** [comment]
Thank you @dagheyman. I wasn't aware of the RSS feed. I think RSS and GH releases work in pair IMHO. I like GH sending a notification email when a new release is published so I'm sure not to miss out. I use RSS feeds for general news articles. But that's a personal opinion.

Thank you for considering @dagheyman

**Comment by dagheyman** [comment]
Published a release for 5.0.1, we'll go back to using that.

**Comment by aureq** [comment]
Awesome @dagheyman It worked like a charm and I already upgraded. Thanks a lot.
