### ISSUE TITLE
OS X window management

### ISSUE THREAD

**Issue by pelme** [Yubico/yubioath-desktop#46]
The OS X window management does not work as expected.

1. Have Yubico Authenticator open
2. Double click on a code to have it copied to clipboard
3. The title bar gets weird:
![image](https://cloud.githubusercontent.com/assets/20529/9466202/5d792288-4b33-11e5-854d-73446f88bb7f.png)
4. Clicking on the Dock icon or cmd+alt switching to the Yubico Authenticator does not bring the program to the front. Using the tray icon+show credentials the window will show back up and work.

**Comment by pelme** [comment]
I'm currently running OS X 10.10.4, Yubico Authenticator 2.2.1 (but the problem has been there at least in the previous release too)

**Comment by pelme** [comment]
The first issue I originally reported is no longer a problem so I changed the issue description.

The issue described is still an issue on OS X El Capitan 10.11 and Yubico Authenticator 2.3.0. 

I love the idea of the Yubikey but this makes the experience using the Yubikey on OS X quirkier and weirder than it needs to be.

Have you been able to reproduce this problem? Do you need any other information?

**Comment by dainnilsson** [comment]
Thanks for the updated description, yes I can reproduce it. This will need some investigation to determine if it's a bug in Qt4 or the app, and if there's a way to work around it.
