### ISSUE TITLE
Stop messing up mouse wheel scrolling

### ISSUE THREAD

**Issue by teozkr** [Yubico/yubioath-desktop#463]
- Yubico Authenticator version: 5.0.0
- Operating system and version: Arch Linux, up to date
- YubiKey model and version: NEO 3.5.0, not that it's relevant here
- Bug description summary: The new smooth scrolling that was added in 5.x is just a horrible idea

Steps to reproduce
---

1. Have a decent number of OATH tokens (15-20 should do)
2. Use the scroll wheel to scroll to a token in the middle of the list

Expected result
---

The list stops moving and I can pick the entry that I want, and go on with my day.

Actual results
---

The scroll keeps on coasting, and quickly reaches the end of the list.

Other info
---

*Please* stop reinventing basics like scrolling. It's there, and it works. Unless you actively screw it up.

**Comment by dagheyman** [comment]
Thanks for the report! We'll look into it.

**Comment by dagheyman** [comment]
5.0.2 have some improvements to the scrolling, it should behave more predictable now.
