### ISSUE TITLE
Default action of tray icon has been removed

### ISSUE THREAD

**Issue by alangrainger** [Yubico/yubioath-desktop#468]
- Yubico Authenticator version: 5.0.0
- Operating system and version: Windows 10 1903
- YubiKey model and version: 5C Nano
- Bug description summary: 

The system tray menu does not have a default action, so double-clicking on the tray icon does nothing:

![Image of tray menu](https://i.imgur.com/HDl43mw.png)

This has changed from 4.x where there was a default action so show the Authenticator window.

Steps to reproduce
---

Double-click the tray icon.

[Please explain what you did when the bug appeared, and if and how you have been
able to reproduce it.]

After upgrading to 5.0.0 the feature was removed.

**Comment by dagheyman** [comment]
Thanks! We'll look into re-adding this.

**Comment by dagheyman** [comment]
This have been re-added in 5.0.1.
