### ISSUE TITLE
⌘-C no longer works on macOS, as of v5

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [Yubico/yubioath-desktop#482]
- Yubico Authenticator version: 5.0.1 (🍾)
- Operating system and version: macOS 10.15 "Catalina"
- YubiKey model and version: USB-C
- Bug description summary: 

Steps to reproduce
---

As of upgrading to 5.0.1 today, my workflow of quickly copying the codes no longer seems to work:

1. launch the app (⌘␣yubi⏎)
2. without clicking or hitting any keys, start to type the name of a site or application (⌘␣yubi⏎discor)
3. hit return when correct application is the only one visible (⌘␣yubi⏎discord⏎)
4. touch YubiKey to authorize generation
5. ⌘C to copy the generated code, for pasting into app/website (⌘␣yubi⏎discord⏎<TOUCH>⌘c)

Expected result
---

Equivalent behaviour to <v5; receiving an auth-code onto my system clipboard

Actual results
---

Code is generated, but is not copied to clipboard

Other info
---

This is obviously not a huge blocker. But having to move my mouse up and double-click the generated code to copy it (perhaps this is a Windows-ecosystem pattern?) was an unfamilar and unexpected change, for me. Whenever you could get to it, that'd be swell; but it's no big deal. (=

All the other changes are 🅰️ ➕ though! I'd kinda thought this app was gonna lay forgotten and dead, so I'm extremely happy to see that it's still a first-class, supported use-case for the YubiKey! Keep up the good work!

**Comment by braathen** [comment]
Thanks for the report and the nice words... :)

I've confirmed the behaviour you're describing, we will look into why it happens and it should hopefully be fixed in the next version. The expected behaviour is that the code will be copied in step 4, so no need for cmd-C after touch.

**Comment by dagheyman** [comment]
This is fixed on the master branch and will be included in the next release.
