### ISSUE TITLE
Remove "Delete account" from context menu

### ISSUE THREAD

**Issue by DaveMiddleton** [Yubico/yubioath-desktop#484]
- Yubico Authenticator version: 5.0.1
- Operating system and version: Windows 10 Pro 64-bit 1903 build 18362.418
- YubiKey model and version: 4 version 4.3.4
- Bug description summary: Remove "Delete account" from context menu

Steps to reproduce
---
Right-click in the Yubico Authenticator to access the context menu. "Delete account" is just below "Copy to clipboard" and second from the top of the menu, and can be accidentally clicked instead of the Copy command.

[Please explain what you did when the bug appeared, and if and how you have been
able to reproduce it.]
The issue is: "Delete account" it is too close to the main task i.e. copy the OTP to the clipboard. It is too easy to accidentally click "Delete account" and get into the delete account process. It is an usability issue. It's like driving a car with an ignition button next to the accelerator; every time I copy an OTP using the context menu I really have to pay attention not to accidentally get into an account deletion process.

Expected result
---
Separation of the "Copy to clipboard" from the "Delete account" task.

[What did you expect to happen when you did the above?]

Actual results
---

[What actually happened?]

Other info
---
Most of the time I use the Crtl-C command as to avoid the context menu.

[Anything else you would like to add?]
This is not a bug report, but an (usability) enhancement. 

The "Delete account" function can be moved e.g. into the top menu of the Authenticator application next to the "i" and "+" button. If the "Delete account" button is pressed one should be able to either cancel the task or select an account and confirm its deletion.

**Comment by dagheyman** [comment]
Thanks for the feedback! We'll look into improving this, I definitively understand the issue.

**Comment by dagheyman** [comment]
This is now fixed on the master branch, with a separator in the context menu before the delete account option. There is also a pretty scary confirmation prompt if the action is selected.
