### ISSUE TITLE
Icon/Button to clear previous search terms

### ISSUE THREAD

**Issue by icawebdesign** [Yubico/yubioath-desktop#486]
- Yubico Authenticator version: 5.0.1
- Operating system and version: All
- YubiKey model and version: N/A
- Feature request summary:

Please add a 'clear' icon/button in the search field to easily/quickly be able to remove any previous search chars that have been added.

Steps to reproduce
---

Use the search feature for an entry.. go back to the app and search for another entry.. you need to clear the previous entry either with the backspace/delete key, select-all and delete, etc.

Expected result
---

Having a button/icon to have a 1-click (and possibly keyboard shortcut assigned) solution to remove previous search terms.

This is not a bug report, everything works as designed, but a UX feature request.

**Comment by braathen** [comment]
Thanks for the input, I see your point and will think about what we can do. Just FYI escape will clear the input, but it will also move you away from the search field, so not exactly what you want.

**Comment by icawebdesign** [comment]
@braathen thanks for that tip.. it would work as a temp solution (esc > ctrl+f quicker than manual deletion) for now :)

**Comment by braathen** [comment]
actually, I can save you from that ctrl-f as well, just start typing and search will get focus... :)

having thought about this a bit I think we'll look into adding a clear button on the textfield(s) where appropriate. I have not been able to find something of a "standard shortcut" for clearing an input field though.

**Comment by icawebdesign** [comment]
@braathen Thanks for the additional tip.. I'll try that tomorrow when I have my Yubikey with me =)

Thanks also for looking into adding a clear button. I also agree in that I don't know of a "standard" shortcut for clearing a text field.. was more thinking aloud of general possibilities (I know some people prefer/need to use a keyboard more than a mouse/trackpad for various reasons).. but I think tbh, with a button and the esc > start typing functionality, it would have both cases potentially covered.

**Comment by fdennis** [comment]
After some discussion we have decided to not implement a "clear" button, since pressing the "esc" button work just as well. In other words, the "esc" key is a clear button already.
