### ISSUE TITLE
No systray icon under KDE Plasma5

### ISSUE THREAD

**Issue by jtyr** [Yubico/yubioath-desktop#49]
There is no systray icon visible under KDE Plasma5. Plasma5 started to use a _status notifier item_ instead of the _xembed_. More details are [here](http://blog.martin-graesslin.com/blog/2014/06/where-are-my-systray-icons/).

**Comment by dagheyman** [comment]
On a fresh install of Kubuntu with KDE Plasma 5.5.5 I can see a systray icon.
