### ISSUE TITLE
Package yubioath-desktop 4.3.5~ppa1~cosmic1: Dependency on python3-yubikey-manager not updated

### ISSUE THREAD

**Issue by leeps** [Yubico/yubioath-desktop#490]
- Operating system and version: Ubuntu 18.10 Cosmic Cuttlefish
- Bug description summary: PPA Package "yubioath-desktop" in version 4.3.5\~ppa1~cosmic1 has a dependency on python3-yubikey-manager in version <=3.0.0 that cannot be satisfied from the PPA
- refer to #261 

Steps to reproduce
---
```
# add-apt-repository ppa:yubico/stable
 PPA for stable Yubico software.
 More info: https://launchpad.net/~yubico/+archive/ubuntu/stable
Press [ENTER] to continue or Ctrl-c to cancel adding it.

Hit:1 http://de.archive.ubuntu.com/ubuntu cosmic InRelease
Hit:2 [removed private repo entry]
Hit:3 http://ppa.launchpad.net/mkusb/ppa/ubuntu cosmic InRelease
Hit:4 http://de.archive.ubuntu.com/ubuntu cosmic-security InRelease
Hit:5 http://de.archive.ubuntu.com/ubuntu cosmic-updates InRelease
Get:6 http://ppa.launchpad.net/yubico/stable/ubuntu cosmic InRelease [15,4 kB]
Hit:7 http://linux.teamviewer.com/deb stable InRelease
Hit:8 https://updates.signal.org/desktop/apt xenial InRelease
Get:9 http://ppa.launchpad.net/yubico/stable/ubuntu cosmic/main amd64 Packages [4.808 B]
Get:10 http://ppa.launchpad.net/yubico/stable/ubuntu cosmic/main Translation-en [2.512 B]
Fetched 22,7 kB in 1s (27,0 kB/s)
Reading package lists... Done
# apt-get install yubioath-desktop
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 yubioath-desktop : Depends: python3-yubikey-manager (<= 3) but 3.0.0~ppa1~cosmic1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

Expected result
---

Can install yubioath-desktop from PPA.

Actual results
---

Cannot install yubioath-desktop from PPA.

**Comment by fdennis** [comment]
Hi,
Have you tried the [latest ](https://developers.yubico.com/yubioath-desktop/Releases/) version (5.0.1)?
The latest version of Yubico Authenticator is version 5.0.1, which is released as an AppImage for Linux. We are currently looking into other distribution formats.

**Comment by leeps** [comment]
I have not.

The PPA exists. If it's not supported anymore, I suggest removing it.
It's not a good idea to keep it around when it's either broken or unsupported.

**Comment by MatthiasLohr** [comment]
@leeps, I fully aggree!

Maybe the community can take over managing a PPA?

**Comment by leeps** [comment]
I don't expect anything to come from this, @MatthiasLohr. I've since switched distributions and use version 5.x now.
