### ISSUE TITLE
Rikard Braathen PGP key not listed in developers.yubico.com

### ISSUE THREAD

**Issue by Maryse47** [Yubico/yubioath-desktop#492]
[Rikard Braathen](https://github.com/braathen) PGP key isn't listed in https://developers.yubico.com/Software_Projects/Software_Signing.html . Please add his credentials there among other developers.

**Comment by braathen** [comment]
Thanks for looking after me... :)
We're usually only listing PGP keys on that page for people who are signing software releases, for commits you can tell from GitHub that they're verified.
