### ISSUE TITLE
Allow to change order

### ISSUE THREAD

**Issue by ai** [Yubico/yubioath-desktop#504]
- Yubico Authenticator version: 5.0.1
- Operating system and version: Fedora 31
- YubiKey model and version: YubiKey 5C
- Bug description summary: allow to change the order of keys

Some keys are much often used than others. For instance, I need TOTP keys for npm every week to make a release.

It will be nice to change the order of keys and put some on the top.

If YubiKey can’t allow changing the order, it will be OK to change the order only locally.

**Comment by dagheyman** [comment]
Hi, thanks for the report. This is actually possible, just mark the most used credentials as "favorite" (click to select, press star in top menu), and they will be pinned in top of the list.

As you hinted at, these favorites are only stored locally on the computer, not on the device itself.

**Comment by ai** [comment]
Yeap, it was exactly what I looked for 😍. Seems like I missed it.
