### ISSUE TITLE
Add Flatpak package

### ISSUE THREAD

**Issue by ai** [Yubico/yubioath-desktop#506]
[Flatpak](https://flatpak.org/) is a new way to deliver software to Linux users. It is a single format to all distros with app isolation and easy updates.

GNOME, RedHat/Fedora and Intel promote Flatpak. For instance, it is the only way to distribute an application for Fedora Silverlight. Some GNOME applications (like [Fragments](https://gitlab.gnome.org/World/Fragments)) supports only Flatpak as a way to install them. There are already Flatpak packages for Atom, GIMP, Slack. With [a few extra steps](https://flatpak.org/setup/Ubuntu/), it can be used in many different Linux distros including Ubuntu, Debian or ArchLinux.

It will be nice to have this desktop app on [Flathub](https://flathub.org/home).

Ubuntu has Flatpak support too, but they promote another package format Snap. If your releasing CI is flexible, it will be nice to support both Flatpak and Snap.

Of course, we can remember famous [xkcd’s Standards](https://xkcd.com/927/) here, but Flatpak/Snap looks really like a future way of software distribution in Linux and supporting just 2 packages will be much easier than we need to support today.

**Comment by dagheyman** [comment]
We (Yubico) currently won't commit to maintaining a Flatpak, however, there is a community effort going on here: https://github.com/flathub/flathub/pull/1126

**Comment by ai** [comment]
Done, We added the app package to the Flathub repository https://flathub.org/apps/details/com.yubico.yubioath

@dagheyman do we need to add the link to Yubico Authenticator docs? Some “Non-official packages” list?

**Comment by dagheyman** [comment]
@ai Great! Closing this then. No, I think we are fine on docs, will update the URL mentioned in the other issue.
