### ISSUE TITLE
Detect NEO's with CCID disabled

### ISSUE THREAD

**Issue by minisu** [Yubico/yubioath-desktop#51]
CCID is disabled by default on NEO's. This can cause confusion for users of Yubico Authenticator.

Yubico Authenticator should detect that a NEO without Smart Card communication is inserted (and give the user an option to enable it). Since some users might want to just use the OTP slots (not enable CCID), there should be a _"Don't show this again"_ checkbox in the dialog window.

See [this forum topic](http://forum.yubico.com/viewtopic.php?f=26&t=2021) for discussion.

**Comment by SueHeim** [comment]
At the very least, at least display a message that CCID needs to be enabled, and to advise the user to use the NEO Manager app to enable it. Right now, there is no way to know what to do (or remember that you need to do this). This might be a short term fix?
