### ISSUE TITLE
[SOLVED] yubioath-desktop 5.0.1-2 (Arch Linux) won't detect my Yubikey 5 NFC!

### ISSUE THREAD

**Issue by ABOhiccups** [Yubico/yubioath-desktop#514]
- Yubico Authenticator version: 5.0.1-2
- Operating system and version: Arch Linux 4.19.95-1-lts
- YubiKey model and version: YubiKey 5 NFC
- Bug description summary: yubioath-desktop won't detect YubiKey 5 NFC after plugin.

**Comment by emlun** [comment]
Thanks for the report. Is the `pcscd` service running?

**Comment by ABOhiccups** [comment]
No. But, I enable it now. It works! Thank you! :)
