### ISSUE TITLE
Use SVG icon in GNOME

### ISSUE THREAD

**Issue by ai** [Yubico/yubioath-desktop#518]
- Yubico Authenticator version: 5.0.1
- Operating system and version: Fedora 31
- Bug description summary: App uses 128×128 PNG icon in Linux. The icon looks blurry on modern HiDPI screens.

Steps to reproduce
---

1. Install app
2. Open GNOME Shell apps list

Expected result
---

Hi-res icon in apps list

Actual results
---

Blurry icon

Other info
---

I can make PR when my [another icon PR](https://github.com/Yubico/yubioath-desktop/pull/519) will be merge

**Comment by ai** [comment]
Seems like we need to replace `.png` to `.svg` in this line

https://github.com/Yubico/yubioath-desktop/blob/master/debian/yubioath-desktop.install#L2

I checked my `/usr/share/pixmaps` and found SVG files there. Seems like modern Linux systems support SVG icons.

**Comment by dagheyman** [comment]
Sounds good, PR welcome.
