### ISSUE TITLE
Systray Icon in Xubuntu 15.10 Beta2 Super Big

### ISSUE THREAD

**Issue by drohm** [Yubico/yubioath-desktop#53]
The systray icon in Xubuntu 15.10 Beta 2 is super big:

![xubuntu15 10beta2_systray](https://cloud.githubusercontent.com/assets/184959/10184354/8fb41bee-6709-11e5-9ea9-60dae4c06520.png)

This behavior only started today, it was fine after I first installed the application.  I'm not sure what changed or how to get it back to normal size.

**Comment by drohm** [comment]
Is there any way I can reset the icon or scale it down?

**Comment by dainnilsson** [comment]
I've never seen this before, and I use Xubuntu 15.04 myself. I haven't tried 15.10, but since it's a beta it might still have bugs.

**Comment by dainnilsson** [comment]
I just tested installing this on Xubuntu 15.10 (final), so I assume it was just something in the beta. Closing the issue.
