### ISSUE TITLE
Release appdata.xml

### ISSUE THREAD

**Issue by ai** [Yubico/yubioath-desktop#535]
I found that recently added `resources/com.yubico.yubioath.appdata.xml` are missed at https://github.com/Yubico/yubioath-desktop/archive/yubioath-desktop-5.0.2.tar.gz

Can you release a new version with AppData, I need ti for Flatpak release.

**Comment by ai** [comment]
@dagheyman sorry, seems like we need a release

**Comment by dagheyman** [comment]
Yes, it was merged after the release of 5.0.2. The file will be included in the next release, but no ETA for that currently.
