### ISSUE TITLE
Windows Desktop Not Working

### ISSUE THREAD

**Issue by WPCMSNinja** [Yubico/yubioath-desktop#54]
So when I use the Windows Desktop version it doesn't give me the proper code, yet when I take the Yubikey Neo out and use it on my Android Phone it gives me the proper code.  Any ideas?

**Comment by minisu** [comment]
Does the dekstop version give you any code at all?

**Comment by WPCMSNinja** [comment]
It does give me codes but the codes dont match up.

**Comment by WPCMSNinja** [comment]
Mind you I didn't use the desktop version to sync originally, would that cause the mismatch of codes?  I would hope that you would be able to rely on the yubikey to keep them compatible.

**Comment by dainnilsson** [comment]
As the Android version is generating the correct codes it seems that the credential is correctly stored on your phone. It sounds to me like your computers clock is off. TOTP relies on a clock that is correct to within 30 seconds, if it's off from that you'll get outdated or not yet valid codes.

**Comment by WPCMSNinja** [comment]
That would be it, I manually synced my time to that of NIST as the auto syncing was more than a minute off.  Thank you for your help.
