### ISSUE TITLE
Enhancement: add option during password set/reset to also require touch to unlock.

### ISSUE THREAD

**Issue by brendanhoar** [Yubico/yubioath-desktop#57]
I see from the source code that slot-based TOTP/HOTP credentials can be set to require a physical touch to unlock.

I propose adding such an option for applet-based credentials as well.

Currently, in order to unlock the applet-based OTPs, one must only enter the password. By default, this leaves the applet open and generating valid TOTP codes until the user remembers to quit the app or remove the key. Under some circumstances, it would be considered more secure to require a physical interaction for each set of codes generated. The application would continue caching the password but require a physical touch for each TOTP generation request. I understand there are some time-window issues that would need to be addressed carefully for a good user experience, of course.

If this feature would also require changes to the YubiOATH applet, I still think it's worth considering for adding the feature even if it only supported future NEO models.

**Comment by brendanhoar** [comment]
Alternate proposals: 

1. Add a setting for max number of retries before discarding the password and asking again.

2. Add a setting for max number of retries before discarding the password and then minimizing (or exiting).

It's really way too easy to leave it running for hours/days without noticing...which I keep doing. :)

**Comment by dainnilsson** [comment]
I think the non-applet changes have been addressed in #58. As for the initial proposal: The YubiKey 4 now supports requiring touch per code for individual credentials.
