### ISSUE TITLE
wrong versioning in 5.0.3 msi installers

### ISSUE THREAD

**Issue by mirostauder** [Yubico/yubioath-desktop#571]
- Yubico Authenticator version: 5.0.3
- Operating system and version: Windows
- YubiKey model and version: any
- Bug description summary: msi installer 5.0.3 uses wrong version - 5.0.2

- Steps to reproduce:
install using msi installer - yubioath-desktop-5.0.3-win32.msi
look at registry
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{24AB3148-963B-4FB9-A507-322E09F7447C}

- Expected result:
DisplayVersion = 5.0.3

- Actual results:
DisplayVersion = 5.0.2

- Other info:
similar result with yubioath-desktop-5.0.3-win64.msi
exe installers are unavailable

**Comment by dagheyman** [comment]
Thanks for the report, this was an oversight on our part when doing the release. Will be fixed in the next release. Does it affect you in anyway besides the wrong version being reported?

**Comment by mirostauder** [comment]
Update and Inventory management tools will report wrong version,
and suggest and/or try to deploy an update.

**Comment by dagheyman** [comment]
This should be fixed for the 5.0.4 version.
