### ISSUE TITLE
Desktop client for Mac no longer remembers window position

### ISSUE THREAD

**Issue by edelstone** [Yubico/yubioath-desktop#574]
- Yubico Authenticator version: 5.0.3
- Operating system and version: MacOS 10.15.4
- YubiKey model and version: 5C Nano
- Bug description summary: Just downloaded the 5.0.3 release. I typically have my authenticator window about 300px wide, height at maximum, and justified entirely to the left of my screen. Every time I open the app, the window insists on being re-positioned to the center of the screen. I deleted and reinstalled 5.0.3 and the problem persists. Reverted back to 5.0.2 and the problem is gone.

Steps to reproduce
---
1. Download 5.0.3
2. Reposition window to some other place than fully centered
3. Quit app
4. Restart app and window will be centered again

Expected result
---
Expected that window position would be remembered.

Actual results
---
Window position was not remembered.

Other info
---
N/A

**Comment by dagheyman** [comment]
Thanks for the report, we'll look into why this happens. Is this on a multi monitor setup or just on a laptop?

**Comment by edelstone** [comment]
Just on the laptop @dagheyman. I have multiple desktop "spaces" set up, but no additional monitors.
