### ISSUE TITLE
Metainfo file has faulty and wrong links to set the Flathub ones

### ISSUE THREAD

**Issue by EchedeyLR** [Yubico/yubioath-desktop#582]
Referenced here: https://github.com/flathub/com.yubico.yubioath/issues/1 

> Me commented
> The website link is pointing to the "Issues" manager (to create a new ticket to be exact) and seems that any other link was added.
> 
> Check at the bottom of the following image to see the preview link in which the button will redirect an user.
> ![Captura de pantalla de 2020-04-27 20-24-58](https://user-images.githubusercontent.com/56733813/80413990-3dce7a00-88c8-11ea-9f8a-e06fa2610f39.png)

>  bilelmoussaoui commented
> 
> This comes from the upstream metainfo file https://github.com/Yubico/yubioath-desktop/blob/master/resources/com.yubico.yubioath.appdata.xml#L11 and should be fixed there.

**Comment by ai** [comment]
I think we will have the same confusion behavior in Snap and other catalogs.

**Comment by dagheyman** [comment]
Thanks, yes, this should probably just be a link to yubico.com. Will fix.

**Comment by EchedeyLR** [comment]
> Thanks, yes, this should probably just be a link to yubico.com. Will fix.

Don't forget that other links are also needed. This report was not just to solve that wrong link but also to point that other links like that one to the "issues manager" should be too separated.
