### ISSUE TITLE
Theme doesn't really change to dark when using "System default" theme option.

### ISSUE THREAD

**Issue by elboletaire** [Yubico/yubioath-desktop#587]
- **Yubico Authenticator version:** 5.0.3
- **Operating system and version:** Windows 10 Pro and Ubuntu 20.04 (both up to date)
- YubiKey model and version: doesn't matter.
- Bug description summary: Under the settings, the "theme" comes by default to "System default". My system, both in linux and windows, is set to use dark themes, which should display the app in its dark theme.

Steps to reproduce
------------------

1. Set your system colors to dark.
2. Open yubioath desktop.

Expected result
---------------

To see yubico authenticator in its dark theme, 

Actual results
--------------

Yubico stays in its light theme when set to "System default".

![imatge](https://user-images.githubusercontent.com/153305/80536860-59f31980-89a3-11ea-9ac6-0fbea892cde1.png)

Other info
----------

AFAIK under linux this can be complicated, I'm not really sure the system knows if the theme is "dark" or "light", but windows only has two options, so either this should be working, or there shouldn't be no "System default" option, which can be misleading.

**Comment by elboletaire** [comment]
Ok I see that for linux was already noticed here #507, close this one if this isn't needed (although I don't see one for windows).

**Comment by fdennis** [comment]
This seems to be a bug in Qt. We have reported the issue to them. Thank you for finding this.
