### ISSUE TITLE
Possible desktop video latency issue

### ISSUE THREAD

**Issue by Caveman8080** [Yubico/yubioath-desktop#588]
- Yubico Authenticator version: 5.0.3 (Both x64 standalone and Microsoft Store app)
- Operating system and version: Windows 10 Build 19041.208
- YubiKey model and version: YubiKey Neo
- Bug description summary: When the Yubico Authenticator is in the foreground, there is a noticeable bit of latency on the desktop in relation to video rendering. This was tested with the FPS counter from the Google Chrome developer tools. 

Testing a monitor with a refresh rate of 60Hz, on a Nvidia 1080 Ti, and the latest drivers:
-Authenticator app in the background: Average of 57 FPS.
-Authenticator app in the foreground: Average of 29 FPS.

I do not have another computer to test this on.
Happens with both standalone and Microsoft Store app.
My hypothesis is that there is something in the Nivida drivers or setting that is causing the Authenticator app to only render at 30 FPS.

**Comment by dagheyman** [comment]
Thanks for the report! My guess would also be that it is related to the video drivers somehow. You could try running the app with the environment variable `QT_OPENGL` set to `software` or `angle` and see if it makes a difference.

**Comment by Caveman8080** [comment]
Thanks for the reply. You were able to help me find the problem.

I fix the latency issue by changing the following settings in the NVIDIA Control Panel.

1. Change 3D Setting to "Use the advanced 3D image settings"
2. In the Manage 3D settings, select "OpenGL rendering GPU" and change from "auto-select" to your video card.
3. Apply and restart the app.

Don't ask me why that fixed it, but it did.
