### ISSUE TITLE
Fix .net framework requirements for > Win7 versions. 

### ISSUE THREAD

**Issue by dorvan** [Yubico/yubioath-desktop#59]
Fix .net framework requirements for > Win7 versions. 
it's impossible to set-up in a win10 environment, because the .NET 3.5 dep it's blocking.

check of .net framework ok (4.x), version install fails.

**Comment by dainnilsson** [comment]
What do you mean? There's no use of .NET in this project.

**Comment by dorvan** [comment]
I've posted here, because I've followed the link on the "application for otp logon in windows" on yubico site. The setup requires at lease 3.5 and check green flag on win10 as "OK" but during resut try to download the 3.5 version from internet stopping the setup.

**Comment by dainnilsson** [comment]
I have no idea what you're talking about.
