### ISSUE TITLE
Ubuntu PPA has no yubioath-desktop for Eoan

### ISSUE THREAD

**Issue by LDVSOFT** [Yubico/yubioath-desktop#591]
- Yubico Authenticator version: _Unapplicable_
- Operating system and version: Ubuntu 19.10 Eoan
- YubiKey model and version: _Unapplicable_
- Bug description summary: Ubuntu PPA has no yubioath-desktop app built.

Steps to reproduce
---

* Follow [PPA guide](https://support.yubico.com/support/solutions/articles/15000010964-enabling-the-yubico-ppa-on-ubuntu) on adding Yubico repository.
* `apt-get update`
* `apt-get policy yubioath-desktop`

Expected result
---

You can see package being available

Actual results
---

There isn't one.

Other info
---

Looks like PPA version for other distros is outdated a bit too.

**Comment by dagheyman** [comment]
Hi, we need to improve the documentation on this, but this application is no longer available through the PPA. 

The version we publish is the Snap version, and that should be available in the snap store. There is also a native Debian/Ubuntu package maintained by third parties, which I believe will be available in Ubuntu 20.04

**Comment by guntbert** [comment]
Hey @dagheyman, may i ask **when** you are going to update the documentation? (and closing this issue doesn't improve visibility either :frowning_face: )

**Comment by LDVSOFT** [comment]
For anyone wondering: `yubioath-desktop` is provided in _universe_ Ubuntu repository.

**Comment by guntbert** [comment]
@LDVSOFT not for eoan/19.10
