### ISSUE TITLE
Incomplete Theme Yields Inconsistend Light - Dark Theme Changes

### ISSUE THREAD

**Issue by fzcooper** [Yubico/yubioath-desktop#599]
- Yubico Authenticator version: 4.3.6
- Operating system and version: Linux mint 19.3 Cinnamon
- YubiKey model and version: 5
- Bug description summary: 
It looks like a single theme element has been missed when applying the dark theme. The account buttons appear to have a slight zebra-striping to the color to help accentuate them, but when changing to a dark theme (Mint-Y-Dark), every other button remains its original color. On my system, this is #292723 or rgb(233, 231, 227).

Steps to reproduce
---
Change themes to a dark theme, open Authenticator, and see that only half the buttons changed color.
Light Theme:
![Original_Light](https://user-images.githubusercontent.com/30929768/82011006-90c66200-9628-11ea-9b16-4a2c75fd7bb6.png)
Dark Theme:
![Default_Dark](https://user-images.githubusercontent.com/30929768/82011005-90c66200-9628-11ea-8fcb-cb735c51e7b9.png)
Dark Theme w/ custom qt5ct palette, darkened "Less bright" color:
![Custom_Dark](https://user-images.githubusercontent.com/30929768/82011004-902dcb80-9628-11ea-9e57-9b39e61f6624.png)

Expected result
---
Both button colors used for zebra striping will change to darker versions.

Actual results
---
Half of the buttons changed to a darker theme, while the other half remained bright. This caused the text on the bright buttons to be unreadable.

Other info
---
I don't know much about qt, but using qt5ct to edit the color scheme to create a custom color scheme and editing the palette's "Less bright" color, the zebra unchanging color can be made dark to suit the rest of the theme. I poked around the qml and source files trying to find something that would relate closely to the names I was seeing in qt5ct to test making changes directly, but couldn't identify something I'd expect to affect this.

**Comment by dagheyman** [comment]
Thanks for the report! However, we don't update the 4.X versions anymore. Do you have a way to test 5.0.4?

**Comment by fzcooper** [comment]
Ah, I didn't realilze the PPA was so far behind. I'll get the AppImage after work and see how it performs.

**Comment by fzcooper** [comment]
Linux package management is becoming a nuisance. So, neither the AppImage nor the snap match the system theme at all in 'System Default' option, but it has an option to switch to a dark theme and that works fine. I made a Microsoft account and test-ran adding MFA to the keys, and it seems like the AppImage works well while the snap wouldn't see my key, so maybe that's another bug, but for theming I am happy. :)

Thanks.
