### ISSUE TITLE
Flatpak missing dependency 

### ISSUE THREAD

**Issue by andmalc** [Yubico/yubioath-desktop#606]
- Yubico Authenticator version: 5.0.4 installed from Flatpak
- Operating system and version:  Fedora Workstation 32 and Silverblue 32
- YubiKey model and version: 5 NFC
- Bug description summary: Key not detected without pcsc-lite installed 

Steps to reproduce

Installed Yubico Authenticator from flatpak here: https://flathub.org/apps/details/com.yubico.yubioath
Ran app - console output includes `failed to update readers: no_pcscd`
Inserted Yubikey in USB port: Key is not shown 

Installed pcsc_lite package using dnf on Fedora Workstation and rpm-ostree on Silverblue
Ran app and inserted key: 
Key is detected and shows saved TOTP codes.

**Comment by dagheyman** [comment]
Thanks! The Flatpak is however not maintained by us, my suggestion is to report the issue here https://github.com/flathub/com.yubico.yubioath

**Comment by andmalc** [comment]
Thanks I'll do that and also request changing their 'Issues' link to direct there instead of here.
