### ISSUE TITLE
Windows10 v2004，Physical key login

### ISSUE THREAD

**Issue by EricMzky** [Yubico/yubioath-desktop#615]
- Yubico Authenticator version: No
- Operating system and version: windows10 v2004
- YubiKey model and version: 5.2.4
- Bug description summary: 

What can I do to log in to windows10 using the physical key and password free？
I see the security key in the login options set by the system
Then it says log in using the physical key.But when I win plus L.When you re-enter Windows, there are no options to log in with a physical key, only a password
what should I do ？
thanks 
Yubikey 5 NFC

**Comment by dagheyman** [comment]
Hi, 

This sounds like a question better suited for our technical support team. Feel free to file a ticket.
https://support.yubico.com/support/tickets/new

**Comment by EricMzky** [comment]
> Hi,
> 
> This sounds like a question better suited for our technical support team. Feel free to file a ticket.
> https://support.yubico.com/support/tickets/new

That's OK，thank you ~~~
