### ISSUE TITLE
Using the add function does nothing

### ISSUE THREAD

**Issue by cuddylier** [Yubico/yubioath-desktop#62]
Hi

When I use the add function and get it to scan the QR code, it gets the code fine and adds it to the secret key field, when I select the 2nd slot and hit 'Ok', it doesn't actually do anything or add the details,  when I unplug and plug the Yubikey NEO in again, it doesn't show the new credential nor on the Android app. When I add credentials on the Android app, they show both on the Windows app and Android app.

**Comment by dainnilsson** [comment]
The desktop version of Yubico Authenticator support two different modes, the "normal" OATH functionality which is available in the NEO and YK4, which is also supported on Android over NFC, and the older "legacy" mode, which uses the two slots available on more basic YubiKeys as well. The desktop app SHOULD always use the newer OATH functionality, if available. If not, it will use the legacy mode as a fallback.

Now, as the dialog you get when you're adding a credential is referencing slots, this means that the app is unable to detect the newer OATH functionality and instead using the legacy fallback . This might be because you do not have CCID mode enabled, which is required for the newer functionality. If so, you can use https://developers.yubico.com/yubikey-neo-manager/ to enable it. If CCID mode is enabled and you're still having this problem, then please let me know and we'll take it from there.

**Comment by cuddylier** [comment]
Yes, I have CCID enabled on both keys: http://i.imgur.com/tsnpPRe.png

When I open Windows Authenticator, it brings up the multiple OATH credentials I have on the one slot so it's definitely storing them all within just slot 2 but when I click the refresh icon icon on the slot name, that's when it asks me to press my yubikey then does nothing when I do tap it. If that is part of the legacy mode then how do I make it so I have to tap to get further TOTP codes after the initial time is up as it keeps restarting the time after it runs out currently.

**Comment by dainnilsson** [comment]
The slot based (legacy) mode only supports two unnamed credentials, one in slot 1 and one in slot 2. If you have more than two credentials then you're definitely using the "normal" mode. Also, the slot based credentials will be named "YubiKey slot1" and "YubiKey slot 2", anything else is NOT using the legacy slots.

Now, it seems that something else is interfering with the app detecting the "normal" OATH functionality. If you open the application settings, try disabling both slots and saving. That way the app will not try reading from the legacy slots which under some circumstances interferes with the normal mode.

**Comment by dainnilsson** [comment]
Oh, and requiring touch is only supported for (legacy) slot based credentials as well as for the newer YubiKey 4 "normal" OATH functionality.

**Comment by cuddylier** [comment]
Adding and reading now works flawlessly after I disabled the read from the 2nd slot in settings so thanks a lot for that :)

It's a shame the touch requirement is only supported for the newer versions since the Android app has a version of it where you have to tap the yubikey again to get new codes after the timer is up.

**Comment by cuddylier** [comment]
Is there anyway you can make it stop generating codes until the yubikey is pressed again or replugged in for my NEO since it's such a big security hole if someone got into my computer somehow remotely and was able to generate codes if I accidentlally left the Yubikey plugged in while I was away. I know it currently doesn't exist as you say but is it a possibility to add?

**Comment by dainnilsson** [comment]
Not for NEO, I'm afraid. As stated, the YubiKey 4 can be programmed to require a button press for each code generation, but the NEO does not support this. What you can do is not have the application remember the password. In that case, any time the window is hidden (closed or minimized) the cached password will be deleted, and you will need to re-enter it the next time you wish to generate a code.

**Comment by cuddylier** [comment]
Ah so even having the authenticator window minimised, will stop any passcodes being generated? Maybe a master password setting could be added that you need to enter each time you wish to generate codes?

**Comment by dainnilsson** [comment]
That is correct. Once minimized the app will stop generating codes, and any non-persisted password will be "forgotten".

The problem with requiring a password for _each_ time you want to generate codes is that each code is only valid for at _most_ 30 seconds. Half of the time the code will be valid fro less than 15 seconds, likely requiring another code generation before you're able to get a code that is usable. Add in the time it takes to locate the correct code in a long list, and you easily get into a situation where you have to enter the password multiple times just to use it once, which would be a usability nightmare.
