### ISSUE TITLE
Yubico OTP error/invalid when used on diff OS

### ISSUE THREAD

**Issue by unchainedio** [Yubico/yubioath-desktop#646]
- Yubico Authenticator version: 5.0.4
- Operating system and version:  Manjaro/Arch Linux latest version
- YubiKey model and version: NFC5
- Bug description summary: 
I created my OTP (6 digit) profiles for diff websites on a Mac, i then upgraded my computer to a linux system.  On my new laptop non of my OTPs work when i try to login.  I keep getting an error on sites where i have yubikey setup as 2fa that the OTP is invalid/incorrect.

Steps to reproduce
---
Create an OTP/2fa on one OS, say Mac Os, switch machines to a linux system (in my case Manjaro), plug in your Yubikey and use the OTP to try and login to a site as 2fa (U2F works).

Expected result
---

i expect my OTP to work on any system as that is the selling point of Yubkey.
Thus far it only authenticates correctly on the original system i created the OTP profile on.

Actual results
---

I get invalid OTP when i use it for 2fa, U2f works though

Other info
---

The only thing i am wondering is if there is anything in the OTP creation process on yubikey that ties to either the system you create it on or the IP or something along those lines.  Its weird that the OTP only works when i go back to my Mac

**Comment by dainnilsson** [comment]
Assuming the credential is of the TOTP type (which is the most commonly used one by far), the current time of the system is sent to the YubiKey to generate a code, as these are time dependent. Can you make sure the system clock is correct on your Linux system?

**Comment by unchainedio** [comment]
what do u mean correct?  correct in relation to what?  its matches my local time

if u can tell me a command to enter that u can verify.

**Comment by unchainedio** [comment]
![image](https://user-images.githubusercontent.com/22932825/86363283-e60d1000-bc76-11ea-9176-d2423e9780dd.png)

**Comment by dainnilsson** [comment]
Based on that screenshot and when you posted it, it looks like your clock is a few minutes fast (it's currently 15:17 as I'm typing this). TOTP codes are generally only valid for a period of 30 seconds, so that would explain it.

**Comment by unchainedio** [comment]
should i set HW clock in local time as well?

**Comment by emlun** [comment]
I'd recommend trying the instructions [here](https://wiki.manjaro.org/System_Maintenance#Time_and_Date), or maybe the [Arch wiki](https://wiki.archlinux.org/index.php/System_time#Time_synchronization) if that doesn't work.

**Comment by unchainedio** [comment]
worked great, didnt realize time was off.  thanks.  closing
