### ISSUE TITLE
Yubico Authenticator window should minimize once copy to clipboard icon clicked

### ISSUE THREAD

**Issue by MatzFan** [Yubico/yubioath-desktop#65]
Improved UX if window minimises automatically, rather than user having to do it before pasting auth code into the required application - e.g. GitHub, via a browser.

Using: Yubico Authenticator 2.3.0, Mac OS X 10.10.5

**Comment by dainnilsson** [comment]
This is already what happens if you double-click on the code itself rather than the copy button.

**Comment by MatzFan** [comment]
Aha, thanks for that tip!
