### ISSUE TITLE
Screen shows "Insert your YubiKey" on startup after SSH

### ISSUE THREAD

**Issue by squidpickles** [Yubico/yubioath-desktop#654]
- Yubico Authenticator version: 5.0.4
- Operating system and version: MacOS Catalina 10.15.6
- YubiKey model and version: 5C Nano
- Bug description summary: When launching the application, the screen shows "Insert your YubiKey" and the lights on the YubiKey stay on indefinitely. Unplugging it and plugging it back in allows it to be detected. This happens any time I've used it as an SSH key first.

Steps to reproduce
---
1. Use GPG/smartcard-based SSH key
2. Launch application

Expected result
---
Application should launch and detect the key.

Actual results
---

Application launches and does not detect the key, unless the key is unplugged and plugged back in, or the computer is put to sleep.

Other info
---
Using browser-based U2F before launching the application does not seem to trigger this bug.

**Comment by fdennis** [comment]
Hi,
How did you install Yubico Authenticator?

**Comment by squidpickles** [comment]
Installed using Homebrew.

**Comment by fdennis** [comment]
This is an issue with GPG's scdaemon (smartcard daemon) locking the card, preventing other applications from using it. You can either manually kill gpg-agent to unlock it by running `gpgconf --kill gpg-agent` or configure scdaemon to timeout when it becomes idle by setting a `card-timeout` in scdaemon.conf. Note that this will cause you to have to enter your PIN each time gpg-agent is again used after being killed.

**Comment by squidpickles** [comment]
Interesting. Other than adding a feature to kill the gpg-agent on launch, I can't see a good way around this. Guess it's out of scope.

Thanks
