### ISSUE TITLE
Stops detecting connected key after a while

### ISSUE THREAD

**Issue by mkarajohn** [Yubico/yubioath-desktop#656]
- Yubico Authenticator version: 5.0.4 (snap package, `source: snapcraft.io`)
- Operating system and version: Ubuntu 20.04.1 LTS x86_64 
- YubiKey model and version: 5 NFC
- Bug description summary: The Authenticator snap program stops detecting connected Yubikeys.

Steps to reproduce
---

Install the snap version of the app from Ubuntu Software Center (the one with `source: snapcraft.io`). Run the program, and connect a Yubikey. The first few times it's going to get detected normally. After a while the program stops detecting any connected keys.

Expected result
---

To consistently recognize the connected yubikeys.

Actual results
---

After a while the program stops detecting any connected keys.

Other info
---

The issue gets resolved temporarily by running `sudo snap restart yubioath-desktop.pcscd`

The other version of the Yubikey Authenticator in the Ubuntu Software Center does not have this issue at all. (`source: ubuntu-focal-universe`)

EDIT: Actually, i dug into it some more, and I am noticing that the `pcscd` process fails to start when the program starts running. There are no other `pcscd` processes running in the background. There are no `pcscd` processes running at all actually, which is why it starts working when i run `sudo snap restart yubioath-desktop.pcscd`

Terminating the Authenticator does not kill the `pcscd` process (at least not immediatelly) but it does get killed at some point later on, and that's why I am noticing that the keys are not detected after some point

**Comment by fdennis** [comment]
Are you getting the same problem with the appimage? Found [here](https://developers.yubico.com/yubioath-desktop/Releases/). Most likely, this has to do with the snap version only. We will look into it.

**Comment by mkarajohn** [comment]
Yeah, that's correct, the issue only exists in the snap version.

**Comment by Linuturk** [comment]
Seeing the same issue here with the snap version on Kubuntu 20.04.

**Comment by fdennis** [comment]
We will take a look at this. In the meantime, you can always try the AppImage instead.

**Comment by lemairecarl** [comment]
I have this problem too.

Did you know that there is another Yubico Authenticator, with a different icon, that is available in the snap store through the desktop app? According to the reviews, this one works. Although, I would not use it since I cannot guarantee that it really comes from Yubico.

For now, my solution is to use the AppImage, and to manually add a menu item to access it quickly.

**Comment by freedge** [comment]
after some inactivity I can see in the logs:
```
sudo snap logs -n all  yubioath-desktop
...
2021-11-05T22:40:12Z yubioath-desktop.pcscd[318846]: 68515910 commands.c:1124:CmdPowerOff Card absent or mute
2021-11-05T22:40:13Z systemd[1]: snap.yubioath-desktop.pcscd.service: Succeeded.
```
and the service needs to be manually restarted after that.

I think this is a consequence of using the ```--auto-exit``` option when starting usr/sbin/pcscd, and/or not having a restart-condition in the pcscd daemon.
