### ISSUE TITLE
YubiKey already in use error on Windows client

### ISSUE THREAD

**Issue by Zyg0te** [Yubico/yubioath-desktop#67]
I dont have this issue on OSX but in Windows with version 2.3.0 Im having a real hard time getting the authenticator to read my Yubikey. I get the "YubiKey already in use" error and I end up having to restart the authenticator and plug the Yubikey into my various USB ports until finally it's ready successfully. 

I have the "Kill scdaemon on show" option enabled but that doesnt seem to have much effect.

**Comment by dagheyman** [comment]
I'm not able to reproduce this on my Windows 10 installation. I would need more information to investigate this further. You could also try to create a a support ticket.
https://www.yubico.com/support/raise-ticket/
