### ISSUE TITLE
Yubico Authenticator Not Responding on Windows

### ISSUE THREAD

**Issue by wichtounet** [Yubico/yubioath-desktop#673]
- Yubico Authenticator version: 5.0.4 win64
- Operating system and version: Windows 10 Home
- YubiKey model and version: Yubikey 5 NFC
- Bug description summary: The app is not responding. 

Steps to reproduce
---

Just starting the tool starts it in "Not Responding" mode. I can't do anything with the tool.

Expected result
---

I am expecting it to start and show my Yubikey.

Actual results
---

The app stays in Not Responding mode and I cannot do anything else than Kill It.

Other info
---

It used to work but after a Reboot,  nothing is working anymore. I tried uninstalling and reinstalling, to no avail. Starting without my key plugged in leads to the same issue. I also tried Reset and Repair from Windows.

**Comment by fdennis** [comment]
Hi,
What version of Windows 10 are you using? How did you install the app?

**Comment by wichtounet** [comment]
Hi @fdennis 

I have Windows 10 Home, Version	10.0.19041 Build 19041

I have installed the win64 msi from here: https://developers.yubico.com/yubioath-desktop/Releases/

Thanks

**Comment by fdennis** [comment]
If you have tried uninstalling and reinstalling, another approach could be to install another version, such as 5.0.3, and see if that works better. I cannot reproduce your issue in Win 10 19041.

**Comment by wichtounet** [comment]
Hi @fdennis 

I have just tried. All 5.0.X versions have the same issues. I am able to start 4.3.0 but then it does not show my Yubikey (shows connecting to Yubikey and never changes). 4.3.4 has the same issue as 5.0. I have also tried win32 and win64 installers.

**Comment by wichtounet** [comment]
Hi @fdennis 

I have tried other 5.0.X version and the issue is the same. 
I have tried up to 4.3.0 and this one starts but does not show my key. 4.3.4 does not work (same issue as 5.0.4). 

I have upgraded Windows to Version 10.0.19042, but it did not change a thing, Yubico Authenticator is still not starting.

**Comment by nevun** [comment]
@wichtounet would you have time to try out running process monitor on your computer and try and capture a log so we can see what is going on?

https://docs.microsoft.com/en-us/sysinternals/downloads/procmon

It is a bit tricky to get going but basically you just need to add a filter for the yubioath-desktop exe file, start recording and then start yubioath-desktop.exe.

**Comment by wichtounet** [comment]
@nevun Here you go: https://file.io/Xn4KCRgaVn72

It's the first time I am using this tool, so I am not sure my recording is good. Let me know if you need other things.

**Comment by wichtounet** [comment]
Ok, I think this one is much more complete: [Logfile3.zip](https://github.com/Yubico/yubioath-desktop/files/5591653/Logfile3.zip)

**Comment by nevun** [comment]
@wichtounet thank you, it is our end of day here in Sweden but we will look at the log in more detail tomorrow. I could load if fine and it looks about right.

**Comment by nevun** [comment]
@wichtounet sorry for not getting back to you. I am comparing to traces on a computer where it works fine and the main difference I see is that your computer is loading D3D12.dll for Direct3D support in QT which mine is not. There are some debug options here you might be able to enable for getting more debug: https://doc.qt.io/qt-5/qtquick-visualcanvas-adaptations-d3d12.html , like setting the env variable QT_D3D_DEBUG to 1.

Seems QT has fixed a few issues and we should maybe see if 5.14.2.2 fixes these hang. It also might not. Hang on.

**Comment by nevun** [comment]
For the record, 5.14.2 did not fix the reporter's issue.

**Comment by wichtounet** [comment]
@nevun asked me to try:

```
set QT_OPENGL=software
yubioath-desktop.exe
```

and this fixed my issue! The software is working like before and I can see all my tokens.

Thanks a lot @nevun
