### ISSUE TITLE
Font changes, UI tweaks

### ISSUE THREAD

**Issue by rmenessec** [Yubico/yubioath-desktop#68]
Please enlarge the font used for displaying OTP codes to make them the largest element. Please also change the OTP code font face to use the system default monospace. Alternately, adding customizable font face and style options would be welcome.

Slightly larger extra margins would also help with long lists of OTPs.

For comparison, see 
![screenshot_ga](https://cloud.githubusercontent.com/assets/425616/12764729/6828f66c-c9c9-11e5-9822-54c7a59ff960.png)

**Comment by dagheyman** [comment]
I've made some visual changes to the codes, which should resolve this issue. The font will stay as the default font for now though.
