### ISSUE TITLE
Support for SHA512 algorithm

### ISSUE THREAD

**Issue by Jawshy** [Yubico/yubioath-desktop#689]
Please add support for the SHA512 algorithm. I tried to add TOTP for an account, but because it uses SHA512 I couldn't add it to Yubico Authenticator. Scanning the QR code gave a generic error and there's no option for SHA512 when adding manually.

**Comment by dainnilsson** [comment]
SHA512 is supported and should be shown as an option when adding an account if the YubiKey supports it. Note that SHA-512 support is available on YubiKey 4.3.1 and later.

**Comment by Jawshy** [comment]
I tried my newer YubiKey and it worked. Thank you.
