### ISSUE TITLE
yubioauth fails to detect YubiKey

### ISSUE THREAD

**Issue by DarkDimius** [Yubico/yubioath-desktop#70]
OSX Yosemite. yubioath 2.3.0.
On first load, yubioauth says that YubiKey is already used.
If YubiKey is re-plugged, yubioauth fails to detect the Yubikey.

**Comment by DarkDimius** [comment]
I'm not sure if this is relevant, but if I try `pcsctest` it outputs:
```

MUSCLE PC/SC Lite Test Program

Testing SCardEstablishContext    : Command successful.
Testing SCardGetStatusChange
```
and hangs.

**Comment by DarkDimius** [comment]
`system_profiler SPUSBDataType `
reports:
```
        Yubikey NEO OTP+U2F+CCID:

          Product ID: 0x0116
          Vendor ID: 0x1050
          Version: 3.37
          Speed: Up to 12 Mb/sec
          Manufacturer: Yubico
          Location ID: 0x14100000 / 16
          Current Available (mA): 1000
          Current Required (mA): 30
          Extra Operating Current (mA): 0
```

**Comment by dagheyman** [comment]
If you download and run Yubikey NEO Manager (https://developers.yubico.com/yubikey-neo-manager/) does it list anything under `Available apps` ?

**Comment by DarkDimius** [comment]
Yes, it does list: 
 - YubiKey OTP
 - YubiOATH
 - Yubico U2F
 - OpenPGP
 - OpenPGP

And it does it both when YubiKey is detected by yubioauth and when it is not detected.

**Comment by dagheyman** [comment]
Is this still the case with the new version (4.0.0) ?
https://developers.yubico.com/yubioath-desktop/Releases/

**Comment by dagheyman** [comment]
Closing this, please try with the latest version and feel free to open new issues if there are any remaining problems.

**Comment by DarkDimius** [comment]
The issue persists after update. I've created a new issue.
