### ISSUE TITLE
Yubico Authenticator fails to display Key on MacOS 

### ISSUE THREAD

**Issue by sergedroz** [Yubico/yubioath-desktop#700]
- Yubico Authenticator version: 5.0.4
- Operating system and version:  MacOS 10.2.3 (20D91) Big Sur
- YubiKey model and version: 5c Nano
- Bug description summary: Yubico Authenticator fails to display TOTP codes

Steps to reproduce
---
1. Start the application
2. Main screen shows "Insert your YubiKey"
3. Settings recognizes Key, but no entries shown

-> See attached screenshots
![Main Screen](https://user-images.githubusercontent.com/12233053/112121690-cb414980-8bbf-11eb-823f-b46f2ff985ac.png)
![Settings](https://user-images.githubusercontent.com/12233053/112121692-cc727680-8bbf-11eb-856b-eeb6bd3647f1.png)

Expected result
---

Entries show. 

Actual results
---

App asks to insert YubiKey

Other info
---

Starting from the command line I get this output:
/Applications/Yubico\ Authenticator.app/Contents/MacOS/yubioath-desktop
Qt Quick Layouts: Detected recursive rearrange. Aborting after two iterations.
Qt Quick Layouts: Detected recursive rearrange. Aborting after two iterations.
Qt Quick Layouts: Detected recursive rearrange. Aborting after two iterations.
qt.qpa.drawing: Display non non-main thread! Deferring to main thread
qml: calculateAll failed: open_device_failed
qml: calculateAll failed: open_device_failed
qml: calculateAll failed: open_device_failed
qml: calculateAll failed: open_device_failed
qml: calculateAll failed: open_device_failed
...

**Comment by sergedroz** [comment]
I also seem to get this message:
default	11:16:50.620984+0100	tccd	AUTHREQ_ATTRIBUTION: msgID=83510.36, attribution={responsible={identifier=com.googlecode.iterm2, pid=404, auid=966, euid=966, responsible_path=/Applications/Utilities/iTerm.app/Contents/MacOS/iTerm2, binary_path=/Applications/Utilities/iTerm.app/Contents/MacOS/iTerm2}, requesting={identifier=com.yubico.yubioath, pid=83510, auid=966, euid=966, binary_path=/Applications/Yubico Authenticator.app/Contents/MacOS/yubioath-desktop}, },
error	11:16:50.627028+0100	yubioath-desktop	0x10005799f: TCC deny IOHIDDeviceOpen
rspt:
AppleUSBHostUserClient::openGated: could not open provider IOUSBHostDevice. provider already opened for exclusive access by a kernel client

**Comment by fdennis** [comment]
Hi,
From your last message it looks like something is blocking the access to your YubiKey. It is difficult for me to provide anymore information beyond this. Perhaps you are using the smart card? Are you using gpg at the same time? Something has exclusive access to your YubiKey, that is the issue.

**Comment by sergedroz** [comment]
No that I'm aware of. Is there any way to check what is accessing a given device?

**Comment by fdennis** [comment]
@sergedroz I'm not sure. Are you still having this issue? Have you tried it on another Mac and made it work?

**Comment by sergedroz** [comment]
Hi @fdennis 
Yes the issue remains. Intermittently the key works again, but then stops again. I tend to agree that something else is using it, but I haven't figured out what this could be. Interestingly this does not happen on a newer Mac. 
I've meanwhile switch to the newer machine for most of my work. 

I'm happy to test, but currently lack resources to actively investigate.

**Comment by fdennis** [comment]
@sergedroz I will close this issue then, since it is not repeated on the newer Mac. Most likely, something else is grabbing the key.
