### ISSUE TITLE
32bit msi installer won't install on 32bit windows

### ISSUE THREAD

**Issue by mirostauder** [Yubico/yubioath-desktop#702]
- Yubico Authenticator version: 5.0.5
- Operating system and version: Windows 10
- YubiKey model and version: n/a
- Bug description summary: 32bit msi installer won't install on 32bit windows

- Steps to reproduce:
run the win32 msi installer on 32bit Windows 10
e.g.: msiexec /i yubioath-desktop-5.0.5-win32.msi

- Expected result
install succeeds

- Actual results
Windows Installer error popup:
This installation package is not supported by this processor type.
Contact your product vendor.

- Other info
installs on 64bit windows

**Comment by fdennis** [comment]
Thanks for reporting. I can confirm this. We will look into it.

**Comment by fdennis** [comment]
This has now been fixed. It will take a couple of hours for the website to load. The new installer will be version 5.0.5b. Give it a try later if you can.

**Comment by fdennis** [comment]
@mirostauder Have you tried the new installer? It is available here https://developers.yubico.com/yubioath-desktop/Releases/

**Comment by mirostauder** [comment]
works fine now.
Thanks!
