### ISSUE TITLE
Doesn't run on Python 3

### ISSUE THREAD

**Issue by bwhacks** [Yubico/yubioath-desktop#71]
Several Linux distributions including Debian are deprecating Python 2, so yubioath-desktop won't run any more. Please consider using transition tools such as python-six to work with Python 3 as well.

**Comment by hsanjuan** [comment]
I would say this is rather a bug. It's not about enhancing the app, it's about the app being fully broken on multiple distros. My two cents...

**Comment by dainnilsson** [comment]
Clearly it's not a bug, I don't really think that's a matter of opinion. Just as it isn't a bug that the application isn't written in Java, or doesn't run on iOS. Python 2 will still run on any platform we've targeted in the past, even though it may be deprecated.

On the topic of the issue itself: This _enhancement_ will most likely be implemented in the next major version release. No ETA as of yet for that.

**Comment by dagheyman** [comment]
The current version on the master branch and the upcoming release is compatible with Python 3.
