### ISSUE TITLE
yubioath and ykman (cli+gui) not working on FreeBSD 13.0

### ISSUE THREAD

**Issue by iandstanley** [Yubico/yubioath-desktop#712]
- Yubico Authenticator version:  5.04
- Operating system and version:  FreeBSD 13.0
- YubiKey model and version:  Yubikey 5NFC (and same problem with yubikey 4 and neo) - I have tried a few with the same issue ... ALL KEYS WORK PERFECTLY ON MY DEBIAN 10 DESKTOP

- Bug description summary: 
YUBIOATH desktop cannot see *any* yubikey I insert a yubikey 

I get a lot of log output (see below) if I run this from an xterm

Steps to reproduce
---
install freebsd 13.0
install yubikey software as listed below
launch yubioath desktop software

Expected result
---
I should see the yubikey inserted and be able to add an totp oath code

I have tried with multiple keys from yubikey 5nfc / yubikey 4 / yubikey neo all without success

I have other issues with ykman cli and gui 

Other yubikey tools work fine: 

- ykinfo, 
- ykpersonalize (+gui), 
- yubikey-piv-tool 
- opensc tools, 
- gpg 
- Also U2F works with firefox (but oddly FIDO2 doesn't work with demo.yubico.com) ... I suspect this may be a firefox issue though

Actual results
---

screen stays waiting for yubikey to be inserted
logs spew out if lauched from teriminal (see below)

Other info
---

I am trying to get my yubikey 5 working with FreeBSD v13.0 on my laptop
I also have a yubikey 4 and a neo to hand to test as well

Each of these keys work perfectly on my desktop under Debian 10

### INSTALLED SOFTWARE
I have installed the following software from the FreeBSD 13 repositories

- libyubikey, 
- yubico-piv-tool, yubikey-agent, yubikey-manager-qt, yubikey-personalization-gui, pam_yubico
also 
- pcsc-lite, opensc

### First of all ... what works
- I can run ykinfo and pull up all the details from each key I try 
- I have u2f working on firefox and can login with any of my keys into the demo.yubico.com test server.
- ykpersonalisation cli works fine as does the gui

# What fails 
- Oddly FIDO2 under firefox on the demo.yubico.com test server with my yubikey 5nfc (???)
- ykman cli and gui (different errors but may be linked)
- yubi-oath gui 

# yubioath-desktop  5.04

Running the oath desktop gets me a lovely gui that is mostly functional. And by that I mean I can access the settings and the (i) info box 

However, the gui ignores any yubikey I insert ... I have tried both yubikey 5nfc's and some yubikey 4's that I have around.

`
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"<string>\", line 1, in <module>\n\nNameError: name 'yubikey' is not defined\n"
Unhandled PyOtherSide error: Function not found: 'yubikey.controller.get_connected_readers' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: TypeError: Cannot read property 'success' of undefined undefined
`

Just a bit lost and confused with this as most things work except ykman/ykman gui / yubioath gui

Any ideas?

**Comment by iandstanley** [comment]
pcscd is running

when i run pcsc_scan I get the following as I insert my yubikey5
`
Using reader plug'n play mechanism
Scanning present readers...
Waiting for the first reader...   ^found one
Scanning present readers...
0: Yubico YubiKey OTP+FIDO+CCID 00 00

Wed Jun  9 00:52:37 2021
 Reader 0: Yubico YubiKey OTP+FIDO+CCID 00 00
  Event number: 0
  Card state: Card inserted,
  ATR: 3B FD 13 00 00 81 31 FE 15 80 73 C0 21 C0 57 59 75 62 69 4B 65 79 40

ATR: 3B FD 13 00 00 81 31 FE 15 80 73 C0 21 C0 57 59 75 62 69 4B 65 79 40
+ TS = 3B --> Direct Convention
+ T0 = FD, Y(1): 1111, K: 13 (historical bytes)
  TA(1) = 13 --> Fi=372, Di=4, 93 cycles/ETU
    43010 bits/s at 4 MHz, fMax for Fi = 5 MHz => 53763 bits/s
  TB(1) = 00 --> VPP is not electrically connected
  TC(1) = 00 --> Extra guard time: 0
  TD(1) = 81 --> Y(i+1) = 1000, Protocol T = 1
-----
  TD(2) = 31 --> Y(i+1) = 0011, Protocol T = 1
-----
  TA(3) = FE --> IFSC: 254
  TB(3) = 15 --> Block Waiting Integer: 1 - Character Waiting Integer: 5
+ Historical bytes: 80 73 C0 21 C0 57 59 75 62 69 4B 65 79
  Category indicator byte: 80 (compact TLV data object)
    Tag: 7, len: 3 (card capabilities)
      Selection methods: C0
        - DF selection by full DF name
        - DF selection by partial DF name
      Data coding byte: 21
        - Behaviour of write functions: proprietary
        - Value 'FF' for the first byte of BER-TLV tag fields: invalid
        - Data unit in quartets: 2
      Command chaining, length fields and logical channels: C0
        - Command chaining
        - Extended Lc and Le fields
        - Logical channel number assignment: No logical channel
        - Maximum number of logical channels: 1
    Tag: 5, len: 7 (card issuer's data)
      Card issuer data: 59 75 62 69 4B 65 79
+ TCK = 40 (correct checksum)

Possibly identified card (using /usr/local/share/pcsc/smartcard_list.txt):
3B FD 13 00 00 81 31 FE 15 80 73 C0 21 C0 57 59 75 62 69 4B 65 79 40
        Yubico YubiKey 5 NFC (PKI)
        https://www.yubico.com/product/yubikey-5-nfc
`

**Comment by fdennis** [comment]
Hi,

I will refer you to your other thread in ykman-gui. It already has an answer that is applicable here as well.
https://github.com/Yubico/yubikey-manager-qt/issues/290
