### ISSUE TITLE
Authenticator app crashes after interacting with the UI

### ISSUE THREAD

**Issue by jessehattabaugh** [Yubico/yubioath-desktop#714]
- Yubico Authenticator version: 5.0.5.0
- Operating system and version: Windows 10, 21H1
- YubiKey model and version: 5 NFC
- Bug description summary: Authenticator app crashes after interacting with the UI

Steps to reproduce
---

- Open the app
- Move mouse cursor over any part of the UI
- Interact with the UI (clicking, scrolling, hovering)

Expected result
---

- UI should respond to click

Actual results
---

- UI elements freeze, sometimes mid animation
- a short pause
- app crashes
- sometimes AMD display drivers' bug reporting tool pops up
- Windows Event Viewer contains the following error:

>  Faulting application name: yubioath-desktop.exe, version: 5.0.5.0, time stamp: 0x607708c1
> Faulting module name: Qt5Gui.dll, version: 5.14.1.0, time stamp: 0x5e296c01
> Exception code: 0xc0000005
> Fault offset: 0x00000000000ec509
> Faulting process id: 0xa3c
> Faulting application start time: 0x01d76396d243c88a
> Faulting application path: C:\Program Files\Yubico\Yubico Authenticator\yubioath-desktop.exe
> Faulting module path: C:\Program Files\Yubico\Yubico Authenticator\Qt5Gui.dll
> Report Id: fa1fc566-af83-4dd0-97ca-9d7e4abb9d80
> Faulting package full name: 
> Faulting package-relative application ID: 

> Faulting application name: yubioath-desktop.exe, version: 5.0.5.0, time stamp: 0x607708c1
> Faulting module name: ntdll.dll, version: 10.0.19041.1023, time stamp: 0x7977b9de
> Exception code: 0xc0000005
> Fault offset: 0x000000000002426b
> Faulting process id: 0x8f8
> Faulting application start time: 0x01d763949c259de1
> Faulting application path: C:\Program Files\Yubico\Yubico Authenticator\yubioath-desktop.exe
> Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
> Report Id: 6b03cf39-5d63-4c44-9d84-07f7d98d177c
> Faulting package full name: 
> Faulting package-relative application ID: 

> Faulting application name: yubioath-desktop.exe, version: 5.0.5.0, time stamp: 0x607708c1
> Faulting module name: AcLayers.DLL, version: 10.0.19041.1023, time stamp: 0xdff7bbc0
> Exception code: 0xc0000374
> Fault offset: 0x0000000000009cb6
> Faulting process id: 0x3a8c
> Faulting application start time: 0x01d76394826ca709
> Faulting application path: C:\Program Files\Yubico\Yubico Authenticator\yubioath-desktop.exe
> Faulting module path: C:\Windows\SYSTEM32\AcLayers.DLL
> Report Id: c9854b61-89e5-43d1-8622-98498886ce87
> Faulting package full name: 
> Faulting package-relative application ID: 

> Faulting application name: yubioath-desktop.exe, version: 5.0.5.0, time stamp: 0x607708c1
> Faulting module name: Qt5Core.dll, version: 5.14.1.0, time stamp: 0x5e296b4a
> Exception code: 0xc0000005
> Fault offset: 0x000000000002ada6
> Faulting process id: 0x46a0
> Faulting application start time: 0x01d7639452b534dd
> Faulting application path: C:\Program Files\Yubico\Yubico Authenticator\yubioath-desktop.exe
> Faulting module path: C:\Program Files\Yubico\Yubico Authenticator\Qt5Core.dll
> Report Id: e0213856-8b5b-4f39-bc26-b0312814bfff
> Faulting package full name: 
> Faulting package-relative application ID: 

> Faulting application name: yubioath-desktop.exe, version: 5.0.5.0, time stamp: 0x607708c1
> Faulting module name: atio6axx.dll, version: 27.20.21003.8013, time stamp: 0x609a2ed5
> Exception code: 0xc0000005
> Fault offset: 0x00000000016c3dd6
> Faulting process id: 0x304
> Faulting application start time: 0x01d763934325d834
> Faulting application path: C:\Program Files\WindowsApps\YubicoAB.YubicoAuthenticator_5.0.5.0_x64__pjam772p9bs2g\VFS\ProgramFilesX64\Yubico\Yubico Authenticator\yubioath-desktop.exe
> Faulting module path: C:\Windows\System32\DriverStore\FileRepository\u0367492.inf_amd64_dc9dba40afc0f9b5\B367342\atio6axx.dll
> Report Id: 56c4bad1-6d38-4bd0-8f4d-d23f10925546
> Faulting package full name: YubicoAB.YubicoAuthenticator_5.0.5.0_x64__pjam772p9bs2g
> Faulting package-relative application ID: YUBIOATHDESKTOP

Other info
---

1. This seems to only occur on machines with AMD display drivers. I have a Vega 56 GPU with the 21.5.2 drivers.
2. This problem has been occurring for over a year with various versions of Windows, the Authenticator, and the AMD display drivers.
3.  If the app is not interacted with for about a minute after launching, the problem doesn't occur as regularly.

**Comment by fdennis** [comment]
Thanks for reporting this.
Does it help if you set the environment variable` QT_OPENGL` to `software`?

**Comment by jessehattabaugh** [comment]
Yes, that does help! Thanks! I'll report if it recurs.

**Comment by jessehattabaugh** [comment]
Wait, that's not a solution to the problem is it? Surely you don expect everyone who uses this app with an AMD GPU to set an environment variable.

**Comment by jessehattabaugh** [comment]
![image](https://user-images.githubusercontent.com/17991/123189085-04ed4f00-d452-11eb-8250-6bca2fd6b4a1.png)

**Comment by fdennis** [comment]
Unfortunately, this is a problem with Qt and the current workaround is to set the environment variable. We would like to see this being handled in a better way and are therefore monitoring this issue at Qt. This is not an issue we see the majority of users having and it does not affect every AMD user.

**Comment by jessehattabaugh** [comment]
If that's the case, maybe you'd like to ask me for more details about my system so you can help QT solve this problem?

**Comment by fdennis** [comment]
Thank you for the offer. However that is not necessary at the moment. If you're interested, we can notify you in the future if there are additional things that would be helpful to test to resolve this issue.
