### ISSUE TITLE
Dock icon doesn't open window after window closed

### ISSUE THREAD

**Issue by dsample** [Yubico/yubioath-desktop#74]
On OSX, If the authenticator window is closed, the only way to open it again is from the menubar icon, even though the dock icon is visible. However, the menu with `Preferences...` is only visible on the application menu bar after selecting the dock icon.

I'd suggest Adding a `Preferences...` option to the menu bar icon and allow re-opening of the authenticator window from the dock.

**Comment by woohgit** [comment]
I have an additional issue with it: If I close it and re-open it, it won't detect my TOTP stored codes on it, I even need to restart my mac to be able to read the TOTP codes...

**Comment by dagheyman** [comment]
Should be solved by this fix:
https://github.com/Yubico/python-yubicommon/commit/d0a0864754b76025e26db3b66576e138512de037
