### ISSUE TITLE
Yubikey Bio first time installation & "Authenticator mode is set to ccid but ccid connection mode is not enabled"

### ISSUE THREAD

**Issue by pascal06** [Yubico/yubioath-desktop#757]
Hello,
it's the first time I use a Yubikey, I need help to make it functioning:

- Yubico Authenticator version: 4.3.6
- Operating system and version: Ubuntu 18.04.6 LTS
- YubiKey model and version: Bio FIDO edition
- Bug description summary: when I launch the Yubico Authenticator and insert the key, the led flash in red slowly, and authenticator says "Authenticator mode is set to ccid but ccid connection mode is not enabled".

Steps to reproduce
---
- Add Yubico PPA as an APT repository: sudo add-apt-repository ppa:yubico/stable && sudo apt-get update
- Install YubiKey Manager CLI: sudo apt install yubikey-manager
- Install YubiKey Manager GUI: sudo apt install yubikey-manager-qt
- Install YubiKey Personalization Tool: sudo apt install yubikey-personalization-gui
- Install libpam-yubico: sudo apt install libpam-yubico
- Install libpam-u2f: sudo apt install libpam-u2f

Expected result
---
A working key !

Actual results
---
"Authenticator mode is set to ccid but ccid connection mode is not enabled"

Thanks a lot in advance.

**Comment by fdennis** [comment]
The latest desktop authenticator version is 5.1.0. Please try that one.

**Comment by pascal06** [comment]
Hello Fdennis,
thanks a lot for your help, that was the trick indeed. So Authenticator is working now.
However, I tried to use the last Manager version and it doesn't display the key... I'm going to open another ticket...
Thanks for all.
Best regards,

Pascal
