### ISSUE TITLE
Yubico Authenticator causes problems with Windows Task Manager and shutdown

### ISSUE THREAD

**Issue by EatonZ** [Yubico/yubioath-desktop#759]
- Yubico Authenticator version: **5.1.0, Windows Store version**
- Operating system and version: **Windows 10 x64**
- YubiKey model and version: **5C NFC, FW 5.2.7**
- Bug description summary:
When Yubico Authenticator is running, if you open Windows Task Manager, Processes will be blank. Additionally, if you try to shut down your PC, you get a message saying "If you shut down now, you and any other people using this PC could lose unsaved work."

Steps to reproduce
---

1. Install Yubico Authenticator from the Windows Store.
2. Open Yubico Authenticator.
3. Open Windows Task Manager. The Processes tab will list nothing:

![Task Manager](https://user-images.githubusercontent.com/3020941/143657499-4d74f76f-1e66-485a-987d-7104b0fa7817.png)

4. Shut down your PC (right click Windows button -> Shut down or sign out -> Shut down). You will get this message:

![Shutdown](https://user-images.githubusercontent.com/3020941/143657509-a3a7a734-e8f6-4642-ae57-59cc5d54e1aa.png)

Expected result
---

Windows Task Manager should be able to list processes with Yubico Authenticator open, and Windows should shut down with no warning messages.

Actual results
---

Yubico Authenticator blocks process enumeration, and appears to conflict with Windows' shutdown process.

Other info
---

1. Quitting Yubico Authenticator instantly fixes both issues. Task Manager starts working, and you can shut down with no warning messages.
2. [I am not the only one running into these issues.](https://www.reddit.com/r/yubikey/comments/qs297w/yubico_authenticator_from_window_11_store_while/)

**Comment by webshaun** [comment]
This has been happening to me since Windows 11 was released.  System was just formatted.  I used the cloud reset option.  This started happening with the yubikey software after the format.

**Comment by MrMase** [comment]
I've also had step 4 appear, however for I have not had the issue with processes appearing but with User session enumeration which then leads to the issue in step 4. As task manager cannot read these even when running in administrator context this would seem to suggest permissions are getting edited at some point.

User session enumeration issue also presents itself in an elevated command prompt.

**Comment by webshaun** [comment]
Any word on this issue?  It hasn't been resolved.  I've tried both the desktop version from the website and the windows store app.  Both present the same issue.

**Comment by fdennis** [comment]
@webshaun A new release for the Windows version should be out soon. If you want, you could try the instructions I left in this comment (https://github.com/Yubico/yubioath-desktop/issues/752#issuecomment-982612871) and verify that it solves the issue for you as well. This would help us understand if the two issues are related (which I am assuming they are). I will keep you posted when the new release is out, should not be long.

**Comment by EatonZ** [comment]
The update has appeared for me on the Windows Store. Am I to presume this will fix the bug? If so, then you may close this issue.

**Comment by fdennis** [comment]
@EatonZ Exactly. A new patch release is out for Windows. You can also find it here https://developers.yubico.com/yubioath-desktop/Releases/
