### ISSUE TITLE
Yubikey NEO not detected on Ubuntu 14.04

### ISSUE THREAD

**Issue by zingmars** [Yubico/yubioath-desktop#76]
Yubikey Authenticator doesn't seem to detect my yubikey. It does seem to be detected by the personalisation tool (http://i.imgur.com/0P1FzV4.png) and keepass's challenge-response plugin, just not the Authenticator. Ideas?

I'm on Ubuntu 14.04.

**Comment by dagheyman** [comment]
Maybe something could be wrong with the CCID configuration. If you download and run Yubikey NEO Manager (https://developers.yubico.com/yubikey-neo-manager/) do you see anything listed under `Available apps` in the side menu?

**Comment by zingmars** [comment]
Nope. 
http://i.imgur.com/y2Vx8vw.png

**Comment by dagheyman** [comment]
Have you tried running the `linux-patch-ccid` script as sudo?
https://github.com/Yubico/yubioath-desktop#detecting-the-device-when-using-ccid

The script can be found here: https://github.com/Yubico/yubioath-desktop/blob/master/resources/linux-patch-ccid

**Comment by zingmars** [comment]
Seems to work. Thanks.

A bit curious as to why this wasn't done by the package in yubico's ppa. Weird.
