### ISSUE TITLE
Snap crashes on launch

### ISSUE THREAD

**Issue by mt206** [Yubico/yubioath-desktop#777]
- Yubico Authenticator version: 5.1.0 Rev 13 Snap
- Operating system and version: Linux - Ubuntu Budgie (20.04.3 LTS)
- YubiKey model and version: Yubikey 5 nfc
- Bug description summary: 
Upon launching the yubioath-desktop it crashes immediately. The message that I get is:

 ```
 Gtk-Message: 13:27:28.415: Failed to load module "appmenu-gtk-module"
Qt: Session management error: Could not open network socket
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
QGLXContext: Failed to create dummy context
Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::DoubleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
Aborted (core dumped)
```

This just started today. This had also happened maybe a year or so ago and switching to nvidia display drivers fixed the immediate crash issue. I had not changed any settings or updated any dependencies prior to this issue manifesting itself this time so I don't think the issues are the same. 

Steps to reproduce
---

Attempt to launch the app

Expected result
---

It should not crash

Actual results
---

It crashes

Other info
---

Is there an alternative to the yubioath-desktop app for a yubikey based authenticator app supporting TOTP codes? A cli version even. This application has frequently been rendered unusable and I can't see any local changes that would be the cause. I experienced issues with the appimage version as well with it recognizing the yubikey but saying the serial was wrong

**Comment by fdennis** [comment]
Hi,
Does this happen every time you try to run it? Even after a reboot of the computer?
There is a CLI called ykman, more information can be found here https://github.com/Yubico/yubikey-manager

**Comment by mt206** [comment]
> Hi, Does this happen every time you try to run it? Even after a reboot of the computer? 
Yes it was happening after every usage and after a reboot as well
> There is a CLI called ykman, more information can be found here https://github.com/Yubico/yubikey-manager
Thanks. I will install that and try to use it in the future. 

After debugging and trying a number of fixes, the issue was related to Nvidia drivers again and something with opengl. It is confusing for me why that would be the case as I was under the, perhaps naive, assumption that snaps packaged all their dependencies. 
Running `sudo apt install libnvidia-gl-440:i386` fixed my particular problem. 
You may close this ticket out if you think this isn't an issue specific to yubioath-desktop.
