### ISSUE TITLE
Via terminal created OATH secrets do not appear in the Authenticator (Flatpak Version)

### ISSUE THREAD

**Issue by shibumi** [Yubico/yubioath-desktop#785]
- Yubico Authenticator version: 5.1.0 Flatpak Version
- Operating system and version: Fedora 35 / Gnome / Linux
- YubiKey model and version:   Yubikey 4 NFC
- Bug description summary:  manually created oath secrets are not displayed in the authenticator

Steps to reproduce
---

Create a few OATH secrets manually:

ykman oath accounts add yubico <KEY> --touch

Then open the Yubikey Authenticator. 

Expected result
---

I should be able to see secrets inserted via the terminal as well.

Actual results
---

I see no OATH codes at all..

**Comment by shibumi** [comment]
After some Investigation I found out, that this behavior only occurs in the Flatpak App. When I install the Application through dnf I have no issues.

**Comment by fdennis** [comment]
Hey,
Have you tried the AppImage? Would be interesting to know if the same problem appears there or not. You can find it here https://developers.yubico.com/yubioath-desktop/Releases/

**Comment by shibumi** [comment]
@fdennis pretty sure that the appimage should work, because the appimage has no isolation or security features, but I will test this too.

I am very confident that the issue has something to do with flatpak's portal... For OATH codes the yubikey needs the CCID interface, this means that the flatpak must run some sort of CCID agent

**Comment by fdennis** [comment]
@shibumi We are not the maintainers of the flatpak. You can find that project here https://github.com/flathub/com.yubico.yubioath

**Comment by shibumi** [comment]
@fdennis ah okay. Then let us close this issue here, sorry for the noise.
