### ISSUE TITLE
Authenticator can not read from USB on Arch Linux

### ISSUE THREAD

**Issue by Jah-On** [Yubico/yubioath-desktop#786]
- Yubico Authenticator version: v5.1.0
- Operating system and version: Garuda Linux running 5.16.12-zen1-1-zen
- YubiKey model and version: Yubikey 5 with NFC
- Bug description summary: Authenticator recognizes Yubikey but can not read or write to it. 

Steps to reproduce
---

I installed the Authenticator app on my fresh Garuda install. I do not know if other Arch systems are affected. 

Expected result
---

I expected to be able to add 2FA accounts to the key and to see those accounts when I plug the Yubikey in.

Actual results
---

When I tried adding 2FA accounts to it, an error bubble showed up saying "Unknown error". With accounts on it, the accounts do not show up at all. 

> Got library name:  "/usr/lib/qt/qml/io/thp/pyotherside/libpyothersideplugin.so"
qrc:/qml/main.qml:353:5: QML Shortcut: Shortcut: Only binding to one of multiple key bindings associated with 4. Use 'sequences: [ <key> ]' to bind to all of them.
qrc:/qml/main.qml:297:5: QML Shortcut: Shortcut: Only binding to one of multiple key bindings associated with 9. Use 'sequences: [ <key> ]' to bind to all of them.
Qt Quick Layouts: Detected recursive rearrange. Aborting after two iterations.
Qt Quick Layouts: Detected recursive rearrange. Aborting after two iterations.
Icon theme "adwaita" not found.
Icon theme "ubuntu-mono" not found.
Icon theme "yaru" not found.
Icon theme "Mint-X" not found.
Icon theme "elementary" not found.
WARNING: PC/SC not available. Smart card protocols will not function.
qml: calculateAll failed: No eligiable connections are available ([<class 'yubikit.core.smartcard.SmartCardConnection'>]).

Console output. ^

Other info
---
I had to add the accounts using my phone with NFC.

**Comment by Jah-On** [comment]
Ok, I did figure it out by starting the PCSC daemon. However, I would suggest adding a console line telling the user to do "sudo systemctl start pcscd". They should not have to come over to GitHub to find that out.

**Comment by fdennis** [comment]
@Jah-On Thank you for the suggestion. In the console output there is a warning - "WARNING: PC/SC not available. Smart card protocols will not function.". However, how you start PCSC is unfortunately different everywhere and we cannot have specific commands for every OS.

**Comment by e-lisa** [comment]
Hi @fdennis I just wanted to echo @Jah-On's comment that "Unknown Error" might not be the best way to notify the user that "WARNING: PC/SC not available".  In my case it took me a few weeks before I thought to run the application from the command line. I think asking the user to see "Unknown Error" and then randomly guess that "running it via the command line will give new and different error messages is a big stretch.

Would it be possible to change "Unknown Error" to "Cannot connect to PS/SC service" ?

If so I'll try to submit a pull request. Thanks!

**Comment by Jah-On** [comment]
This sounds like a very reasonable solution!

**Comment by LosD** [comment]
@fdennis Could you AT LEAST add something like "IS the PC/SC daemon running"? The current error message is entirely unhelpful.

**Comment by fdennis** [comment]
@e-lisa @Jah-On @LosD Have you tried version 6.2.0? There should now be an error message saying "Failed to open smart card connection. Make sure pcscd is installed and running". Could you verify if that is the case for you?
