### ISSUE TITLE
Yubikey sleeps after about 15 minutes, have to replug it in constantly

### ISSUE THREAD

**Issue by auwsom** [Yubico/yubioath-desktop#789]
I'm not sure where the correct place to post this is, but it happens with several Yubikeys plugged into USB ports in Ubuntu 20.04 and 22.04, on a Dell T5600 workstation, and I believe on a Toshiba laptop. I could test it on a Window VM, but I'm not sure if using a USB passthrough would troubleshoot the issue.

Basically, as the title says it disconnects all the time, so I have to replug it in and there's no haptic feedback so I press it so many times until it works. I have it slot 1 and 2 swapped, but I think it happens on the ones without a swap (although usually those are used after a popup showing the system is looking for a key, which might issue a wake signal). It's a standard Yubikey 5 without NFC.

- Yubico Authenticator version: 
- Operating system and version: 
- YubiKey model and version: 
- Bug description summary: 

Steps to reproduce
---

[Please explain what you did when the bug appeared, and if and how you have been
able to reproduce it.]

Expected result
---

[What did you expect to happen when you did the above?]

Actual results
---

[What actually happened?]

Other info
---

[Anything else you would like to add?]

**Comment by fdennis** [comment]
Sorry for the late reply. Is this still an issue for you?
I suggest you contact support at https://support.yubico.com
I will close this issue since it is not related to Yubico Authenticator.
