### ISSUE TITLE
Yubikey NEO - Not able to see TOTPs on Desktop but able to see on Android with NFC

### ISSUE THREAD

**Issue by yencarnacion** [Yubico/yubioath-desktop#79]
Yubikey NEO Manager 1.4.0 tells me:
NAME: YubiKey NEO
Firmware: 3.3.0
Connection Mode: OTP+U2F+CCID
There are NO available apps

ykinfo -a output is
version: 3.3.0
touch_level: 1541
programming_sequence: 1
slot1_status: 1
slot2_status: 0
vendor_id: 1050
product_id: 116

How can I see the OTPs that I can see when using the Android App on my Desktop?
I am running Yubico Authenticator 2.3.0 on OSX 10.11.4

What I currently see is:  
If "Read from Slot x" is selected in preferences then "YubiKey slot x" in Yubico Authenticator
If no "Read from Slot x" are selected then "Insert a YubiKey ..."

**Comment by SueHeim** [comment]
I'm guessing you mean you want to see the TOTP authenticator codes on your Mac?

Are you using Yubico Authenticator for Desktop on your Mac system? Download and install it: https://developers.yubico.com/yubioath-desktop/Releases/yubioath-desktop-2.3.0-mac.pkg. If you are, and you are still having issues, please start a support ticket at https://www.yubico.com/support/raise-ticket/

Thanks!

**Comment by dagheyman** [comment]
It seems that the OS is having some problems with the CCID connection, even though CCID mode is enabled on the Yubikey. It is probably related to the libccid library. Please try to update to the latest version of OS X and install the Combo Update mentioned in this blogpost: http://ludovicrousseau.blogspot.se/2016/05/os-x-el-capitan-10115-and-ccid-driver_23.html
