### ISSUE TITLE
Authenticator leaks codes to Universal Clipboard

### ISSUE THREAD

**Issue by tusing** [Yubico/yubioath-desktop#792]
This is a security issue in all versions of Yubico Authenticator on macOS and iOS.

Authenticator leaks TOTP codes to all iCloud devices. This is a weakening of the security model of Authenticator, as if any iCloud device is compromised, it can steal the TOTP code and use it before the intended device.

Programs like 1Password explicitly prevent sharing clipboard content with Universal Clipboard. Yubico Authenticator on iOS and macOS should be doing the same.

**Comment by dainnilsson** [comment]
Hi.

Universal Clipboard (or any other clipboard sharing service) does indeed sync clipboard data, including potentially sensitive data, across your devices. Any such service should be used with care, with a good understanding of the tradeoffs involved.

When it comes to OTPs, I would say that a mitigating factor is that each code is only valid once, and typically for a very short period of time, and that each device needs to be logged in to your iCloud account, and your devices must be in close proximity to each other for clipboard sharing to be active. Lastly, as OTPs are used as a second factor, the OTP itself is never enough to get access to any account.

My general advice would be to weigh the pros and cons of using such a clipboard sharing service, and consider what threats you are trying to guard against when deciding whether or not to do so. Many of our users are willing to accept the increased potential risk for the convenience it offers, but everyone has to make that decision for themselves.
