### ISSUE TITLE
Yubico Authenticator as Flatpak

### ISSUE THREAD

**Issue by Chantology** [Yubico/yubioath-desktop#793]
- Yubico Authenticator version: 5,10
- Operating system and version: Linux Fedora 35
- YubiKey model and version: 
- Bug description summary: Enhancement / Feature Request

Flatpak is better integrated in the System and Software store. Snaps are unfortunately not supported as easily as Flatpaks nowadays. There is one version that is maintained by the community but I am not sure how well it is maintained:
https://flathub.org/apps/details/com.yubico.yubioath

**Comment by fdennis** [comment]
Hi,
We have discussed this with the Flatpak community and decided that right now we will only maintain the Snaps but we will also try to help the community with the Flatpak as much as we can. We cannot commit to maintaining both of these. The Flatpak is well maintained.

**Comment by Chantology** [comment]
thank you! Knowing that the Flatpak is well maintained is enough :)
I am new to linux and I prefer using them over Snaps
