### ISSUE TITLE
"Copy to clipboard" releals OTP tokens

### ISSUE THREAD

**Issue by WhyNotHugo** [Yubico/yubioath-desktop#795]
- Yubico Authenticator version: 5.1.0
- Operating system and version: Linux 5.17.7-arch1-2 GNU/Linux 
- YubiKey model and version: 5
- Bug description summary:

When I click the "Copy to clipboard" option and tap the yubikey, the code is shown on screen too. There is not point in showing the code, and it's a risk to display a secret when the user **has not** chosen to have it displayed. If I want to log into a website while screen sharing, this leaks the OTP. There is no reason to even display the code unless the user explicitly requests it.

### Steps to reproduce

- Right click on any entry
- Pick "Copy to clipboard"
- Tap the Yubikey.

### Expected result

The code should just be copied to the clipboard.

### Actual results

The code is copied to clipboard, and is also shown on screen for anyone that's around to be able to see it.

**Comment by fdennis** [comment]
Considering the OTP is single use and intended as a second factor, we don't see much benefit in hiding the code in this case. We will look into it further and might implement this or something similar in the future if there is sufficient demand for it. In general, I would recommend not logging in to sites while sharing your screen.

**Comment by WhyNotHugo** [comment]
I'm not suggesting to take extra action to hide it, I'm rather suggesting NOT revealing it.

I can avoid screen sharing, but I can't avoid using my laptop in public.

As a password manager, I think the primary focus should be "don't expose secrets unless needed". I don't see any reason to expose the codes in this case. What's the rationale for showing them without the user explicitly requesting this?

25 May 2022 10:05:55 Dennis Fokin ***@***.***>:
