### ISSUE TITLE
Enable Retina display mode on Mac.

### ISSUE THREAD

**Issue by robbiet480** [Yubico/yubioath-desktop#8]
The app looks really pixelated right now on both my MacBook Pro with Retina Display and my 4k monitor running at 2x (HiDPI) mode.

**Comment by jtl999** [comment]
Yup. Still a problem

Does PySide and QT support HiDPI displays?

**Comment by jtl999** [comment]
Well it does kinda work if you build from source :)

https://i.imgur.com/GWgPokm.png

**Comment by dagheyman** [comment]
Thank you for the reports, will look into why this is happening.

**Comment by dagheyman** [comment]
So, this seems to be solved by adding 

```
<key>NSPrincipalClass</key>
<string>NSApplication</string>
<key>NSHighResolutionCapable</key>
<string>True</string>
```
to the Info.plist file found in the .app bundle. 
Source: https://blog.qt.io/blog/2013/04/25/retina-display-support-for-mac-os-ios-and-x11/

We will do this to upcoming releases and you should also be able to fix this in your existing installation by editing the file manually.
