### ISSUE TITLE
Steam Authenticator Codes

### ISSUE THREAD

**Issue by im-richard** [Yubico/yubioath-desktop#803]
- Yubico Authenticator version:  **v5.1.0**
- Operating system and version:  **Windows 11**
- YubiKey model and version:  **5 NFC / v5.2.6**

So sorry if this has already been explained, but I'm having a headache here.

I read through #72  in terms of this being a possibility to add Steam Authenticator codes to your Yubikey, but unless I'm missing something, the instructions appear to be on Linux for the most part.

I've attempted to read the documentation, but I'm using PowerShell / CLI with ./ykman and having no luck finding the syntax so that I can add the TOTP URL with the steam secret and digits=5 since the GUI version only allows for 6+ digits.

**Comment by fdennis** [comment]
Try adding "Steam" to the Issuer field, that should fix it. If you are using ykman CLI, try this ` ykman oath accounts add NAME -i Steam`

**Comment by im-richard** [comment]
Do I need to add the # of digits or the secret key? Just don't want to execute the command until I have the full syntax, last thing I need to do is insert something invalid and have a mess I have no idea how to clean up.

**Comment by im-richard** [comment]
Oops

**Comment by fdennis** [comment]
After you execute that command it is going to prompt you for the secret key. Number of digits is not necessary to add. Afterwards, try listing the account by doing `ykman oath accounts code`. If you are not happy with the account you just added, or something went wrong, you can always delete it - `ykman oath accounts delete NAME`.
All of this is possible in the Yubico Authenticator app as well, if you'd like a GUI.

**Comment by im-richard** [comment]
I'd buy you a beer.
Thanks a bunch. This worked great. Even confirmed the codes with Google Authenticator and everything matches perfect.

Yeah I was aware of the GUI method to delete, but for some reason it always throws "Unknown Error" when you attempt to delete them, and you have to completely close the Yubi Authenticator and re-open.

**Comment by fdennis** [comment]
As far as I know, it is not available for Blizzard's.

**Comment by fdennis** [comment]
I will close this issue.
