### ISSUE TITLE
trusty package in ppa is out of date

### ISSUE THREAD

**Issue by robkorv** [Yubico/yubioath-desktop#86]
Hi,

Is it possible that the trusty package gets updated to the newest [release](https://github.com/Yubico/yubioath-desktop/releases)?
Right now it is stuck on an old release: https://launchpad.net/~yubico/+archive/ubuntu/stable/+packages?field.name_filter=yubioath-desktop&field.status_filter=published&field.series_filter=trusty

**Comment by ntrepid8** [comment]
I've got the same issue.  The updated xenial package (version 3.0.1-1) works fine but on another machine with trusty (version 2.3.0-1) my yubikey is no longer detected.  I've tried cloning the repo and building the package myself and was not able to complete it on the first try.

I'll give it another go tomorrow but it would be great to have the ppa updated.

**Comment by robkorv** [comment]
I have that some problem. Key works (OTP+CCID) like it should on xenial (version 3.0.1-1). On trusty (version 2.3.0-1) it doesn't get recognized (OTP does work).

**Comment by robkorv** [comment]
Uhm, for some reason is does work now. Don't know why... but I see multiple stored TOTP in yubioath.

![yubico authenticator 2 3 0 _014](https://cloud.githubusercontent.com/assets/4266355/16830782/4b16cdd0-49a1-11e6-8679-3c9fb44156f3.png)

What I did:
* fresh install of ubuntu desktop
* no yubikey inserted
* `sudo add-apt-repository ppa:yubico/stable`
* `sudo apt-get update`
* `sudo apt-get dist-upgrade`
* `sudo apt-get install yubikey-neo-manager yubikey-personalization-gui yubioath-desktop`
* `sudo reboot`
* insert yubikey, make sure CCID is enabled.

I didn't test FIDO U2F yet.

**Comment by a-dma** [comment]
are the multiple entries for the same credential? Is the TOTP code the same? I assume no to both...

As for versions, I don't know if there are specific reasons for not having 3.0.1 packages for all Ubuntu releases (I don't think so). The maintainers for this project are currently unavailable, I'll ping them about this, but it's probably gonna take a couple of weeks.

**Comment by robkorv** [comment]
> are the multiple entries for the same credential? Is the TOTP code the same? I assume no to both...
It now works as expected. I see multiple different TOTP's on my key in trusty, just like in xenial.

Tnx for pinging the maintainers @a-dma.

**Comment by a-dma** [comment]
> It now works as expected. I see multiple different TOTP's on my key in trusty, just like in xenial.

Oh sorry, I thought you meant that as in "I see more credentials than I was expecting". Glad that it's working.

**Comment by robkorv** [comment]
Ok, I still don't know why it works now in trusty... but I got it working with the current ppa versions. Including the previsious steps:

I have a [yubikey-neo](https://www.yubico.com/products/yubikey-hardware/yubikey-neo/)

What I did:
* fresh install of ubuntu desktop trusty
* no yubikey inserted
* `sudo add-apt-repository ppa:yubico/stable`
* `sudo add-apt-repository ppa:gertvdijk/ccid-backports` <-- needed for u2f
* `sudo apt-get update`
* `sudo apt-get dist-upgrade`
* `sudo apt-get install yubikey-neo-manager yubikey-personalization-gui yubioath-desktop`
* `cd /etc/udev/rules.d`
* `sudo wget https://raw.githubusercontent.com/Yubico/libu2f-host/master/70-u2f.rules`
* `sudo chmod 0644 70-u2f.rules`
* `sudo reboot`
* insert yubikey, start neo-manager and enable OTP+U2F+CCID.

Now the key works the same as in xenial.

**Comment by ntrepid8** [comment]
I was able to get the current version of `yubioath-desktop` to work on trusty by running the `linux-path-ccid` script from this repo.  I think several entries in `/etc/libccid_Info.plist` were missing.  Before running the script there were two entries, and after there were four.  Anyway, it works now :)

**Comment by robkorv** [comment]
@ntrepid8 does u2f works without updating ccid and adding `70-u2f.rules` to udev?

**Comment by a-dma** [comment]
@robkorv there is a script in the repo to update `libccid_Info.plist`, you can find it [here](https://github.com/Yubico/yubioath-desktop/blob/master/resources/linux-patch-ccid).

You need udev rules to make the `hid` device accessible by unprivileged users in your systesm

**Comment by ntrepid8** [comment]
Would it make sense to run that script as part of the post-install script of the deb package?  Is there any reason not to run it?

**Comment by a-dma** [comment]
In recent versions of libccid there is no need for that script since the definitions are included, but for older versions I don't see any harm in running it as a postinst except that they are a bit fragile, but that's not too big of an issue.

@dainnilsson opinions?

**Comment by dagheyman** [comment]
Since you both got the older version to work on trusty, I'm closing the issue. The main reason for not providing trusty packages for 3.0.1 is that we introduced a new dependency, [python-click](https://launchpad.net/ubuntu/+source/python-click), not available in trusty.

Since `/etc/libccid_Info.plist` doesn't need to be patched in later versions of Ubuntu, I don't think it's worth making the `linux-path-ccid` script part of the installation.

**Comment by nealmcb** [comment]
Thanks for the hints, folks!

The script to update libccid_Info.plist has moved: I see one here now:

https://github.com/Yubico/yubioath-desktop-dpkg/blob/master/resources/linux-patch-ccid

It seems to have worked to run these commands (edited from my transcript), to get Yubikey 4 PIV working on Ubuntu Trusty 14.04.5.
Note that I avoid running some random Python script as root, but instead allow it to only change a single file temporarily, and check the results. The script thus fails when restarting the daemon
    `start-stop-daemon: warning: failed to kill 4591: Operation not permitted`
so I do that manually instead.

```bash
wget https://raw.githubusercontent.com/Yubico/yubioath-desktop-dpkg/master/resources/linux-patch-ccid
sudo cp -p /etc/libccid_Info.plist /etc/libccid_Info.plist-save
sudo chmod o+w /etc/libccid_Info.plist
python ./linux-patch-ccid 
sudo chmod o-w /etc/libccid_Info.plist
diff /etc/libccid_Info.plist /etc/libccid_Info.plist-save
sudo service pcscd restart
yubico-piv-tool -a status  # Success!
```
