### ISSUE TITLE
UnwrapValueError

### ISSUE THREAD

**Issue by TobiNinja** [Yubico/yubioath-desktop#873]
Hi,
a colleague of mine is using her Yubikey since some time. Since today when plugging in the key in the USB port of her Windows laptop the follow error message is shown
![image](https://user-images.githubusercontent.com/12623591/207095973-9c88e42a-f622-44b0-b8aa-65f812667c56.png)
Version Authenticator App: 6.0.2
Yubikey is a 5C NFC, Firmware 5.4.3
Windows: Windows version:  10,0,19044
We tried also to run as admin, but no success.. 
Any idea, what the error might be related to? Hardware issue?

Thanks!!

**Comment by dainnilsson** [comment]
Hi! This is an issue with the OATH "remembered password" function. There's a fix for this behavior in #853 which will be included in the next version of the app. You can manually delete the `oath_keys.json` file in C:\Users\<username>\.local\share\ykman\ as a workaround for now.

**Comment by TobiNinja** [comment]
Worked... Perfect... Thanks for the fast and competent help... Any idea, when the next version will be made available? If this is within the next days fine, otherwise I might have to write here an internal "how to" for the workaround :-)

**Comment by dainnilsson** [comment]
Unfortunately we'll need a bit more time before the release, we're aiming for sometime January.

I would like to better understand what might be causing the issue in the first place though. Basically the "remember password" feature is what creates the `oath_keys.json` file in the first place, and uses a key stored in the Window keyring to decrypt it. The error occurs when the key isn't able to decrypt, meaning either the key or the `oath_keys.json` file has become corrupted. The fix we have now will essentially do what deleting the file manually does, which is to allow the app to keep going, and just prompt for your password again.

If there's anything you can share about what might have triggered this to happen in the first place I'd love to know. Likewise if it happens again, or if you spot any pattern to when it happens.

**Comment by TobiNinja** [comment]
Hi, unfortunately we are not really able to reproduce the issue. it happened with just one colleague. But if there is a further occurance, I will try to do some further investigations.
Thanks again for your support!
