### ISSUE TITLE
Credential with colon in name doesn't work?

### ISSUE THREAD

**Issue by jas4711** [Yubico/yubioath-desktop#91]
I'm adding the ownCloud QR credential below, but it doesn't seem to work. If I remove the ':' from the credential name, it works.  Are the names split on colons somehow?

Yes I have revoked this credential :-)

![badqr](https://cloud.githubusercontent.com/assets/531817/17809415/bce3d2fa-6616-11e6-8335-cb082fa625a5.png)

**Comment by dagheyman** [comment]
Well yes, the credential names are split on colons, as the colon is used to identify the "issuer" prefix. See [this link](https://github.com/google/google-authenticator/wiki/Key-Uri-Format#label).

> Neither issuer nor account name may themselves contain a colon.

**Comment by jas4711** [comment]
I take it that this means the QR is not following that spec.  Right now this result in unexpected behaviour: the credential is simply not stored on the YubiKey.  Would it be possible to do something better?  Either just remove the colons or transpose them to some other character.  An error message is also a possibility, but that is usually bad user interface design.

**Comment by dagheyman** [comment]
Actually it seems that it's not the colon that's making the credential fail, but the length of the name. The name is 65 bytes long, and the maximum length allowed on YubiKeys is 64 bytes. So deleting a character anywhere in the name adds the credential with "https" as the issuer...

This should be handled better, the user should probably be asked to shorten the name to 64 characters or less.
