### ISSUE TITLE
Keyboard shortcuts ctrl-q or ctrl-w to close window?

### ISSUE THREAD

**Issue by jas4711** [Yubico/yubioath-desktop#92]
How about adding keyboard shortcuts for closing the window?  Ctrl-q is standard.

**Comment by rmenessec** [comment]
+1

I'd really like to see this, on all platforms. Preferably with configurable shortcuts. (I use Ctrl+Shift+Q to make it harder to exit programs accidentally.)

**Comment by dagheyman** [comment]
Keyboard shortcuts are added in version 4.0.0
