### ISSUE TITLE
HMAC-SHA256 TOTP support

### ISSUE THREAD

**Issue by tycho** [Yubico/yubioath-desktop#97]
I have another case of an unfortunate and obscure OTP type, provided by an authenticator that my bank uses. They use the Entrust IdentityGuard authenticator. I attached an Android debugger to it and extracted the OTP key, but found that they use HMAC-SHA256 instead of the much more prolific HMAC-SHA1. I can use oathtool to generate Entrust IdentityGuard compatible OTP keys by doing:

```
$ oathtool -v --totp=sha256 --digits=8 fd33e2e8ad3cb1bdd3ea8f5633fcf5
```
**NOTE**: Not my real key -- just a truncated md5sum of 'hi there', since their seed size is 15 bytes.

Any chance you could implement HMAC-SHA256 for OATH?

**Comment by adammorley** [comment]
out of curiosity, does anyone have a nice way to extract the secret?  i messed around with android studio in debug mode, but it's a total cluster-f.

**Comment by emlun** [comment]
No, there's no way to extract TOTP secrets from the YubiKey.

**Comment by tycho** [comment]
@emlun I think he meant from the Entrust IdentityGuard app.

**Comment by emlun** [comment]
Oh, ok. Thanks @tycho.

In that case, please move that discussion to the discussion channel(s) for that app instead.

**Comment by adammorley** [comment]
Thanks.  I was hoping to pull the secret from entrust and put it on a yubikey instead, so I thought somebody might know how to do that.  Entrust isn't exactly helpful since they have their nice walled garden already.
